### ISSUE TITLE
Add Directive snippets to Webstorm Template (ng-d)

### ISSUE THREAD

**Issue by marchitos** [johnpapa/angular-styleguide#117]
Webstorm Template miss the snippet for directive creation, in Sublime Text that snippet is bound to ngdirective

**Comment by belchugov** [comment]
I'm looking for the same missing snippet today, so +1

**Comment by johnpapa** [comment]
Feel free to make a PR

**Comment by joshtoo** [comment]
Also Covered in #537

**Comment by MAustinMMDP** [comment]
@johnpapa - this can be closed as it is covered with PR #544
