### ISSUE TITLE
Undef option in JSHint

### ISSUE THREAD

**Issue by 5im0n** [johnpapa/angular-styleguide#165]
I think something is wrong with the named function.

```
angular
    .module('app')
    .controller('SomeController' , SomeController);

function SomeController() { }
```

With this notation JSHint raise a warning cause SomeController was used before it was defined.

**Comment by Ganbin** [comment]
I dont see the equivalent of latedef in jslint. I can't achieve to use this best practice for angular and make it live in harmony with my jslint. I get error in all my pages because all the function are 'used before defined'. Anybody have an idea?

**Comment by julienmartin** [comment]
@Ganbin same as JSHint. Use 'nofunc'.

See : http://jslinterrors.com/a-was-used-before-it-was-defined

**Comment by Ganbin** [comment]
@julienmartin Thanks for suggestion but this options is not available in JSLint.

But anyway after deep meditation about how to write my code. I will not follow the angular guideline that say we should put all the "readable" part on top and all the function with code on the top. But that mean we implicitly know that Javascript will do hoisting. Of course good Javascript developer know that. But new comers can broke them head on small things like that.

I think we should not organize the code for our own ease to read but to write code that we know exactly what it does. So for this rule : [Function Declarations to Hide Implementation Details](https://github.com/johnpapa/angular-styleguide/blob/master/a1/README.md#style-y053) I will prefer to do the code in the "To Avoid" code snippet. The only difference is that I will go to the end of my file to see the method that are implemented. All the details will be on top.

For me this is more logic.

First we declare the implementation and write the code. So the script will have all informations to know before to return or execute anything. Actually this is the same like the other solution except that I write my code exactly how it gonna be executed after hoisting.

**Comment by gkalpak** [comment]
<sub>LoL - it's exaclty the same except that it's the exact opposite :stuck_out_tongue: </sub>

**Comment by Ganbin** [comment]
@gkalpak That's it. :D

**Comment by dietergeerts** [comment]
@Ganbin , I can't agree on that. We SHOULD write code so that it's easier to read. When you need to go through code that you have not written, or it's been a long time since you have seen it, it will be faster to find the piece you need when it's written in a way it's easy to read. Code should be written like those story books where you choose your path. You begin with the main story, and if you are interested in a part, you click through (with a good IDE) to a sub-story etc.... This way it is easy to navigate.

Plus: a beginner should know some basic stuff before actually beginning to write some code. The hoisting stuff IS such BASIC stuff.

**Comment by Ganbin** [comment]
Actually its a personal choice to use the bad parts of javascript to write his code. I prefere to write code the way it will be executed.

For me I feel something strange when I was using the hoisting. I prefere to declare the things before I use it. And you are right to choose the SHOULD word. And beginners will not know all the basic stuff. Specially with javascript which give you so much freedom to write your code.

As gkalpak said I just do the exact opposite. And with the scroll bar of any IDE it take 0,2 seconds to go down the file. You will see all the exported stuff as it was at the top.
I use this revealing pattern : https://addyosmani.com/resources/essentialjsdesignpatterns/book/#revealingmodulepatternjavascript

**Comment by pabloleone** [comment]
I don't understand why this is the standard. As a PHP developer,  I won't use a variable that's not declared previously, it's a terrible practice!

I understand how JavaScript works, but isn't readable. In the style-guide, the example states a function and the use of it in the same file under the same scope, but that doesn't cover all scenarios. So I don't understand why do we adopt that as the standard when it's weird for the majority of other languages and even for a simple reasoning.

**Comment by brion-fuller** [comment]
@Ganbin I would have to disagree about function declaration hoisting as a bad part of JavaScript.   Defining functions at the end of a file is more readable to other users, I shouldn't have to scroll down to the end of a file to see what I can actually use.  If you do need to know more about the logic of a function you can navigate to the definition.  
@pabloleone I see this kind of pattern done in almost any language I have worked in (C++,C#,Java, ColdFusion, Python), private functions are defined below and public functions up top.  I find it bad practice to have someone search a file when they just need an overview.
