### ISSUE TITLE
Controller as  -  for forms

### ISSUE THREAD

**Issue by mLaird** [johnpapa/angular-styleguide#175]
The Controller as section is excellent for the things it covers, but it needs a specific discussion of controllers for forms.  I'm seeing various approaches when I Google the subject - like go back to $scope for the form,  use controller as form (but not much further explanation), and this approach in the link -  http://www.technofattie.com/2014/07/01/using-angular-forms-with-controller-as-syntax.html 

Forms get complicated and can have nested controllers.  Your thoughts on this subject would be appreciated.

**Comment by johnpapa** [comment]
Interested in making a PR?

**Comment by johnpapa** [comment]
Going to close this unless someone has a recommendation on how to PR this

**Comment by MarkAPhillips** [comment]
Feel free to close - I do not have time at the moment - thanks
