### ISSUE TITLE
Watch and this

### ISSUE THREAD

**Issue by zgababa** [johnpapa/angular-styleguide#176]
Hi, 

I think there is a mistake in **controllerAs with vm** -> [Style Y032] section, I can't reproduce the example. 

HTML

```
<div class="container" ng-controller="TestController as d">
    <input type="text" ng-model="d.title">
</div>
```

From the styleguide

``` javascript
var vm = this;
this.vm = "Hi";
$scope.$watch('vm.title', function(current, original) {
    $log.info('vm.title was %s', original); 
    $log.info('vm.title is now %s', current); // Nothing happen, when I typing
});
```

But that works (from the tuto controllerAs http://toddmotto.com/digging-into-angulars-controller-as-syntax/)

``` javascript
 var vm = this;
 vm.title = "";

  $scope.$watch(function () {
      return vm.title;
    }, function (current, original) {
      $log.info('vm.title was %s', original);
      $log.info('vm.title is now %s', current);
  });
```

Am I wrong or not ? 

Thanks !

**Comment by Errvald** [comment]
This doesn't work if in the ``.state`` controller is ``  'Controller as test' `` ,  ``$scope.$watch('vm.title'...`` is ``undefined``.

**Comment by ikantthink** [comment]
@Errvald You are totally right on that. As @rhullah mentioned, if you use controller as you will need to watch test.title... `$scope.$watch('test.title'...`

**Comment by Sspeed5cm** [comment]
@zgababa Thanks! Your new HTML works for me!

**Comment by mnewmedia** [comment]
Defintily confusing. I was refactoring while reading:

1. controllerAs View Syntax (OK changed)
2. controllerAs Controller Syntax (OK changed)
3. controllerAs with vm (OK Changed)
4. Note: When creating watches (Failed - since I also did Follow **1.**)
