### ISSUE TITLE
Cover ESLint as an alternative to JSHint 

### ISSUE THREAD

**Issue by alecxe** [johnpapa/angular-styleguide#194]
I think [Code Analysis](https://github.com/johnpapa/angularjs-styleguide#code-analysis) part needs to contain a note about [`ESLint`](http://eslint.org/). 

`ESLint` is pretty mature, actively developed and, most importantly, it is customizable and extendable via custom rules. Therefore, there are different `ESLint` plugins out there: for example, [`eslint-plugin-angularjs`](https://www.npmjs.com/packages/eslint-plugin-angularjs). IMHO, worth mentioning.

What do you think? Thanks.

**Comment by johnpapa** [comment]
This one has some promise https://github.com/Gillespie59/eslint-plugin-angular by @Gillespie59

**Comment by alecxe** [comment]
Up until now we've been using https://github.com/sahibinden/eslint-plugin-angularjs, but the one you've mentioned looks more mature and active and it also has references to the specific paragraphs in the guideline - I'll definitely give it a try. Thank you!

**Comment by Gillespie59** [comment]
What about refering the eslint-plugin-angular plugin in the guideline ?

**Comment by johnpapa** [comment]
Sounds like a good idea for a PR :) hint hint

**Comment by Gillespie59** [comment]
I will send a new PR today.

**Comment by Gillespie59** [comment]
We remove the JSHint bloc ? and provide the same JSON configuration object for ESLint ? And add a link to the Angular plugin ?

**Comment by johnpapa** [comment]
Not sure I understand the question. JSHint is still valid, ESLint would just be for the custom styles for this style guide. So whatever gets pushed for this style guide would be just to run the style for this guide, and not to conflict with any rules form JSHint.

**Comment by Gillespie59** [comment]
In fact, ESLint give the possibility to use the same rules provided by JSHint. 

So in order to have only one Lint tool in our workflow, ESLint, it is possible de delete your JSHint guideline. And provide the same information (the JSON configuration object) for ESLint, in addition to the eslint-plugin-angular configuration. 

Or if you prefer, we can add ESLint only for eslint-plugin-angular.

**Comment by johnpapa** [comment]
just as a plugin for the styles. closing this one , but please make the PR.

**Comment by alecxe** [comment]
Thank you guys for doing this.
