### ISSUE TITLE
Mention the $destroy event, and why you should use it

### ISSUE THREAD

**Issue by westor21** [johnpapa/angular-styleguide#271]
from angular.js documentation:
"Best Practice: Directives should clean up after themselves. You can use element.on('$destroy', ...) or scope.$on('$destroy', ...) to run a clean-up function when the directive is removed."

In the destroy function I would set all references to objects to null.
I suggest to keep the destroy function in the top, directly below the variables declaration block. That makes it easy to compare, what has to be cleaned up.

**Comment by johnpapa** [comment]
I agree there are best practices for directives and other components to stay performant. For example, removing a directive isolate scope before removing the element in the $destroy. 

This is a fuzzy line in the style guide, tho. I think these types of things belong more in a tips guide (hint hint). There comes a point where this style guide is too large to traverse and I am careful to keep it digestible.

**Comment by westor21** [comment]
Ah ok, I see your point. And I agree - this style guide can't cover everything around.
But most of us, including me, did not much care about memory usage. Most examples do not mention $destroy.
Large applications deal usually with a lot of components which are often added to or removed from DOM. I'm not sure but I could imagine that garbage collection could not perform well without destroying object refrences.

**Comment by johnpapa** [comment]
agreed and added https://github.com/johnpapa/angular-styleguide#style-y070
