### ISSUE TITLE
Y075 bindToController example

### ISSUE THREAD

**Issue by bensurman** [johnpapa/angular-styleguide#295]
Thanks for the excellent guide, I've been using it a lot!

I have a question related to bindToController with a link function.  The example shows the link function like so:
```javascript
function linkFunc(scope, el, attr, ctrl) {
        console.log('LINK: scope.min = %s *** should be undefined', scope.min);
        console.log('LINK: scope.max = %s *** should be undefined', scope.max);
        console.log('LINK: scope.vm.min = %s', scope.vm.min);
        console.log('LINK: scope.vm.max = %s', scope.vm.max);
 }
```

But as the controller is now passed in and has the scope bound to it, wouldn't it make more sense writing it like this?
```javascript
function linkFunc(scope, el, attr, vm) {
        console.log('LINK: scope.min = %s *** should be undefined', scope.min);
        console.log('LINK: scope.max = %s *** should be undefined', scope.max);
        console.log('LINK: vm.min = %s', vm.min);
        console.log('LINK: vm.max = %s', vm.max);
}
```

**Comment by johnpapa** [comment]
The link function does not have access to the `vm` variable.

**Comment by bensurman** [comment]
The link function has access to the controller directly via its fourth argument.  I named it `vm` instead of `ctrl` for consistency.   Working example at http://codepen.io/anon/pen/wBxNgv

**Comment by johnpapa** [comment]
ah, i didnt see you passed it in. yep, that works too. feel free to PR it and ADD that case.
