### ISSUE TITLE
Create templates for Brackets

### ISSUE THREAD

**Issue by johnpapa** [johnpapa/angular-styleguide#299]

**Comment by sanjeyac** [comment]
Hi! 
I read your style guide and I created a set of snippets for Brackets based on the guide
Here it is [https://github.com/sanjeyac/angularjs-snippets-for-brackets]

**Comment by johnpapa** [comment]
these are great. i had started a file based on EDC and if you see any additional ones that are useful, please make a PR here

**Comment by johnpapa** [comment]
could use one for "ngwhen" too

**Comment by johnpapa** [comment]
@sanjeyac please feel free to add ngwhen and suggest any others you feel are worth it here https://github.com/johnpapa/angular-styleguide#style-y254

**Comment by johnpapa** [comment]
closing this one, but feel free to make that PR

**Comment by sanjeyac** [comment]
Do you mean a "ngwhen" and a "ngroute" of the standard router provider?
