### ISSUE TITLE
Webstorm Template Issue

### ISSUE THREAD

**Issue by GeoffreyEmery** [johnpapa/angular-styleguide#301]
Hey John,
  Thanks for the all the hard work your doing on this its really appreciated. I am using webstorm and I noticed that your file templates don't work properly when you name your files with a dot notation as recomened in the guide. user.Controller - user.Template.tpl.html.  
Here is a fix for the controller: 
simply set a temp variable and then do a string replace on it. Velocity templates are a bit weird but this works for me it of course strips the period out of the name, but could be replaced with a underscore. 
'''
#set( $a = ${NAME} )
#set( $safeName = $a.replace('.', '') )
${safeName}
 (function() {
    'use strict';
    
    angular
        .module('${moduleName}')
        .controller('${NAME}', ${safeName});
        
    ${safeName}.${DS}inject = ['${dependency}'];

    /* @ngInject */
     function  ${safeName}(${dependency}){ 
        /* jshint validthis: true */
        var vm = this;
        
        vm.activate = activate;
        vm.title = '${NAME}';

        activate();
        
        ////////////////
        
        function activate() { }
    }
})();
'''

**Comment by matheussampaio** [comment]
I have the same issue. Can you guide me how to solve?

**Comment by johnpapa** [comment]
great! make a pull request?

**Comment by GeoffreyEmery** [comment]
@matheussampaio you can change the livetemplate file settings just insert my code above in it... @johnpapa is there a slick way to do a export of the webstorm settings that is just for this? Your code comes in a jar should i just make a new project import your stuff fresh and then make the change and export it back up as a jar? or would it be better as a single live template page for each one?

**Comment by ticlaudeberube** [comment]
How can I get the templates to show in new File menu in webstrorm 10.4.  I can use the ng-, but the new file templates are not shown as described in the Pluralsight tutorial.

**Comment by johnpapa** [comment]
going to close this for inactivity unless someone wants to make a PR

**Comment by ticlaudeberube** [comment]
Somehow, I can't see the templates in the new file menu. is there a way to
add them manually?

Would certainly like to add IIFE to the template list. I have it already, I
would need to post the code.

Thanks,

Claude

**Comment by joshtoo** [comment]
@johnpapa - IMO this is all covered in #537

**Comment by MAustinMMDP** [comment]
@johnpapa - this can be closed as it is covered with PR #544
