### ISSUE TITLE
Manually Identify Dependences; Order of Execution Question

### ISSUE THREAD

**Issue by larkintuckerllc** [johnpapa/angular-styleguide#303]
First, *wow* on this style guide...

In the section [Y091](https://github.com/johnpapa/angular-styleguide#style-y091), the sample code has the $inject property being set after the usage immediately before it.  I understand that the function is hoisted, but I cannot figure out how $inject is being set before the call that uses the function.

What am I missing (guessing it is a newbie JavaScript thing)?

```
/* recommended */
angular
    .module('app')
    .controller('Dashboard', Dashboard);

Dashboard.$inject = ['$location', '$routeParams', 'common', 'dataservice'];

function Dashboard($location, $routeParams, common, dataservice) {
}
```

**Comment by Markionium** [comment]
The explanation is probably that the function is being passed as a parameter in the `.controller` call. It is not called directly after that so therefore it is possible to still set the property `$inject` onto that object.

When the function gets called when the app bootstraps the inject property will be set.

**Comment by larkintuckerllc** [comment]
Ahh... (thanks to @Markionium) it was a newbie JavaScript (AngularJS) thing.  Defining the controller is separate from instantiating it and because JavaScript is single threaded, I can guarantee that the $inject gets set before it has a chance of being instantiated.

**Comment by 6temes** [comment]
Sorry to piggyback this thread but, incidentally, is this syntax minification-safe?

**Comment by larkintuckerllc** [comment]
Actually the whole point of $inject is to allow for minification. Explaination is available at [Developer Guide / Dependency Injection](https://docs.angularjs.org/guide/di); there is specific section on $inject.

**Comment by 6temes** [comment]
+1
