### ISSUE TITLE
Semantic ControllerAs (replace 'vm = this' with meaning)

### ISSUE THREAD

**Issue by ehorodyski** [johnpapa/angular-styleguide#307]
One minor but very big change my team has made from the stock Style Guide is to replace the `vm = this` in our controllers with more meaningful, contextual names. 

For instance, with the samples given in the guide as it stands, our changes would look something like:

    function AvengersController(){
        avenger = this;
        avenger.name = "Hawkeye";
        avenger.power = "Archery";
    }

What this small, semantic change does is drastically increase readability in our code base. It especially helps when using related files, such as views, so that we bind to `<span ng-model=avenger.name></span>` which clarifies intent.

This becomes even more useful when we are nesting and/or traversing an object. When having to nest directives together using a more contextual approach leaves us with much more readable HTML:

    <ul ng-repeat="items in order">
        <li>{{item.name}}</li>
    </ul>

This is probably the road much traveled, but by including this in our JavaScript we have found that our code is much more readable and the intent is clearer than using the generic `vm = this;` structure found in the guide. It would be _the_ one thing I would append to this Style Guide, while other changes we have made were for the team's inclusion into the world of Angular, not for the good of the community as a whole.

**Comment by kylecordes** [comment]
I think your example above has a couple problems. Most notably, you described a template with "ng-model=avenger.name", but the "avenger" in here would be the "controller as" alias, which has nothing to do with what you named the this-capturing variable inside a controller.

**Comment by ehorodyski** [comment]
@kylecordes -- I've come across some of our devs doing `ControllerAs` and binding the controller to `vm`. We have some dev code that has `ng-model="vm.name"`.

Also, I'm an awful commenter/poster (people StackOverflow-shame me) because sometimes I rush through ideas to get them out, and refine them later. With a few hours left before bed -- I'm sure I missed some things because I was in a hurry to start the house's "bedtime" situation.

I still stand firm on using more semantic aliases for `this` in Controllers, et. al. It's a minor change that I've gotten a lot of positive feedback on and really seems to help solidify intent. Is `vm` an Avenger? The entire roster? By giving it a semantic name `avenger`, I can tell on line one that we are dealing with something like _an_ Avenger's profile page, not a page for >1 Avengers.

**Comment by kylecordes** [comment]
I agree with you about semantic aliases. We recently switched in some work here from typically naming these "that" to typically naming them "vm", partly to comply with this style guide. It is an improvement, but once they are all named vm the improvement is mostly that it is easier to visually distinguish vm from that.

I think it is a better style to guide people toward choosing different names for the "this" alias in different controllers. But this is not my style guide. :-)

**Comment by ehorodyski** [comment]
@kylecordes Not mine either, but I'm hoping I can contribute!

**Comment by johnpapa** [comment]
I find `vm` in the controller to  always be obvious  as it is the View Model.  In the HTML context is more important as multiple controller's and vm's may exist, but not in the controller.

Thanks for the discussion though.
