### ISSUE TITLE
controllerAs: 'vm' conflicts with new router component

### ISSUE THREAD

**Issue by kpgarrod** [johnpapa/angular-styleguide#309]
It seems to me that the new router has an implicit scope object which ties to the component name. This seems to conflict with https://github.com/johnpapa/angular-styleguide#style-y032, which recommends using controllerAs: 'vm'. Should we now be using controllerAs: 'componentName' instead of controllerAs: 'vm'?

I commonly pass data into my controllers via $state promises as recommended https://github.com/johnpapa/angular-styleguide#style-y081. Typically, if I am resolving a movie from my movieService, I would   pass it to MovieController as 'movie' and add it to the scope as 'vm.movie'. 

If I use the implicit scope name from a new router component, I would end up with 'movie.movie'. That doesn't look right. Any suggestions on how to handle these issues with the new router? Am I missing something?

**Comment by wardbell** [comment]
Without documentation it is difficult to say exactly how the *out-of-the-box* conventions play out. 

What is clear from looking at the code is that the JS "component" referenced by the new router does NOT take a scope and is in "As VM" style. There is no "implicit scope object"; the view is bound to an instance of the controller (instance of the "component" in ng 2.0).

But I take your main point. Judging by [this example](https://github.com/angular/router/blob/master/examples/angular-1/hello/app.js), you are expected to refer to the "controller/component" either by **its root filename** or **by its registered camelCase name**, minus the "Controller" suffix. We'd have to play with it to determine how this actually works.

Here is "[welcome.js](https://github.com/angular/router/blob/master/examples/angular-1/hello/components/welcome/welcome.js)"

    angular.module('example.welcome', []).
        controller('WelcomeController', WelcomeController);

    function WelcomeController() {
      this.heading = 'Welcome to The New Angular Router Demo!';
    }

Here is "[welcome.html](https://github.com/angular/router/blob/master/examples/angular-1/hello/components/welcome/welcome.html)"

    <section>
      <h2>{{welcome.heading}}</h2>
    </section>

Also troubling for the style guide is that the router convention appears to demand that the root name of the controller file be the same as the root name of the html file. That means we'd have to change the style guide's recommended *welcomeController.js* to *welcome.js*.

As for your example, if you call the property `movie` and you name your controller *movie.js*, you'll get `movie.movie`. I don't see a way around that ... other than to choose a different name for the controller or the property.

**Comment by kpgarrod** [comment]
@wardbell Thanks for your thoughts. I may have used the term 'implicit scope object' incorrectly but we have the same understanding of the issue. 

Practically, my controllers would normally be called something more descriptive than 'movieController', so your instinct is probably right - movieViewer.movie looks fine.

A related issue is that I will often use the same template for newMovieController and movieEditorController.  That works fine if both controllers are `controllerAs: 'vm'`, but if one is 
`controllerAs: 'newMovie'` and the other `controllerAs: 'movieEditor'`, they obviously won't be able to share a template or ng-include. I suppose a movieForm directive/component would solve the problem. Any thoughts on that?

I guess this conversation may be a bit premature or misplaced, so I'm happy to wait for 1.4 to be officially released.

Maybe this will become clearer once 1.4 is officially released.

**Comment by dietergeerts** [comment]
Don't use controller or controllerAs in your route config and use just a templateUrl. You will then have two templates in which you can define the template and controller pair you want through ng-include.

**Comment by johnpapa** [comment]
i'm not sure what the action item is here yet

**Comment by wardbell** [comment]
The question at issue: should we recommend that the controllerAs variable name be "welcome"  instead of "vm".

Of course this is a 1.x style guide. But it does aspire to recommend styles that are as easy to migrate to v.2 as possible.

And if we recommend the new router in v.1.x (whatever it is called), we're not going to be able to use the word "vm" as the variable name.  

I think that is going to be a serious problem. Or am I missing something?

**Comment by jvandemo** [comment]
@wardbell &mdash; Agree, PR #401 should fix this (and is conform to how Angular 2 works).

Thanks to @reflexdemon for linking this issue with the PR.

**Comment by reflexdemon** [comment]
Was reading some blogs on Todd Motto website and found this really good.
[A better way to $scope, angular.extend, no more “vm = this”](http://toddmotto.com/a-better-way-to-scope-angular-extend-no-more-vm-this/). I think that what I was kind of looking for when I initially started moving from [Backbone.JS](http://backbonejs.org/) to [Angular.JS](https://angularjs.org/).

@johnpapa this might have answers for the questions on this topic.

**Comment by johnpapa** [comment]
I don't think we are going to solve this here, nor should we, for Angular 1.x. Good discussion though.

Naming of the vm is entirely up the user. There are many discussions in the guide about this, and my experience has lead me convincingly to start with `vm` and go more explicit only when the need arises. 

This guide is about what is available and a good style for code you write today. What is coming is still evolving, and when that comes, it will take time to determine the right style. When that happens, I'l revisit this topic.

Closing.

**Comment by jvandemo** [comment]
@johnpapa &mdash; Good call! :+1:
