### ISSUE TITLE
in the section 'controllerAs with vm' not so obvious how to make the watch on properties that are defined on this (or the vm)

### ISSUE THREAD

**Issue by kobrigo** [johnpapa/angular-styleguide#310]
In order for the watch in the example on style Y032 to work, the controller should be named vm.
For example <div ng-controller='MyController as vm">
This is fragile and confusing. The vm here has nothing to do with the 'var vm = this' that is defined within the closure of the controller function.
the watch within the controller is defendant on how to client (the one that is using the controller) will call it. It would be nicer to free the client to call the controller as he pleases.

The preferred way might be:
$scope.$watch(function(){return this.title;}.bind(this), function(current, original) {
        $log.info('this.title was %s', original);
        $log.info('this.title is now %s', current);
});

With this the client is free to name the controller as he chooses.

**Comment by johnpapa** [comment]
incomplete.
