### ISSUE TITLE
Sublime Text Snippets

### ISSUE THREAD

**Issue by alsfurlan** [johnpapa/angular-styleguide#311]
Hi John Papa,
first congradulações for your work! Excellent, he follow in my work and is very good.

Based on it, I created snippets for Sublime Text you would like to share with you:
https://github.com/alsfurlan/ng-snippets

I thought better than those on the page and I am constantly updating including ngdocs for documentation. 

If you find interesting and want to reference in your page, it would be an honor!

**Comment by Gillespie59** [comment]
Interesting :d 

You can maybe translate your README file into english, in order to help english-speaking people ;)

Manu

**Comment by alsfurlan** [comment]
I translated today :+1:

**Comment by Gillespie59** [comment]
@johnpapa why do you push a ZIP archives ? why not directly the sublime templates ? in order to ease the update directly from Github.

**Comment by johnpapa** [comment]
sounds like a great idea for a Pull Request. hint hint

**Comment by Gillespie59** [comment]
this PR sent.

**Comment by alsfurlan** [comment]
Ok John Papa, I do a Pull request sun! ;). Thanks!

**Comment by johnpapa** [comment]
accepted @Gillespie59 's PR , added bindToController to the directive, and then added a new one for service. thanks

**Comment by alsfurlan** [comment]
@johnpapa Do you said to @Gillespie59  do the pull request or for me?

**Comment by johnpapa** [comment]
They are merged.

But we could use a constant and a value snippet if you want to add those.
