### ISSUE TITLE
German translation on progress?

### ISSUE THREAD

**Issue by devployment** [johnpapa/angular-styleguide#312]
@johnpapa Do you know (or anybody else) if there's an ongoing German translation? Otherwise I'd like to give it try. But don't wan't to start if it's already on progress. :)

**Comment by johnpapa** [comment]
go for it

**Comment by johannes-weber** [comment]
@devployment are you on it? I didn't saw some commits on your fork. What's the state?
I'd like to support with the german translation.

**Comment by devployment** [comment]
@johannes-weber Started translation. But yes. Nothing committed yet. The intro and the the first 3 or 4 styles are done.

I will check this evening and push the current state. Thanks for the nudge.

**Comment by johannes-weber** [comment]
I'll support you.
