### ISSUE TITLE
components directory in Angular 1.4

### ISSUE THREAD

**Issue by shock99** [johnpapa/angular-styleguide#313]
It looks like the new Angular router calls controller/template pairings "components". Your current guide has  a components directory containing directives, how do you see that changing with 1.4?

**Comment by wardbell** [comment]
The[ specific folder that @shock99 is talking about](https://github.com/johnpapa/angular-styleguide/blob/master/README.md#style-y141) perhaps should have been called something else anyway. Maybe "WebControls", "Widgets", "Gadgets" or something that denotes their purpose.

**There is a larger problem: the Angular team has appropriated the word "component"** for a very specific usage. The guide in all other cases uses "*component*" in a generic sense to refer to *anything registered with Angular's IoC*.

Should the guide change that terminology? I looked at [synonyms](http://www.thesaurus.com/browse/components) and couldn't find anything i liked better. I'm really stuck.

At a minimum we might make a note that distinguishes "component" (the everyday word) from "Component", the ng 2.0 specific term.

Thoughts?

**Comment by kylecordes** [comment]
My feeling: a style guide should recommend staying clear of words that have a meaning in the framework. I think most developer already avoid naming their stuff "module", "controllers", etc.

Sadly, I don't have a better name idea to use instead of component, though.

On the plus side, some of the other Angular words are quite easy to avoid, I have never once wanted to name anything in my software "transclude"  :-)

**Comment by dietergeerts** [comment]
This guide is not about Angular 2.0, so I don't see any reason why this should be changed. It's clear that an Angular component before 2.0 is a thing specific to Angular like controller, module, factory, ...

**Comment by johnpapa** [comment]
agreed.

**Comment by breandr** [comment]
@johnpapa so this repo is only for Angular 1.x style guide? Is there a 2.0 style guide available or is it in the works? Thanks for all your work!
