### ISSUE TITLE
[Y080] - Why not use the IIFE pattern for the activate function?

### ISSUE THREAD

**Issue by joneal** [johnpapa/angular-styleguide#318]
Why?  Using an IIFE pattern for activation/initialization makes the function inherently explicit regarding  its purpose, since it will automatically execute.  The name 'activate' then becomes irrelevant, and the  pattern cleans up the explicit function call.

...Or not.

    /* recommended */
    function Avengers(dataservice) {
        var vm = this;
        vm.avengers = [];
        vm.title = 'Avengers';
   
        ////////////

    (function activate() {
        return dataservice.getAvengers().then(function(data) {
            vm.avengers = data;
            return vm.avengers;
        });
    })();
}

**Comment by johnpapa** [comment]
interesting ... but seems like ceremony over just naming it and calling it. IN the new angular there will be conventions for the names of the activate and deactivate events.

**Comment by dietergeerts** [comment]
It will eventually be the same, but I find it personally more clearer to explicitly call the activate function as the last part of the controller setup. All other things beneath that will be functions. You can read much faster through your controllers as you will know not to look lower if you just want to know what's on your controller.
