### ISSUE TITLE
How to avoid confusion when certain IT terms and business terms/features overlap?

### ISSUE THREAD

**Issue by g00glen00b** [johnpapa/angular-styleguide#326]
I'm working at a project for a company that sells services to other companies. I'm talking about inspection, cleaning, transport, ... .
Now the plan is to develop an application that gives an overview of these services. Services can also be grouped in modules, which in turn can be grouped into catalogues.

So, if I was going to follow the same principles here, I would structure the application like this:

 - components
 - services
  - services.controller.js
  - services.controller.less
  - new-service.controller.js
  - new-service.controller.less
  - service-detail.controller.js
  - service-detail.controller.less
 - modules
  - modules.controller.js
  - modules.controller.less
 - catalogues
  - catalogues.controller.js
  - catalogues.controller.less

The problem is, that when I would like to define some services (as AngularJS service) for retrieving catalogues/modules/services, it's obviously going to become really confusing.

How would you approach certain situations? Currently I thought that, because the company is selling those services/modules/catalogues to other companies, I would name it like this:

  - components
  - service-sales (everything about the feature "services")
  - module-sales
  - catalogue-sales
  - services (AngularJS services)

Are there common practices to follow when having certain issues?

Also, how should I name my modules in this case? I was thinking about:

 - app.components
 - app.sales.services (service feature)
 - app.sales.modules
 - app.sales.catalogues
 - app.services (AngularJS service)

**Comment by dietergeerts** [comment]
You can also use a prefix to have less confusion like samodules or smodules or ..... If I see app.sales.modules, is that a grouping of angular modules?

**Comment by johnpapa** [comment]
Naming is tough ... no silver bullet here, but its not a style guide concern in this specific case :)

Me ... I'd pick something that makes sense and run with it.
