### ISSUE TITLE
Gudeline for name Services

### ISSUE THREAD

**Issue by Gillespie59** [johnpapa/angular-styleguide#328]
Hi 

For the moment, we have guideline for the name of controllers. A controller should start with an upper case, and finish with 'Controller'.

Do we have guideline for services? Should we suffix them with 'Service' ? or dependending of the method we use ('Provider' for the method provider, Factory for factory... ) ?

What about  run and config functions ? (app.run() and app.config() ? 

The question does not arise for filters/directives. 

Manu

**Comment by johnpapa** [comment]
Services vary. For example a common name for a data service is `dataservice`. Would that be `dataserviceService` or `dataService` ?  I prefer `dataservice`. Does it matter? Not so much.

Then there is `logger` ... is that `loggerService` or `logger` ? I prefer the latter.

My style is to define a noun that describe the action the service provides.

- `dataservice`
- `logger`
- `exceptionHandler`

I think it really depends on what words make sense, so for me the style is to use whatever conveys the message and for that reason i do not list a specific style

**Comment by Gillespie59** [comment]
Perfect for me. So I disable the corresponding rule in the eslint plugin. If developers want, it will always be possible to enable it, and specify a regexp pattern (like for controllers).

You can close this ticket.

**Comment by websirnik** [comment]
If I have multiple resources that needs to interact with the API, I would name corresponding services: `postDataservice` & `userDataservice`, right?

**Comment by ruionwriting** [comment]
@johnpapa I feel the same as @websirnik about services in different files per context (aggregated root). Would be great to have this - or something similar - on the style guide as well.
