### ISSUE TITLE
Using $ in service/factory names

### ISSUE THREAD

**Issue by jbalboni** [johnpapa/angular-styleguide#335]
Where I work we avoid prefixing services with `$` to avoid collisions with Angular's built-in services. I've seen this mentioned by other developers ([one example](http://stackoverflow.com/questions/15748734/angular-js-naming-conventions-camelcase-and-camelcase)). I also rarely see Angular code from other people that uses `$` as a prefix, with the exception of some third-party libraries (e.g. the Angular UI project).

I don't see an opinion about this in the guide. Is that something worth adding? Or is this a less widely followed convention than I think?

Apologies if this has already been discussed, I couldn't find a issue for it.

**Comment by johnpapa** [comment]
we can add that.

**Comment by johnpapa** [comment]
closed by #337
