### ISSUE TITLE
Emacs snippets

### ISSUE THREAD

**Issue by johnpapa** [johnpapa/angular-styleguide#336]
This PR was close to having emacs snippets for the guide. It needs to be moved to its own folder under `/assets/emacs` and update to be consistent with the guide and the other snippets.

If anyone is up for this, please make a PR.

https://github.com/johnpapa/angular-styleguide/pull/159

**Comment by gfauchart** [comment]
I updated #159 to reflect sublime snippets

**Comment by johnpapa** [comment]
anyone want to make a PR?

**Comment by johnpapa** [comment]
closing as we have new sublime ones coming here https://github.com/johnpapa/angular-styleguide/pull/544
