### ISSUE TITLE
function name casing

### ISSUE THREAD

**Issue by samsur** [johnpapa/angular-styleguide#342]
I have noticed two different casing styles for functions, both are recommended

Example:
function SomeController() { }
function someFactory() { }

In the .Net world, method names use the pascal casing, which means, the first one would be a recommended srtle.  Could you please tell me, which casing style is recommended for javascript and why do we have 2 different styles here.

Thanks
Sam

**Comment by gustavohenke** [comment]
The first one is likely because controllers are instantiated, they behave just like classes, while services are not.

**Comment by dietergeerts** [comment]
JavaScript is more like the Java world where only classes have PascalCasing as they are instantiated. All the rest uses camelCasing. I know it strange at first, I also came from .net before.

**Comment by samsur** [comment]
Thank you gustavohenke and dietergeerts for letting me know why the difference exists.

**Comment by gkalpak** [comment]
> _controllers are instantiated [...] while services are not_

Just a little correction:
There is this notorious _provider vs factory vs service_ ambiguity in Angular. The function passed to `.factory()` is not instantiated (it is "invoked"), whereas the functions passed to `.provider()`* and `.service()` are in fact instantiated. (All the above will result in a Service being registered.)

That's why you might see the following casing:

```js
angular.module('...').
  provider('Foo', FooProviderFn).    // Uppercase, because `FooProviderFn` is instantiated
  provider('Bar', barProviderObj).   // Lowercase, because `barProviderObj` is an object
  service('Baz', BazServiceFn).      // Uppercase, because `BazServiceFn` is instantiated
  factory('Qux', quxFactoryFn);      // Lowercase, because `quxFactoryFn` is invoked
```
--
<sub>*: Note that the provider can also be an object with a `$get()` function property.</sub>

**Comment by gustavohenke** [comment]
Wow. Thank you @gkalpak for teaching me something today. Didn't know I was able to not define `$get()` in a provider.

**Comment by samsur** [comment]
@gkalpak  +1 for the detailed explanation

**Comment by gkalpak** [comment]
Just to be clear, `$get()` must always exist; but the provider can be either an object or . constructor function (creating a provider instance with a `$get()` method):

```js
// Provider as an object
.provider('Foo', {
  ...
  $get: function () {...}
});

// Provider as a constructor
.provider('Bar', function () {
  ...
  this.$get = function () {...};
});
```

**Comment by johnpapa** [comment]
i thnk we're set here now, right?

**Comment by samsur** [comment]
closing this for now. Thanks for the answers
