### ISSUE TITLE
How to add manually many deps

### ISSUE THREAD

**Issue by albertosantini** [johnpapa/angular-styleguide#343]
About Y091 [Manually Identify Dependencies](https://github.com/johnpapa/angular-styleguide#style-y091), for instance,  we have the following approach:

```
Dashboard.$inject = ['$location', '$routeParams', 'common', 'dataservice'];
function Dashboard($location, $routeParams, common, dataservice) {
}
```

If you have many deps, the indentation might be nasty. 
`ng-annotate` mitigates the issue, removing the need of $inject array; anyway the function params are there.

What about a `require` approach (inspired by [Angular Basics](http://www.angularjsbook.com/angular-basics/chapters/dependency-injection/))?
```
Dashboard.$inject = ["$injector"];
function Dashboard($injector) {
        var $location= $injector.get("$location"),
              $routeParams= $injector.get("$routeParams"),
              common= $injector.get("common"),
              dataservice= $injector.get("dataservice");
```

P.S.: http://plnkr.co/edit/zuGyRL2C7T33XVyGRdkq?p=preview

**Comment by johnpapa** [comment]
Yes you can do it manually. Its like the difference between ctor injection and property injection. ctor injection is easier to do right (so you don;t miss one) and more pervasive.

The readability you may gain by going line by line is also possible with ctor like this:

```
Dashboard.$inject = ['$location', '$routeParams', 'common', 'dataservice'];
function Dashboard( 
    $location, 
    $routeParams, 
    common, 
    dataservice) {
}
```
