### ISSUE TITLE
About computed properties

### ISSUE THREAD

**Issue by albertosantini** [johnpapa/angular-styleguide#346]
I think we may add an example about computed properties in the section Y035 [Defer Controller Logic to Services](https://github.com/johnpapa/angular-styleguide#style-y035)

For instance,

```
    /* avoid */

    // account.js
    function Account(accountService) {
        var vm = this;

        vm.account = accountService.getAccount();
        vm.unrealizedPlPerc = unrealizedPlPerc;
        vm.netAssetValue = netAssetValue;

        function unrealizedPlPerc() {
            return vm.account.unrealizedPl / vm.account.balance * 100;
        }

        function netAssetValue() {
            return vm.account.balance + vm.account.unrealizedPl;
        }
    }
```

```
    /* recommended */

    // account.js
    function Account(accountService) {
        var vm = this;

        vm.account = accountService.getAccount();
    }

   // accountService.js
   function getAccount() {
       return $http.get('/api/account')
            .then(function (response) {
                account = response.data;

                account.unrealizedPlPerc = account.unrealizedPl / account.balance * 100;
                account.netAssetValue = account.balance + account.unrealizedPl;
       });
   }
```

The point is to avoid `accountService.getAccount().then(...);` in the controller for the computed properties. The controller would be very slim.

What do you think?

**Comment by mustela** [comment]
@albertosantini I think its important to return a promise from a service, otherwise you could be dealing with null values.

**Comment by johnpapa** [comment]
This has nothing to do with computed properties but everything to do with using promises from a service/factory which is already in the guide. Also, this leans more to understanding promises and js, which is a perfectly fine question, but not an angular style so much how js and promises work.
