### ISSUE TITLE
Avoid IIFE in favor of a scope object

### ISSUE THREAD

**Issue by brauliobo** [johnpapa/angular-styleguide#347]
IIFE increase code identation and is used just to not polute the global scope.

Suggestion: keep one global context object. For example:

Definition come first:
```javascript
app = {
  controllers: {},
  factories: {},
  services: {},
  directives: {},
  filters: {},
  settings: {},
};
```
Then (based on Y010):
```javascript
angular
  .module('app')
  .factory('storage', app.factories.storage);

app.factories.storage = function () { }
```

This may also match directory structure, e.g, `app.factories.storage` defined on `app/factories/storage.js`.

What do you think?

**Comment by wardbell** [comment]
I'm an IIFE fan. I don't indent for the IIFE, btw, because it's an idiom and I use vertical white-space instead. My IIFE contents are flush left. Whatever.

**Comment by FrancescoRizzi** [comment]
without IIFE you are not protected from further polluting the global scope... sure, as long as you are well behaved and add everything to your global app object, you're ok, but IIFE means you don't have to worry about it (once you're within the IIFE block of course)..
I don't love the IIFE block (sort of wish that we had some shortcut statement in its stead), but I'd rather have it there, if that makes sense?

**Comment by wardbell** [comment]
Good point, @FrancescoRizzi !  FWIW it is completely unnecessary in node (which injects it for you) and I think maybe TypeScript tooling also generates the IIFE.

**Comment by kylecordes** [comment]
I usually recommend the following practice: set up your build process to wrap each file in a IIFE while concatenating. But there is also a good argument for putting it manually in every file. Regarding Ward's comment about indentation though, so far I have not noticed any of the automatic formatting tools in IDEs able to disregard the indentation implied by the IIFE - so to get what Ward describes, you are manually managing indentation. Not awful, but arguably there are much better uses of your time.

**Comment by johnpapa** [comment]
I don;t see any reason to spend time worrying about the IIFE. It does its job and is pretty simple to stuff out of the way especially with tooling. It's also extremely common.

**Comment by brauliobo** [comment]
@kylecordes Besides replacing IIFE, I like your suggestion of using a build process. As I am pretty new to angular, could you tell me how to do that?

**Comment by johnpapa** [comment]
There are gulp and grunt plugins that can wrap with an IFFE.

And if you use ES6, you dont need one.

**Comment by brauliobo** [comment]
@johnpapa thanks, could find it at http://stackoverflow.com/questions/25508427/use-gulp-to-wrap-javascript-files-with-a-iife

**Comment by kylecordes** [comment]
Starting new today? Use ES6.  Old project where you want to wrap in IIFEs etc.? See link above.

**Comment by brauliobo** [comment]
@kylecordes I'm considering it more and more :) @viniciuscb
The best docs I found at http://www.michaelbromley.co.uk/blog/350/exploring-es6-classes-in-angularjs-1-x . Please give some reference on it.
