### ISSUE TITLE
Application structure for apps with mobile and desktop specific views?

### ISSUE THREAD

**Issue by cquillen2003** [johnpapa/angular-styleguide#348]
I find it optimal to create separate views for mobile and desktop screens in most cases, rather than rely on responsive design alone.  What is the recommended way to accomplish and organize this in Angular?

I create separate index-desktop.html, index-mobile.html, routes-desktop.js, and routes-mobile.js files to accomplish this and so that I can include fewer assets, libraries, etc. on the mobile version.  I use the user agent to automatically load the appropriate index.html file, but also include desktop and mobile links in the footer to give the user the option to switch.  Does this sound reasonable and are there any conventions coming for this?

**Comment by dietergeerts** [comment]
Very interesting topic as like you said responsive design isn't always good enough for this.

**Comment by cquillen2003** [comment]
app/

    layout/
        shell.mobile.html
        shell.desktop.html
        shell.controller.js
        topnav.mobile.html
        topnav.desktop.html
        topnav.controller.js
    people/
        attendees.html
        attendees.controller.js
        people.routes.js
        speakers.html
        speakers.controller.js
        speaker-detail.html
        speaker-detail.controller.js

**Comment by johnpapa** [comment]
interesting idea. i think it depends tho. i cringe at 2 mobile views for some apps, as the views may be simpler with responsive design. while others may be entirely different views. but then, when te views are so different I often see different controllers too with different models. For these cases you can argue its better to have a mobile module and a desktop module so you dont include more than you need in the app.

Ultimately it is not very cut and dry and there are a few ways to skin this.

**Comment by wardbell** [comment]
Agree, not cut and dry.

My instinct is that mobile and desktop are radically different not just in form factor (the point of responsive design) but in usage scenarios (the point of UX design). 

That instinct drives me toward separate modules with their own views and controllers/viewmodels. That assumes you have the time and budget to think that through and maintain it plus a plan for isolating the business logic that should be shared in yet another place. 

That's a serious undertaking! Even if it is the "right way", few can afford it or justify it from a business perspective.

Which may lead you to a hybrid approach with just the most critically different views handled in separate modules.

"Not cut and dry" indeed!

**Comment by cquillen2003** [comment]
Serious undertaking indeed!  And certainly not cut and dry.  To be clear, I definitely do not want to use a pattern that requires separate mobile and desktop views for each feature/screen.  In my experience, responsive design is better in many cases, but not all.

At this point, I would just like to see how other people have tackled this problem.

I recently started refactoring my angular-seed (and old style guide) patterned app to this style guide's application structure.  Much better so far!  On that note, thank you all for your work on this style guide!

Here is what I'm doing so far:

My requirements:
1. Option to load different assets (and cache manifests) for mobile and desktop
2. Option to use different templates (as required) for mobile and desktop
3. Option to use different controllers/view-models (as required) for mobile and desktop
4. Detect user agent and send appropriate version
5. Give user the option to use mobile or desktop version regardless of the user agent

App structure:
app/
    app-mobile.module.js
    app-desktop.module.js
    index-mobile.html   //App server detects user agent and loads appropriate index.html
    index-desktop.html
    components/
    layout/
        nav-mobile.controller.js   //Separate controllers and templates in this case
        nav-mobile.html
        nav-desktop.controller.js
        nav-desktop.html
    users/
        users.routes.js
        user-login.js
        user-login.html
    customers/
        customers-mobile.routes.js
        customers-desktop.routes.js
        customers.controller.js   //Shared controller, separate templates in this case
        customers-mobile.html
        customers-desktop.html

**Comment by wardbell** [comment]
Do you handle with dynamic routing on the server? Can the client request `~/customers/customers.routes.js` and have the server will redirect to either `~/customers/customers-desktop.routes.js` or `~/customers/customers-mobile.routes.js`? 

That would be ideal. It would simplify client-side development remarkably.

**Comment by cquillen2003** [comment]
Interesting, do you mean always referencing ~/customers/customers.routes.js in the index.html file, but the server sending the appropriate one depending on user agent?  Like so:

//index.html
<script src='customers/customers.routes.js"></script>  //App server sends appropriate one

Right now I have separate index.html files as seen below and serve the correct one based on user agent detection.

//index-mobile.html
<script src='customers/customers-mobile.routes.js"></script>

//index-desktop.html
<script src='customers/customers-desktop.routes.js"></script>

**Comment by wardbell** [comment]
Yup. That's what I meant. You could potentially get by w/ a single index.html and let your server-side routing do the job. I'm assuming you have the appropriate configuration options on your server. Don't know what your tech is.

**Comment by johnpapa** [comment]
You could use Jade (or razr for .net) on the server to write the index.html file's url's.

You could use express routing to serve the appropriate file.

Lots of options ... interesting thought.

**Comment by johnpapa** [comment]
closing since this wont go in the style guide, but is a good topic for discussion :)

**Comment by aneeskodappana** [comment]
any recommendations for angular 8 on mobile and desktop specific views, 
specifically on when using server-side rendering
