### ISSUE TITLE
Avoiding IIFE without polluting the global scope

### ISSUE THREAD

**Issue by Swiip** [johnpapa/angular-styleguide#350]
Yet another thread about IIFE sorry. But it's really painful to write in each file right?

My own guideline for Angular doesn't use IIFE and still don't pollute the global scope, I wanted to know what do you think about that.

Replacing: 
```javascript
(function() {
    'use strict';

    angular
        .module('app')
        .factory('logger', logger);

    function logger() { }
})();
```
By:
```javascript
'use strict';

angular
    .module('app')
    .factory('logger', function logger() { });
```

There is no global variable created, the function has a name in case of error. To be honest, I don't see an argument for IIFE which is not answered by this syntax too.

**Comment by Markionium** [comment]
If i am not mistaken, when you concatenate the files with other code that does not use strict mode you'll enable strict mode for any code that comes after the `'use strict';` statement. 

If that is not the case and you can be sure no one will use your code and concatenate it with other code then you should be fine to do it like that.

**Comment by kylecordes** [comment]
Some concatenation processes wrap each file in an IIFE to be safe from this particular risk.

However, many people just ignore it. Whether it matters depends on whether you have any (probably rather old) code laying around that does not work with use strict.

**Comment by johnpapa** [comment]
related to https://github.com/johnpapa/angular-styleguide/issues/347

**Comment by johnpapa** [comment]
This would help remove that function, but not any others inside an IFFE. If you only have the one, then you just have the angular variable.

Use IIFE, use something else, use a grunt/gulp process to add them ... I just dont find that IIFE takes any additional time for me and has never bothered me. I realize some folks prefer it to go away but if you want that, personally I'd like to TypeScript or ES6.

I'm closing this as an issue, as it's not a problem. Its a choice.
