### ISSUE TITLE
Browserify as part of task automation

### ISSUE THREAD

**Issue by MarcCloud** [johnpapa/angular-styleguide#362]
Hi, 

I really liked this guide and I have been implementing these concepts on my job and personal projects.

Recently added Browserify to my automation stack of tools and it has been really useful. I think it could be worthy to add it's usage to this guide.

I created a seed project that has everything tied up to start working in this form.
https://github.com/MarcCloud/angularify-seed

**Comment by johnpapa** [comment]
appreciate it, but i dont think browserify is an appropriate add to the guide

**Comment by voor** [comment]
You're not implementing Browserify in such a way that each module can be independently testing, either.  You'd want to do something so that each js file could still stand alone as its own angular module.

**Comment by MarcCloud** [comment]
Voor Thanks for the advice. I'll try to add this to the next version.

**Comment by voor** [comment]
@MarcCloud We're actually using Browserify and Angular together in our current project.  It's not open source, so I apologize for the train-wreck of an example but here's how we're doing it:
https://gist.github.com/voor/c6aa0f32a3aa0abda47b
