### ISSUE TITLE
[Y052] Variable assignment

### ISSUE THREAD

**Issue by Nupf** [johnpapa/angular-styleguide#364]
I'm new to js so maybe this is obvious:

```javascript
function dataService() {
  var someValue = '';
  var service = {
    save: save,
    someValue: someValue
  };
  return service;

  ////////////

  function save() {
    // this does not change the returned someValue
    someValue = 42;
    // this does
    this.someValue = 42;
  };
}
```
As someValue was defined outside the service object it seemed to me that changes should also be done to the same variable. Maybe it would help other beginners to change the example to
```javascript
  function save() {
    this.someValue = 42;
  };
```

**Comment by johnpapa** [comment]
`this.someValue` on the function creates a property on the resulting object from when you call `new save()`. In other words, you are defining a property on the constructor of the `save` object

**Comment by Nupf** [comment]
Thanks for taking the time to reply.
As I understand it, the problem does, however, persist. service.save() does not change service.someValue if it is written like this:
```javascript
  function save() {
    someValue = 42;
  };
```
It would need to be written like this: 
```javascript
  function save() {
    // explicitly show that service.someValue and not someValue have to be modified
    service.someValue = 42;
  };
```

```javascript
  var service = {
    save: save,
    // this only assigns the current value of someValue to service.someValue.
    // Further changes to someValue will not be reflected here
    someValue: someValue
  };
```

Then again, this is normal js behavior (http://stackoverflow.com/questions/10231868/pointers-in-javascript) and I merely added this as a suggestion as no angular tutorial I've found mentioned this.
