### ISSUE TITLE
Activate() Small Issue

### ISSUE THREAD

**Issue by daw451-duplicate** [johnpapa/angular-styleguide#366]
John if i have the following code:

    function MessageController(messageDataService, $stateParams) {
        var message = this;
        message.data = null;

        activate();

        function activate() {
            message.getmessage();
        };

        message.getmessage = function () {
            messageDataService.getMessageWithDetail( $stateParams.messageGuid ).then(function (result) {
               ...
                }
            });
        };
    };

So if i run the following code i actually get an error stating:

Object doesn't support property or method 'getmessage'

I could follow your recommendation and change it to this:

         function getmessage () {
            messageDataService.getMessageWithDetail( $stateParams.messageGuid ).then(function (result) {
               ...
                }
            });

 but i wanted to have a spyOn for the getmessage function. This function contains jQuery actions that i do not want to test. 

I would still like to use the activate() approach... basically a hoisting issue... I guess just place the activate at the bottom - i hate that!!!

**Comment by johnpapa** [comment]
```
function MessageController(messageDataService, $stateParams) {
    var message = this;
    message.data = null;
    message.getmessage = getmessage; // put this here

    activate();

    function activate() {
        getmessage(); // call the local one
    };

    function getmessage () {
        messageDataService.getMessageWithDetail( $stateParams.messageGuid ).then(function (result) {
           ...
            }
        });
    };
};
```

**Comment by daw451-duplicate** [comment]
ah of course thanks!!!

**Comment by johnpapa** [comment]
I dont spy on private function but instead test the behavior they perform
