### ISSUE TITLE
Y420 Filters

### ISSUE THREAD

**Issue by GaryB432** [johnpapa/angular-styleguide#368]
The style says 

> Avoid using filters for scanning all properties of a complex object graph. Use filters for select properties.

Can some more information be given maybe such as a sample code block to be "avoided"?  The [angular phonecat documentation](https://docs.angularjs.org/tutorial/step_09) discusses the checkmark filter but I don't understand about the "complex object graph" and selecting all properties versus just some.  Is this regarding `$stateful` filters?

If someone could explain that here I'd be happy to make a PR with clarification and examples. 

Thanks for this resource!

**Comment by johnpapa** [comment]
If you use the `filter` filter on an object that has an array of customers, which has 10 properties including an array of orders, which has 10 properties including an array of products and sales people, and so on ... basically a large object graph, the filter will evaluate everything by default. This causes an unneeded strain on the digest cycle.

It is best to use filters on smaller sets of data or to reduce which specific properties it should look at.

Or use a javascript function to filter.

**Comment by GaryB432** [comment]
Ahh I see. Thanks for the clarification.
