### ISSUE TITLE
Generator that is built with this style guide

### ISSUE THREAD

**Issue by reflexdemon** [johnpapa/angular-styleguide#369]
Hey,

I was so much impressed with your style guide and planning to mandate this culture among our team who are just about to begin an angular projects. So I have created a generated based upon the feedback provided on this style guide and published in NPM. As more people are moving towards gulp this has become a slush generator. Please review the same and please provide your feedback if you have time.

Many thanks in advance.

[slush-angular-gulp](https://www.npmjs.com/package/slush-angular-gulp)

**Comment by voor** [comment]
See related #380

**Comment by johnpapa** [comment]
interesting.

i made https://github.com/johnpapa/generator-hottowel a while back too.
