### ISSUE TITLE
Application Structure - Shared Directives

### ISSUE THREAD

**Issue by ralberts** [johnpapa/angular-styleguide#371]
I apologize if this has already been asked and answered.  

I am curious in the application structure layout where directives would be placed that are shared across components and features.

Would the recommendation be to add a common/ folder to place these pieces of shared code?

Thanks for the advice!

**Comment by voor** [comment]
I'd like to build upon this with an additional question.  We had something that resided in a module, and then it became more commonly used.  Do you refactor at this point, or leave it in the original module?

**Comment by johnpapa** [comment]
@ralberts I'd create a reusable set of widgets in a module. Like a component library.

@voor Yes, I would refactor once I know a thing can be reused.
