### ISSUE TITLE
Naming convention for partial templates

### ISSUE THREAD

**Issue by AsifMushtaq** [johnpapa/angular-styleguide#372]
I was looking for some sort of naming convention for partial templates. Some times an html template become so big that it needs to be decomposed in partial templates (as some times creating a directive does seems to be a feasible option).

One possible way can be to create a folder named 'partials' inside a module folder and put all the partial templates inside it. The only drawback of this approach seems to be a more deeper hierarchical structure. 

```javascript

    app/
       ...
       ...
       ...
        people/
            partials/
                registration.personal-details.html
                registration.emergency-contact.html
                registration.payment-details.html
            registration.html
            registration.controller.js
            attendees.html
            attendees.controller.js
            people.routes.js
            speakers.html
            speakers.controller.js
            speaker-detail.html
            speaker-detail.controller.js
        ...
        ...
```

Second option is to have partial templates inside the module folder, at the same level of its parent template, the drawback of this approach would be a crowded folder. 

```javascript

    app/
       ...
       ...
       ...
        people/
            registration.personal-details.html
            registration.emergency-contact.html
            registration.payment-details.html
            registration.html
            registration.controller.js
            attendees.html
            attendees.controller.js
            people.routes.js
            speakers.html
            speakers.controller.js
            speaker-detail.html
            speaker-detail.controller.js
        ...
        ...
 ```
Third option is to have separate folder all together for the template along with partial templates.

```javascript

    app/
       ...
       ...
       ...
        people/
            registration/
                registration.personal-details.html
                registration.emergency-contact.html
                registration.payment-details.html
                registration.html
                registration.controller.js
            attendees.html
            attendees.controller.js
            people.routes.js
            speakers.html
            speakers.controller.js
            speaker-detail.html
            speaker-detail.controller.js
        ...
        ...
 ```

What is your opinion about this?

Thanks

**Comment by johnpapa** [comment]
Option 1 ... I would not do a partials folder. Personal preference here, but it doesnt describe whats happening. Especially when you start to add multiple partials from different parts of the feature module.

Option 2 ... This is fine, if you just want to break it out. Kinda assumes ng-include or something similar though.

Option 3 ... Interesting idea. Though I would go one step further and make it a module of its own. The people module could depend on it.

Option 4 ... Make the areas directives or nested views (using ui-view with ui-router). 

I'd go with 3 if you truly want to keep all this separate. 4 if you just need to break it out.

**Comment by AsifMushtaq** [comment]
Thanks John.

Option 4 seams to be interesting. 

According to the style guideline the directives goes into the components folder which is at the root level, it makes sense for reusable directives (across the application), but what would be the best place to put directives which are only being used by a specific module, Lets say the registration in the above case.

**Comment by ruionwriting** [comment]
@AsifMushtaq I'm really interest on this also because I've found similar needs.

**Comment by johnpapa** [comment]
closing since i think we covered it here

**Comment by AsifMushtaq** [comment]
Agree I think you have covered the topic completely.
Thanks @johnpapa,
