### ISSUE TITLE
$compile in controller

### ISSUE THREAD

**Issue by simkepal** [johnpapa/angular-styleguide#373]
Hello,

I try to use guides for angular development. I have a question about controllers using controller as vm. I need to add part of template dynamicaly and till now i did this with $compile function. But without scope in controller this is not possible. Can you help me with this issue, please....

Thank you!!

**Comment by Markionium** [comment]
Can you give a bit more elaborate example? 

Form what you wrote it sounds to me like what you want is some sort of a directive. As that would be where your custom templating could go. As manipulating DOM in a controller is generally bad practice.

**Comment by simkepal** [comment]
Yes, i can tell you more about this. I use ui-select directive for creating selects. And based on first select I need to create another select with new items. And again based on second select I need to add third select with another Items. What would be the best solution for this? Bellow is my current function in controller. Thank you for help and quick response.

function addCategorySelect() {
			var hasChildren = findCategoryChildren();

			if(vm.item.categories && hasChildren) {
				var html = '<div class="category category-' + vm.categoryDepth + '" data-index="' + vm.categoryDepth + '">' +
					'	<div class="form-group">' +
					'		<ui-select ng-model="item.categories[' + vm.categoryDepth + ']" theme="bootstrap" on-select="categorySelect(' + vm.categoryDepth + ');">' +
					'			<ui-select-match placeholder="Izberi podkategorijo...">' +
					'				{{ $select.selected.category }}' +
					'			</ui-select-match>' +
					'			<ui-select-choices ' +
					'			repeat="c.id as c in categories | filter: {parent: ' + parseInt(vm.item.categories[vm.categoryDepth-1]) + '} | filter: {depth: ' + vm.categoryDepth + '}">' +
					'				<div ng-bind-html="c.category | highlight: $select.search"></div>' +
					'			</ui-select-choices>' +
					'		</ui-select>' +
					'	</div>' +
					'</div>';
				el = $compile(html)($scope);
				// return;
				angular.element(".categories").append( el );
			}
		}

**Comment by Markionium** [comment]
Have a look at the following. This might give you an idea. http://jsfiddle.net/qdg8tLsq/

It obviously won't be exactly what you need but you can work from there.

**Comment by johnpapa** [comment]
thanks guys ... closing as a non style question.
