### ISSUE TITLE
Feedback and update for next-generation

### ISSUE THREAD

**Issue by olanod** [johnpapa/angular-styleguide#382]
Hello @johnpapa, I like your style-guide which is what I've been using in my last projects. But now that I've stared to move to ES6 so it would be nice to have an established guide for people which is based on the new syntax.  
I just created an [example app](https://github.com/olanod/bookstore-example-ng1) and a [helper library](https://github.com/olanod/angular-migrate) for angular1 projects to serve as a guide for the future migrations, if you can have a look and give me some feedback it'd be great so in a near future a solid style-guide can be created.

**Comment by AsifMushtaq** [comment]
@olanod I think your example app link is linked is referencing the same issue.

**Comment by olanod** [comment]
ups sorry, edited and fixed.

**Comment by johnpapa** [comment]
thanks. not sure there is any action to take here at this time. if you have suggestions, always open to a PR
