### ISSUE TITLE
Y152 - Grouping components by feature

### ISSUE THREAD

**Issue by g00glen00b** [johnpapa/angular-styleguide#383]
As the example application structure (Y152) there is a folder called components/ containing a calendar and a user-profile.
I'm also noticing a feature area for people (people/ folder). Wouldn't it make more sense to put the user-profile component inside the people feature area?

I know these rules aren't written in stone, but is there any advantage of using one strategy over another?

**Comment by gustavohenke** [comment]
I think the `components/`  directory is supposed to hold stuff that is re-usable across all feature areas.

For example, the `people` feature could be a CRUD for people, but you're likely to show the author of a post (another feature of your app) using the `userProfile` directive.

**Comment by g00glen00b** [comment]
Ok, makes sense. So, but if you write a component that's related only to a specific feature (for example people), it would be a good idea to add it to the same folder, right?

**Comment by cerdman** [comment]
I was confused on this and found the explanation that @gustavohenke gave to be helpful. I think this should be clearly explained in the guide along with examples to show the important of "cross cutting" concerns.

**Comment by gustavohenke** [comment]
> Ok, makes sense. So, but if you write a component that's related only to a specific feature (for example people), it would be a good idea to add it to the same folder, right?

If you are only going to use it within that feature, then I think that's fine.

**Comment by johnpapa** [comment]
``` javascript
if (component.isRelatedTo(feature)) {
    component.livesIn(feature);
} else {
    component.liveIn(appLevelComponentFolder);
}
```
