### ISSUE TITLE
Angular2 Question: Canonical vs Short binding syntax

### ISSUE THREAD

**Issue by joshkurz** [johnpapa/angular-styleguide#384]
Any thoughts, on the difference between the two template binding syntaxes. 

Canonical:
`<element bind-title="name"><element>`
Short:
`<element [title]="name"><element>`
or you can also do `{{}}`, which now only evaluate expressions
`<element title="{{name}}"><element>`

Then there is the syntax for event bindings, which use `(some-event)` or `on-some-event`, that only evaluate statements.

All in all just wondering if there should be some best practices around these syntaxes or if its just a do what feels right type of thing. I currently like using canonical and the `{{}}` expression bindings.

**Comment by johnpapa** [comment]
I like the shortcut syntaxes with `[   ]` and `(    )`

**Comment by voor** [comment]
The nice part about the bind syntax is you can put a fail-safes inside the element, which can be nice for mocks or design phases.  
````
<h1 data-ng-bind="page.title">Page Title</h1>
````
vs
````
<h1>{{ page.title }}</h1>
````
Obviously less code, but depending on your group composition the person designing HTML doesn't need to know that `page.title` contains the page's title.

**Comment by johnpapa** [comment]
yes. but if you have binding failures, you have bigger problems :)
