### ISSUE TITLE
controllerAs with vm, and `this`

### ISSUE THREAD

**Issue by SanderElias** [johnpapa/angular-styleguide#385]
see [this section](https://github.com/johnpapa/angular-styleguide#style-y032)

I wonder what the reason is behind to advise `var vm = this;` opposed  to `var vm = {} ... return vm;`

In the JS community there is a lot of use of `this` without an apparent reason. A lot of issues disappear when you don't use it. (ask Crockford if you don't believe me ;))  Usually when a controller is defined with ngController, `this` will be an empty object anyhow. If we need something, we use the injector and inject it. 
For directive controllers with `bindToController:true` the isolate scope is attached to `this` but that always felt wrong to me. It should be injected along with other dependencies. In most other cases this is also bound to an empty object. 

EDIT: there is an actionable issue here. [this section](https://github.com/johnpapa/angular-styleguide#style-y032) should be adapted to promoting `var vm = {};...return vm;`

**Comment by johnpapa** [comment]
When using controllerAs, `this` is what gets bound to the View.

**Comment by SanderElias** [comment]
@johnpapa My [demo plunk](http://plnkr.co/edit/Q3SnD3JzDPVAZu7Vveg2?p=preview) shows, that whatever is returned gets bound to the view. This is a subtle yet important difference.

**Comment by johnpapa** [comment]
And then you are also replacing the way constructor objects work in JavaScript. The Controller gets instantiated and `this` is the instance that is returned, so you'd be replacing that.

controllerAs is syntactic sugar over $scope. Simply replacing it with { } is not going to add any value.

**Comment by SanderElias** [comment]
John, I read the words, I understand were it is coming from.
However, I seem to fail to understand the added value of using ‘this’ over
an clean object.
When using var vm= {}; it is an small step to var vm = angular.extend({},
someDefaults()). I know I can do the same with ‘this’, but then there is a
change that I overwrite some internals I don’t know off (well, that could
be, there is no way for me knowing looking at that code, right?)

So, my question stay’s. what is the added value of this?

  function someController() {
   var vm = this;
   vm.something = 'someotherthing'
   vm.someFunc = doSomething
   return;
   ///
   function doSomething() {}
   }

over this:

  function someController() {
   var vm = {};
   vm.something = 'someotherthing'
   vm.someFunc = doSomething
   return vm;
   ///
   function doSomething() {}
   }

Good, I need to type a few letters extra, but that can’t be the point?
​

**Comment by SanderElias** [comment]
John, I read the words, I understand were it is coming from.
However, I seem to fail to understand the added value of using ‘this’ over
an clean object.
When using var vm= {}; it is an small step to var vm = angular.extend({},
someDefaults()). I know I can do the same with ‘this’, but then there is a
change that I overwrite some internals I don’t know off (well, that could
be, there is no way for me knowing looking at that code, right?)

So, my question stay’s. what is the added value of this?
```
  function someController() {
   var vm = this;
   vm.something = 'someotherthing'
   vm.someFunc = doSomething
   return;
   ///
   function doSomething() {}
   }
```
over this:
```
  function someController() {
   var vm = {};
   vm.something = 'someotherthing'
   vm.someFunc = doSomething
   return vm;
   ///
   function doSomething() {}
   }
```
Good, I need to type a few letters extra, but that can’t be the point?

**Comment by johnpapa** [comment]
This is the way constructor objects work in JavaScript. You dont need to return anything as `this` is the object you are creating. So you'd be replacing that with your own. I think it is overly clear that `this` is the object as that is how all JavaScript constructors work, and that making a new object and overriding it is not as clear. It's a JavaScript convention.

here is another option 

```
		angular
			.module('app', [])
			.controller('Shell', Shell)
			.controller('Customer', Customer);

		Shell.$inject = ['$scope', 'msgservice'];
		function Shell($scope, msgservice) {
			$scope.vm = this;
			$scope.vm.title = 'shell title';
		}

		Customer.$inject = ['$scope'];
		function Customer($scope) {
			$scope.vm = this; 
			$scope.vm.name = 'customer name';
		}
```

This is what is happening under the covers when you setup controllerAs.

If you go the route you suggest, which I wouldn't, you;d have to make sure all use cases for $scope still work too, such as watches (tho I avoid those, but sometimes they are necessary).

I don't see any value in deviating as its clear what the object is as JavaScript knows `this` is the object. it is also more consistent to where Angular 2 is heading with the class structure and `this` being the object.

Its fun to explore new ideas, and you have an interesting take on it.

**Comment by SanderElias** [comment]
I know it's a JS convention.  I can live with this tough ;) Have been for living with `this` for over 2 decades.
Helping other developers, I found out that for a lot of them this `this` is confusing as <beep>. 
Frankly, I can't blame them. 
I know how ng1 hooks up the controllerAs to the scope. I see no problem there.

In that light. do you really think this is adding confusion:?
```
angular
            .module('app', [])
            .controller('Shell', Shell)
            .controller('Customer', Customer);

        Shell.$inject = ['$scope', 'msgservice'];
        function Shell($scope, msgservice) {
            $scope.vm = {};
            $scope.vm.title = 'shell title';
        }

        Customer.$inject = ['$scope'];
        function Customer($scope) {
            $scope.vm = {}; 
            $scope.vm.name = 'customer name';
        }
```

Or that there will be other issues doing this without this? 

NG2 will be using ES6 classes. Those are just syntactic sugar over what we have already. Both way's of doing this or not this, will still be available. 

And thank you, I try to keep my view fresh. Helping starters is a good way to maintain that.
