### ISSUE TITLE
angular-style in coffeescript?

### ISSUE THREAD

**Issue by kcliu** [johnpapa/angular-styleguide#388]
Since CoffeeScript doesn't support function declaration  (https://github.com/jashkenas/coffeescript/issues/1640) 

how to implement some patterns use function declaration in angular-styleguide?

**Comment by jimlei** [comment]
@kcliu I'd suggest looking into using [ng-classify](https://github.com/CaryLandholt/ng-classify)

It does not adhere to these guidelines perfectly, but the base principle is to keep the code tidy and readable, which I most definitely think is achieved. The big drawback is perhaps using anonymous functions in callbacks, but as you say it simply does not support it.

**Comment by johnpapa** [comment]
when using TS or CS or anything beyond ES5 the syntax and styles may change. At that point you need to adjust. Perhaps you can develop your own offshoot.

**Comment by kcliu** [comment]
@jimlei @johnpapa thanks for the reply
