### ISSUE TITLE
Contants (style-y241) consideration and approach

### ISSUE THREAD

**Issue by ruionwriting** [johnpapa/angular-styleguide#389]
So currently we have this on the guideline:

``` javascript
// Constants used by the entire app
angular
    .module('app.core')
    .constant('moment', moment);

// Constants used only by the sales module
angular
    .module('app.sales')
    .constant('events', {
        ORDER_CREATED: 'event_order_created',
        INVENTORY_DEPLETED: 'event_inventory_depleted'
    });
```

On my case I'll have the need for some additional stuff like that but I would like to have a cleaner, even more, way to represent this kind of constants. Does this sounds good?

``` javascript
// Constants used by the entire app
angular
    .module('app.core')
    .constant('moment', moment);

// Constants used only by the sales module
angular
    .module('app.sales')
    .constant('events', events);

var events = {
    ORDER_CREATED: 'event_order_created',
    INVENTORY_DEPLETED: 'event_inventory_depleted'
};
```

**Comment by johnpapa** [comment]
yep

**Comment by gkalpak** [comment]
Hm...I don't think this would work.

`events` will be `undefined` when calling `constant('events', events)`.
While variable definitions are hoisted in JS, variable initialization isn't.

Your code is equivalent to:

```js
var events;
angular...constant('events', events);   // At this point, `events` is undefined
events = {...};
```

--
In order to keep a clean style, I do this:

```js
angular.
  module(...).
  constant('SOME_CONST', constSomeConst());

function constSomeConst() {
  var SOME_CONST = ...;
  return SOME_CONST;
}
```

**Comment by aciccarello** [comment]
I wonder if you are just returning a POJO, it might make it more confusing to encapsulate that in a function. I think I may have a hard time seeing the usefulness without a specific example.

**Comment by johnpapa** [comment]
either is fine :)

**Comment by gkalpak** [comment]
I am pretty sure I had written an extensive example, but it somehow isn't there !?
<sub>(Anti-gkalpak alien conspiracy stuff, I guess...)</sub>

--
Long story short, this:

```js
angular.
  module('...').
  constant('VALUE_1', constValue1()).
  constant('VALUE_2', constValue2()).
  constant('VALUE_3', constValuet3());

function constValue1() { /* Possibly several lines */ }
function constValue2() { /* Possibly several lines */ }
function constValue3() { /* Possibly several lines */ }
```

is (imo) more readable/"overviewable" than this:

```js
angular.
  module('...').
  constant('VALUE_1', {
    /* Possibly several lines */
  }).
  constant('VALUE_2', {
    /* Possibly several lines */
  }).
  constant('VALUE_3', {
    /* Possibly several lines */
  });
```

--
But it's totally a matter of preference.
The basic point regarding the original question is that the following won't work as expected:

```js
angular.
  module('...').
  constant('VALUE_1', VALUE_1).
  constant('VALUE_2', VALUE_2).
  constant('VALUE_3', VALUE_3);

var VALUE_1 = { /* Possibly several lines */ }
var VALUE_2 = { /* Possibly several lines */ }
var VALUE_3 = { /* Possibly several lines */ }
```

**Comment by johnpapa** [comment]
Yes, if you want to use a var, then you need to define it before you use it. If you want to keep the constant registration up top, then you can use a function below it to get its value.

**Comment by ruionwriting** [comment]
You 100% correct on this @gkalpak and I recognise that it goes down to a matter of preference.
