### ISSUE TITLE
File templates don't work with WebStorm 10

### ISSUE THREAD

**Issue by victorwoo** [johnpapa/angular-styleguide#395]
I've imported _webstorm-angular-file-template.settings.jar_ into WebStorm 10, `ng-c` works, but I can't see any newly added file templates.

**Comment by johnpapa** [comment]
dupe of #421

**Comment by MAustinMMDP** [comment]
If ng-c works you can find the template referenced in file>settings>Editor>Code Style>Live Templates>AngularJS

**Comment by victorwoo** [comment]
Yes I can find `ng-c` etc. in _file>settings>Editor>Code Style>Live Templates>AngularJS_ .
But I can't find new options in _File>New_ menu.

**Comment by MAustinMMDP** [comment]
No it will not show up as a new file type. All you need to do is open an existing JavaScript file or create a new JavaScript file and type in one of the following commands followed by the Tab key:

    ng-c
    ng-f
    ng-m

**Comment by victorwoo** [comment]
But I saw some new file type in my colleague's computer. All he has done is to import this _webstorm-angular-file-template.settings.jar_

**Comment by MAustinMMDP** [comment]
What you want is a custom file template. To do this you would open the file in the editor that you would like to create as a template, go to Tools > Save File as Template, specify a Name / Extension and click OK. Now when you navigate to File > New you should see the template you just created.

**Comment by MAustinMMDP** [comment]
Alternatively, you can go to File > Settings > Editor > Code Style > File and Code Templates, click on the + icon and add a Name, Extension then copy paste the code in the window and select OK.

**Comment by wardbell** [comment]
Now I know to whom I'm turning for Web Storm advice! 😊

**Comment by MAustinMMDP** [comment]
Anytime :smiley:
