### ISSUE TITLE
JSCS option disallowMultipleLineStrings is defined twice

### ISSUE THREAD

**Issue by sanderboom** [johnpapa/angular-styleguide#397]
Under [JSCS](https://github.com/johnpapa/angular-styleguide#style-y235), the option `disallowMultipleLineStrings` is defined twice. 

At line 23 it's sets to `true`, at line 66 to `null`.

**Comment by johnpapa** [comment]
thanks. make a PR?

**Comment by johnpapa** [comment]
thanks!
