### ISSUE TITLE
The Directive snippet is buggy

### ISSUE THREAD

**Issue by leongaban** [johnpapa/angular-styleguide#405]
I could not figure out why it wasn't working, however I found out on Stackoverflow that it's because you can't inject `$scope` into a Directive.

I removed this `directive.$inject = ['dependencies'];` and it worked!

http://stackoverflow.com/questions/30271903/why-is-my-directive-throwing-error-injectorunpr-unknown-provider

**Comment by johnpapa** [comment]
right. so whats the issues and with which snippet set?

**Comment by leongaban** [comment]
Well when I type `ngdirective` that line is included, shouldn't it be removed from the snippet?

**Comment by johnpapa** [comment]
Yes


John Papa




On Sat, May 16, 2015 at 10:59 AM -0700, "Leon Gaban" <notifications@github.com> wrote:












Well when I type ngdirective that line is included, shouldn't it be removed from the snippet?

**Comment by ruionwriting** [comment]
@leongaban can you clarify why to inject $scope on the directive itself. You can to that if adding a controller to a directive.

**Comment by leongaban** [comment]
@johnpapa OH didn't know I could! Yeah I'll do that later today :+1:

**Comment by leongaban** [comment]
@rulonwriting well the guy that answered my stack gave this really good explanation:

"$scope is not a service($scopeProvider is not exist in angular js) it is something special that is injected by angular itself into the controller as a child of $rootScope.

so you cannot explicitly inject it in service,directive...etc."

I made the fix and did a pull request, closing this now.
