### ISSUE TITLE
Any guidance to handle authorization? Something good to add?

### ISSUE THREAD

**Issue by chauey** [johnpapa/angular-styleguide#406]
Any guidance to handle authorization? Something good to add?

For example, how best to hide/show menu items or buttons or states/partials based on role and/or permissions on a certain resource/domain-object? 

Using the ui-router state resolver before going into the state? Better than checking in the state's controller's activation? 

Using directives on elements to show/hide or enable/disable them, passing in things like roles, permissions, resource so it can check if the logged in user has permissions or not?

Handling error codes from REST calls globally with perhaps some interceptor too?

**Comment by johnpapa** [comment]
good topic, but not for a style guide.
