### ISSUE TITLE
ASP.NET bundling/minification issues with .catch

### ISSUE THREAD

**Issue by ruionwriting** [johnpapa/angular-styleguide#409]
I've comment [issue #257](https://github.com/johnpapa/angular-styleguide/issues/257) with some information that I believe is relevant to bring to discussion but now I noticed it was closed.

I noticed that [ASP.NET MVC bundling](https://msdn.microsoft.com/en-us/library/eaa49yx4(v=vs.90).aspx) also have issues with **_.catch_** throwing an error and actually does not minify the code.

How the resulting bundle looks:

```bash
/* Minification failed. Returning unminified contents.
(514,18-23): run-time error JS1137: 'catch' is a new reserved word and should not be used as an identifier: catch
...
 */
(all the code here without being minified)
```

A possible solution would be to change styles [Y035](https://github.com/johnpapa/angular-styleguide#style-y035) and [Y060](https://github.com/johnpapa/angular-styleguide#style-y060) to use the regular promises described on the AngularJS [official docs](https://docs.angularjs.org/api/ng/service/$http#!):

``` javascript
$http(req).success(function(){...}).error(function(){...});
```

Any ideas?

**Comment by gkalpak** [comment]
Using `success()` and `.error()` is not a good idea, because they are not properly chainable.
There are even thoughts of deprecating them in the future.

**Comment by johnpapa** [comment]
Right, those are not "regular promises", those are angular specific syntax.

**Comment by johnpapa** [comment]
ASP.NET bundling may (I really hope) be replaced with gulp and grunt pluggable options. So I'm not too worried about that.

**Comment by glennrocksvb** [comment]
Encountered this issue at work and temporarily fixed it using square bracket notation:

	const ajax = fetch('...').then(callback);
	ajax['catch'](callback);
