### ISSUE TITLE
ng-repeat + ng-include

### ISSUE THREAD

**Issue by KamBha** [johnpapa/angular-styleguide#413]
Hi,
We have some data like this:-
```javascript
{
    fruits: [
        {
           type : "Apple",
           colour: "red"
        },
       {
          type: "Orange"
       }
    ]
}
```

Now, to generate this, we have the following:-

```HTML
<div ng-controller="FruitsController as fruitCtrl">
   <div ng-repeat="fruit in fruitCtrl.data" ng-include="fruitCtrl.findInclude(fruit)" ng-init="fruit"></div>
</div>
```
Now, the ng-init is there so we can pull through fruit in whatever controller is defined in the ng-include.

This looks very clumsy to me, especially in the controller, which ends up looking like this:-

```javascript
 function AppleController($scope, colourService) {
        var vm = this;

        init();

        function init() {
            // Retrieve featured hotels
           vm.data = colourService.convert($scope.gadget.colour);
        }
    }
```
Any thoughts on how to make this less clunky and clearer? I cannot think of a way of avoiding the ng-init and the access to $scope.

**Comment by johnpapa** [comment]
a directive maybe?

closing this as its better for stackoverflow
