### ISSUE TITLE
Filters in their own files ?

### ISSUE THREAD

**Issue by Cinetik** [johnpapa/angular-styleguide#414]
I'm having doubts about filters as there's not a lot about them in [Y420](https://github.com/johnpapa/angular-styleguide#style-y420).

I have multiple small filters for a specific module and I'd like to know if, following the single responsibility [Y001](https://github.com/johnpapa/angular-styleguide#style-y001), it's better to have a file for each one of them or as they are small, put them in a single file.

Also, if it's better to have multiple file, what about naming those files then ? Filters can have really big.

**Comment by johnpapa** [comment]
you could do 1 file if they are small. im not a fan of filters, so i rarely ever use them
