### ISSUE TITLE
Please consider to move "components" to the level of "app" folder

### ISSUE THREAD

**Issue by jamm** [johnpapa/angular-styleguide#415]
Please consider to move "components" folder in your example to the one level higher

```
components/
        calendar.directive.js
        calendar.directive.html
        user-profile.directive.js
        user-profile.directive.html
app/
    app.module.js
    app.config.js
```

Reason:
"components" is a folder for reusable components, they are not part of the current app, their code is not coupled with existing app and can be reused in other apps. When "components" are part of "app", it's not so obvious.

**Comment by AsifMushtaq** [comment]
I think the components mentioned in the style guidelines are the ones related to the app.

For the components that are reusable across various applications should have its own repository/project and would be a better idea to be shared through node or bower packages to avoid code duplication across various projects.

**Comment by jamm** [comment]
@AsifMushtaq that's **exactly** why I ask to move them to upper level. If developer will think about code reuse like "code reuse inside app" they will not be able to reuse this code somewhere else later, because there will be dependencies, coupling to another elements of app (at least paths, names). It's not real code reuse and not real encapsulation. Component should be written encapsulated from scratch (and I'm happy to see it's the corner-stone of components in ng2), then it will be ready for code reuse.

**Comment by johnpapa** [comment]
if they are cross app reusable, i move them to their own project and use bower to host them. so they wouldnt be at the top level, theyd be in their own thing

**Comment by johnpapa** [comment]
there are:
1. components that are used by many apps (lowest folder level or better yet, their own package in private bower)
2. components used by many modules in this app (folder under app)
3. components used by only 1 module in this app (in whatever specific module they are needed

that's the idea

**Comment by jamm** [comment]
It's not a question.
Definitions "2" and "3" are leading to non-reusable code and this issue exactly about eliminating them.

> if they are cross app reusable, i move them to their own project and use bower to host them

of course, and it's the most right way. But nobody will create new repository/project for each new component - at the beginning, they will be in "components" folder "1".

**Comment by johnpapa** [comment]
if 2 and 3 arent there, that means there are not specific components. sometimes we have app specific ones that only work in 1 app. or we have components that are just for a specific module. i have these all the time. so no, i cant agree to eliminate them

of course, if you dont have those requirements, dont follow that. just use cross app ones

> nobody will create new repository/project for each new component - at the beginning

I do. I know many teams who create a repo for reusable components. Custom themed controls, headers, footers, menus, etc that are specific to a company and go in a private bower repo (like a private nuget repo).

it doesnt mean everyone has to, but I absolutely think its the right thing to do if you have these situations.  

these are guidelines remember, you can choose any path you like :)

**Comment by johnpapa** [comment]
yes, agreed @AsifMushtaq

**Comment by jamm** [comment]
> I do.

You start new component in separate repo and after each minor change/debug you make commit/push/bower update? Or maybe you missing initial development/debug step?

**Comment by jamm** [comment]
> sometimes we have app specific ones that only work in 1 app

yes, but it's not legit exception. Any component should be build reusable, without dependencies. Otherwise at some moment developer will realize that this small component is useful not only here, but also in another apps, but it's very difficult to reuse because of dependencies/hardcoded values.

I know you will disagree, I write it just for future readers, in hope to help them.

**Comment by johnpapa** [comment]
Just saying its not legit doesn't make it a fact.

I agree that in principal components should be made reusable, but its not an absolute. There are very few "always" in our world.

**Comment by afirdousi** [comment]
Can't agree more @johnpapa 
Its always good to have your enterprise-wide-reusable components in a separate repo so they can be packaged and shipped to any other project. 

I have no idea how can we eliminate 2 and 3 here. We have them in almost every project.

**Comment by reflexdemon** [comment]
@afirdousi Can you please provide some example of what you are talking about in the case of 2 and 3.

**Comment by afirdousi** [comment]
For 2.,  There are few components handling the layout within my current app. Since they handle only the current app layout, there is no point in keeping them out of the app folder. They are still reusable across different modules in this same app. 

For 3.,  There is a advance filter search box which is highly customizable. I is used on different views within the same module within the app. Again, it is not useable across aps nor across modules but is still useable across different views within a module. 

(For 1., I have a social connect component which helps user connect to different social networks. This is used across apps)

Let's generalize it this way,

1. Components used across apps ( inter apps, inter modules , inter views)
2. Components used across modules ( inter modules, inter views)
3. Components used across views ( inter views)

Would love to hear from @johnpapa on this if he agrees or can explain it better.
