### ISSUE TITLE
WebStorm - Error: Invalid or corrupt jarfile

### ISSUE THREAD

**Issue by akarienta** [johnpapa/angular-styleguide#421]
I have just read [Style [Y252](https://github.com/johnpapa/angular-styleguide#style-y252)] and downloaded [jar file](https://github.com/johnpapa/angular-styleguide/blob/master/assets/webstorm-angular-file-template.settings.jar?raw=true) with the WebStorm templates.

However, when I try importing it into my Webstorm it is not presented in files which are available to be imported. When I try opening the archive by doubleclick I get this issue:

```
Error: Invalid or corrupt jarfile
d:\Users\username\Desktop\webstorm-angular-file-template.settings.jar
```
Tried to clone the repo also but got the same issue.

WebStorm version: 10.0.1

**Comment by johnpapa** [comment]
same as https://github.com/johnpapa/angular-styleguide/issues/395 ?

**Comment by victorwoo** [comment]
Is this issue fixable?

**Comment by MAustinMMDP** [comment]
I also have WebStorm version: 10.0.1 and was able to get it working. Not sure if this is the reason you are having difficulties, but you do not need to open the archive prior to importing; JAR files look like they need to be unzipped prior to installation but WebStorm should take care of this for you.

**Comment by johnpapa** [comment]
happy to take a PR for webstorm.

any takers?

**Comment by MAustinMMDP** [comment]
I'll take it :)

**Comment by joshtoo** [comment]
Should also be covered by #537

**Comment by johnpapa** [comment]
@MAustinMMDP this should be closed now that you ave your PR for https://github.com/johnpapa/angular-styleguide/pull/544
