### ISSUE TITLE
WebStorm IDE Autocompletion issue with "Accessible Members Up Top" Y052

### ISSUE THREAD

**Issue by michaelbromley** [johnpapa/angular-styleguide#427]
I really like the readability afforded by putting the public members at the top. Especially for longer files. However, in WebStorm (which I guess a lot of us use), it seems to confuse the autocompletion engine:

Consider the "traditional" approach:

```JavaScript
function myFactory() {
  function myMethod(arg) {
    //..
  }

  return {
    myMethod: myMethod
  };
}
```

When I am elsewhere in the project and type myFactory. - the IDE will provide solid autocomplete for the available method `myMethod`, along with any JSDocs I have defined above myMethod.

![webstorm1](https://cloud.githubusercontent.com/assets/6275952/8202470/8f18af0a-14da-11e5-8e7e-33d51662dff6.PNG)

However, if we flip this around to put the public API up top:

```JavaScript
function myFactory() {
  return {
    myMethod: myMethod
  };

  function myMethod(arg) {
    //..
  }
}
```

then WebStorm will no longer recognize `myFactory.myMethod()` as a function, and any JSDoc will have no effect.

![webstorm2](https://cloud.githubusercontent.com/assets/6275952/8202475/9a8f8b74-14da-11e5-92ee-56adfcdd3900.PNG)

This is actually a big disadvantage when it comes to large projects. Sure, with WebStorm you can click through a couple of times to get to the actual definition of `myMethod`, but you forego the advantages on in-place autocompletion with full documentation as you code.

There has been a similar discussion in https://github.com/johnpapa/angular-styleguide/issues/133, but this issue does not address the autocomplete issue specifically.

**Comment by runemoennike** [comment]
I have the same issue, although with VS2013/ReSharper. I suspect, though, that it's more of an issue with ReSharper and WebStorm than with the style guide.

**Comment by ceoaliongroo** [comment]
Maybe, you want to check Jetbrains issues:
https://youtrack.jetbrains.com/issues/WI

**Comment by michaelbromley** [comment]
Indeed it is a JetBrains issue. Partially fixed in WebStorm 10.0.4 and the EAP of PhpStorm 9, but not fully. 

See the issue on the JetBrains bug tracker here: https://youtrack.jetbrains.com/issue/WEB-17022

**Comment by ceoaliongroo** [comment]
Great!, i did a vote, to pull up the issue priority.

**Comment by runemoennike** [comment]
For those it might interest, I've created an issue for ReSharper too: https://youtrack.jetbrains.com/issue/RSRP-442304
