### ISSUE TITLE
Checkout my ORM project

### ISSUE THREAD

**Issue by ProLoser** [johnpapa/angular-styleguide#433]
Found a link to this project and completely forgot about it. Seems to be more focused on a styleguide, and while I have mixed / weak feelings about most of the points made in here, I have outlined a lot of stuff that has helped me exponentially step up my architecture game. Thought it might be worth checking out / consolidating, although I tend to stick to some fairly opinionated personal points that people may disagree with.

For example, I only like `controllerAs` in directives, but I do not like it anywhere else in the app. I also have mixed feelings of relying on hoisting since it means you're working with variables/functions  that it may be difficult to track down where they came from (although I understand the argument where order matters). I find verbose filenames/controller names silly.

However, I think there is a lot of things people need to learn about HOW to break up projects into routes, controllers, directives and services, and how to keep these structures sane and relevant even as your app grows into a massive scale.

### https://github.com/ProLoser/AngularJS-ORM

**Comment by dietergeerts** [comment]
Some remarks on your version:
- Controller As views can be reused with other controlles! You just set the controller and controllerAs in your route and always name it for example vm, problem fixed.
- I miss tips on how to share data between controllers, like in subcontrollers, as this is something used in almost every app, for example, you have a list of items and you want each list item to behave the same, you use the same controller for it, but you already have the data in the parent controller, then how do you give those objects to your controller? If you say: use one controller for all, then you are wrong as the behaviour of one such item is something different than the behaviour of the set of them.

**Comment by ProLoser** [comment]
@dietergeerts I don't get your second remark. You should be using resolves. You can inject resolves everywhere, at every level. I also don't get why team size matters. I also can't really speak on lazyloading since it's extremely hackish to do in ng1. If you want true lazyloading you'd be better off looking at ng2 and/or ui-router v1.0

Almost all of my recommendations on having a PROPER understanding of how ui-router works, and since one of the tenants in this styleguide is to use ui-router, I would think that knowing how to use the tools you recommend can only be seen as an improvement.

A lot of bad practices or things I disagree with are aspects that are fundamentally covered by routing and application breakdown. The breakdown I prescribe tends to be just as modular as component-heavy breakdowns, however it also lends itself to being much easier to refactor.

Renaming controllers and then reusing them in other controllers has large fundamental design issues:
1. Your controllers now communicate, something considered generally taboo in MV*(C)
2. Your controllers begin to bloat since they contain your reused logic
  1. This means you slow down your tendency towards services
  2. Your controllers (and therefore scope) becomes highly stateful which can lead to brittle-ness
3. You rely on scope inheritence which is generally bad across controllers, since this is the equivalent to global variables when you make assumptions about the existence of scope variables
  1. By placing a controller on a scope, there is no concrete contract in one controller that another controller is on the scope. You are just telling your coworkers to do it this way and crossing your fingers when you refactor hoping things don't silently break
  2. Renaming controllers becomes arbitrary and can lead to confusion about what this controller's state is.
  3. You don't have the ability to control the instances of controllers, spinning up multiple clones, handling buildup/teardown lifecycle
  4. The only way to share controllers is through scope
  5. You are now relying on controllers to be placed onto the view with the correct names in order to function properly. This means that part of how a controller work is defined in a completely separate place from the controller itself.
4. The injection signature of a controller acts like a **CONTRACT**. An interface that clearly states "In order for this controller to work properly, I need this data.
  1. Providing data to a controller via resolves is done before the controller kicks in
  2. Controller responsibilities shrink to do nothing more than (lightly) populating the view and assisting in routing control
  3. You have much stronger control over lifecycle using resolves, can spin up multiple instances of business logic packages (resolved objects) and can share them across controllers in a clearly defined contractual way.

Try looking over the project and the code before rejecting it. I have been working with angular and contributed to a huge share of the current knowledge-base that is angularjs since around v0.9 and second to the core team itself, personally have the some of the most angular-js code in the wild to date.

**Comment by ProLoser** [comment]
I could seriously go on, but this is a very specific argument that I never expected to get a lot of buy in and honestly isn't the biggest concern I have. For the most part, my main concern is getting people to leverage routing and project breakdown, relocating logic to the relevant locations and being mindful of how you go about designing your api so that it can be easily refactored and less brittle. `controllerAs` is merely one facet to this entire process.

Seriously, check out the repo and try giving me some example cases you don't feel would be elegantly solved by it.

**Comment by dietergeerts** [comment]
@ProLoser :

> Renaming controllers and then reusing them in other controllers has large fundamental design issues:
> 1. Your controllers now communicate, something considered generally taboo in MV*(C)
> 2. Your controllers begin to bloat since they contain your reused logic

I think you don't understand what I mean here. I also have to note that I come from a MVVM background and had never used MVC before that, which is a great benefit because in MVVM, your views and viewmodels are really loosly coupled, unlike MVC! 

So the controllers that are being reused really don't know each other, it's the view that will use those 'subcontrollers' And in such cases, you can't use resolves etc... For example, when you have a route where you show a list and detail next to each other, the list will be powered by a controller and the detail part will be powered by another controller. The part where you 'give' the object to the detail controller is important here, as it will be the selected one. So you 'transfer' the object through your view from one controller to the other. And it doesn't stop there. What if you want to show your list items really detailed with several actions  you can do for each? then you would use a controller that acts on one such item. So your view will create a controller for each item in that list. So in this case we also need to 'give'' the object to that controller. Doing this instead of one massive controller for each major route view will give you more power to switch out controllers and views. if for example you don't want to view your list items in a detailed manner, you can just choose another view and controller to display them and your done.

All of this is hard to grasp for people that started out with MVC as they are used to boilerplate code, while starting out with MVVM will get you used to think in small pieces that act on their own and then compose into bigger stuff.

In angular, you'll get controllers that act on one model object, and they will get it from ngModel, or something you choose. No need for resolves here as those controllers aren't intended to be used by a main route view, but as part of it.

**Comment by dietergeerts** [comment]
@ProLoser : the lazyloading is done with https://github.com/ocombe/ocLazyLoad, and it only requires two lines of code actually....

**Comment by ProLoser** [comment]
Everything you just described doesn't belong in a controller. It belongs in a factory or service. Your objects should be rich and highly functional and completely agnostic of angular-centric concepts, as pretty much all of my classes are. They contain 95% of my logic and can be passed around.

Data is packaged with methods / logic together, is completely self contained, and allows the logic to act upon itself using the data contained within itself. This is not something that should be packaged into a controller.

If you have a list and a details view, the details view should be a sub-state of the list. Which allows you to define a sub-state controller. Which allows you to resolve the sub-state object and inject it into that controller. This "passing" of data you describe is not defined contractually anywhere in your code. You are essentially setting scope variables that the controller now must 'assume' exist. You are also in all likeliness wrapping your ng-controller type code in ng-if statements instead of making it state-controlled.

```
$stateProvider.state('items', {
  controller: function Items($scope, items) { ... },
  template: '<!-- list goes here --><ui-view><!-- Details go here --></ui-view>',
  resolve: {
    items: function(Item) {
      return Item.list();
    }
  }
}).state('items.details', {
  controller: function ItemDetails($scope, item) { ... },
  resolve: {
    item: function(items, $stateParams) {
      // note we're referring to a previous resolve
      return items[$stateParams.index]; // or something
    }
  }
});
```

This is how what you just described SHOULD be tackled.

**Comment by ProLoser** [comment]
I should also mention that almost ALL of your logic belongs in the `Item` class, _not_ in either controller. Updated with relevant code.

**Comment by ProLoser** [comment]
This demonstration shows that it's not important to pass around 'controllers', or naming them, or packaging any important logic whatsoever inside of them. Your simple factories contain most of your logic and are completely autonomous, HIGHLY testable and could in all likeliness be used _completely independently of angular_. They can set state flags on themselves such as if an action is in progress (like saving, creating, uploading) and require a lot less parameters and data juggling. You simply pass these objects around in your app and manage them, and the view has DIRECT access to ALL of these methods since the ENTIRE object is placed onto the view. So instead of `ng-click="myController.save(myData)"` you get a far more packaged `ng-click="item.save()"`.

**Comment by ProLoser** [comment]
I'm going to throw this out because I'm starting to beat a dead horse:

I have been doing way more angular  for far longer than you may very well realize and have personally contributed to a lot of the design patterns in this guide. At the very least try my structure out before you discard it or poke holes in it as I have thoroughly done to every practice in here.

I am completely open and receptive to criticism of my design and more than happy to improve/refactor/change/drop things when it makes sense, it took me several years to arrive at where I am now, but I have built written a LOT of documentation on this stuff and without trying out what I propose I will have a hard time taking arguments against it seriously.

Understand that ui-router is far more than a simple routing system. Understand that ng2's a major new project structure feature (component router) is based entirely on the work that has gone into ui-router. Finally, understand ALL the features of the tools you're using (ui-router) inside and out, as I've come to find most people in the ng community don't, which in turn leads to problematic project structures in angular.

**Comment by ProLoser** [comment]
Please go checkout my repo, profile, and body of work before outright discarding it or ignoring my points.

**Comment by dietergeerts** [comment]
@ProLoser : I'm not discarding or ignoring your work, it's just missing the thing I'm describing, like all other guides out there...

**Comment by ProLoser** [comment]
The state machine controls what is active.

**Comment by ProLoser** [comment]
It sounds like you don't leverage sub-states in your app, which is one of the core values of UI-Router. I don't really want to keep arguing over this point anymore, as it's mostly superficial syntax.

**Comment by johnpapa** [comment]
interesting points ... but i don;t see any action items here so i am closing.
