### ISSUE TITLE
Angular2 migration guide

### ISSUE THREAD

**Issue by filipesilva** [johnpapa/angular-styleguide#439]
Hey, at ngconf @johnpapa mentioned work was in progress for a Angular2 migration guide. Any update on that?

**Comment by johnpapa** [comment]
Working on some details with the team

**Comment by filipesilva** [comment]
Glad to hear, I'm looking forward to it. 

This month I'm going to give a talk at the AngularJS Dublin Meetup about style guides (yours specifically) and if there was something for ng2, I wanted to mention it.
