### ISSUE TITLE
Best practice for using builtin globals

### ISSUE THREAD

**Issue by remcohaszing** [johnpapa/angular-styleguide#443]
In In the [Vendor Globals](https://github.com/johnpapa/angular-styleguide#style-y240) section it is mentioned that they should be injected as constants for testibility.

What would be the recommended way to handle builtin globals such as `Blob`, `navigator`, etc?

Should they be injected as constants or accessed using `$window`?

**Comment by johnpapa** [comment]
if something is on window, you should use $window.
