### ISSUE TITLE
Sublime Snippets for new files

### ISSUE THREAD

**Issue by mseancole** [johnpapa/angular-styleguide#445]
Love the guide, and love the snippets.

However, while using them I noticed that they are limited to only being used on JavaScript files. This means that it wont work on a new, unsaved file, until the proper syntax is selected, or until it is saved as a JavaScript file.

I've got a working solution and will submit a PR shortly.

**Comment by johnpapa** [comment]
PR ?

**Comment by johnpapa** [comment]
closing, but feel free to PR

**Comment by mseancole** [comment]
PR has already been implemented at #446

**Comment by johnpapa** [comment]
awesome!
