### ISSUE TITLE
Adding "Patterns/Anti-patterns" from official Angular repo ??

### ISSUE THREAD

**Issue by fabm22** [johnpapa/angular-styleguide#447]
Granted this styleguide here starts to be seen as a "GOTO" for architecturing Angular apps (at least it is to me), many might actually not read the few official (so to speak) patterns you will find in official Angular repo 

https://github.com/angular/angular.js/wiki/Best-Practices
https://github.com/angular/angular.js/wiki/Anti-Patterns

They are short anyway...
What do you think?

**Comment by johnpapa** [comment]
We shouldLink to them at least. Let me look me over and talk to angular folks. 
Thanks. Good idea. 


John Papa




On Wed, Jul 15, 2015 at 2:44 AM -0700, "fabm22" <notifications@github.com> wrote:












Granted this styleguide here starts to be seen as "GOTO" for architecturing Angular apps (at least it is to me), many might actually not read the few official (so to speak) patterns you will find in officail repo 



https://github.com/angular/angular.js/wiki/Best-Practices

https://github.com/angular/angular.js/wiki/Anti-Patterns



They are short anyway...

What do you think?

**Comment by johnpapa** [comment]
I looked them over and did not see anything to grab that was a style we did not already list. But if you feel differently, please make a PR.

Closing
