### ISSUE TITLE
Component directives

### ISSUE THREAD

**Issue by Jandalf** [johnpapa/angular-styleguide#450]
What do you think about using the [component directive](https://www.airpair.com/angularjs/posts/component-based-angularjs-directives) approach? It was a suggestion by a core AngularJS dev to split up big views into small components.

I really liked the approach it will completely wipe out real controllers coupled with a view. Instead you would only have directives that contain other directives, even the router would just display a directive. This seems also as a good way on the road to Angular 2. I could write this up and make a PR if you point me to the right place to put it.

**Comment by dietergeerts** [comment]
What's wrong with using controllers for this? I would rather be able to switch out views for the same controller, so that how it looks can depend on where it is used, with the same functionality. View and ViewModel should be separate...

**Comment by Jandalf** [comment]
I just found [Issue 444](https://github.com/johnpapa/angular-styleguide/issues/444) and I think this goes in the same direction.
