### ISSUE TITLE
ng-class question

### ISSUE THREAD

**Issue by alsfurlan** [johnpapa/angular-styleguide#453]
Hi @johnpapa,

I have a question and noticed that the guide did not clarify the best way to do this. So I would like to ask you and suggest it to be included in your guide the answer.

What better way to do this?
```
<div data-ng-class="controller.setClass()"></div>
```
```
function setClass() {
          return checkFunction() ? 'col-md-12' : 'col-md-11';
}
```

**OR**
```
<div data-ng-class="{ ctrl.checkFunction() ? 'col-md-12' : 'col-md-11' }"></div>
```

**OR**
```
<div data-ng-class="{ ctrl.checkFunction(): 'col-md-12' : ctrl.inverseCheckFunction(): 'col-md-11' }"></div>
```

**Comment by dietergeerts** [comment]
A controller shouldn't tell how your view needs to look. So use the object notation of ngClass to map a class on info you have available. Btw, this notation is more clear: {class_name: bool_value_from_expression}.

**Comment by johnpapa** [comment]
id agree with @dietergeerts here. its not something i care deeply about. if i saw it in the controller I would not worry, but i dont like classes in the controller either

**Comment by alsfurlan** [comment]
@johnpapa @dietergeerts Neither do I like the class on the controller. Thanks for you opinions.
