### ISSUE TITLE
Using prototype for controller methods

### ISSUE THREAD

**Issue by victorherraiz** [johnpapa/angular-styleguide#454]
is there any reason to avoid declaring controller methods using the prototype with the "ControllerAs syntax"? 
The guide only uses the constructor to add methods to vm (alias this)

**Comment by johnpapa** [comment]
if a controller is used one and only one instance is created, a prototype method is going to add that much value.

**Comment by victorherraiz** [comment]
Controllers are not singletons. Every time you visit one a new instance is created. Therefore, using the prototype to add functionality should have some advantages (e.i. memory and speed) 

http://stackoverflow.com/questions/3493252/javascript-prototype-operator-performance-saves-memory-but-is-it-faster

**Comment by johnpapa** [comment]
Correct, they are not singletons. And prototypes are good when you are creating lots and lots of instances and they all live at the same time. But this is not the oft case.

You create a controller, use it, then it goes away. If you have a controller linked to a View you do this once when going to the view, use it, then it is destroyed. 1 instance at a time.

If you were to create 100 instances of the View it would have 100 instances of its controller, and then prototype would make sense. But we dont usually do that. Mostly we do 1.

Directives ... if it was a directive with a controller you could have many of a directive on a page. In that case you have many of that controller. But how many? Is it worth it for 4 instances? Not in my opinion. If you do it repeatedly in a loop, perhaps yes.

**Comment by victorherraiz** [comment]
Then I will use prototype when the number of instances could be large (e.g. table cell decorators) and keep it simple for the rest.
Thank for your comments and very nice guide (One of the best around)

**Comment by johnpapa** [comment]
to be clear, prototype will not hurt you in any event.

i just dont bother with it if i dont need it.
