### ISSUE TITLE
I have implemented the snippets in netbeans code templates

### ISSUE THREAD

**Issue by talamaska** [johnpapa/angular-styleguide#458]
Would you like me to share the exported config zip, it's just how netbeans is handling  the snippets templates

**Comment by RichardSilveira** [comment]
I am would like to know that too!

**Comment by johnpapa** [comment]
can they be PR'd as a link to a raw source? or the raw source uploaded here? zip is my last choice ... especially after the crazy changes we have had to make for the jar files for the webstorm ones.

**Comment by johnpapa** [comment]
interested in making this PR?

**Comment by talamaska** [comment]
Yes, I had to reinstall netbeans, because egit bugged out.
