### ISSUE TITLE
Calling functions inside functions in service/factory

### ISSUE THREAD

**Issue by tobbbe** [johnpapa/angular-styleguide#465]
How do recommend calling a service function inside another function?
    
    function dataservice() {
        var b = 42;
        
        var service = {
            getSomething: getSomething,
            getSomethingElse: getSomethingElse
        };
    
        return service;
    
        ////////////
    
        function getSomething() {
            // this might cause problems right?
            return calcSomething(value);
        }
        
        function getSomethingElse() {
            // this might cause problems right?
            return calcSomething(value);
        }    
        
        function calcSomething(a) {
            return a + b;
        }
    }

**Comment by gkalpak** [comment]
> // this might cause problems right?

@tobbbe, what kind of problems do you have in mind ?

**Comment by reflexdemon** [comment]
@tobbbe This looks perfect. I don't see any issues on this. In fact, in my current project I have something similar to this where i need to do some string manipulation before hitting the API. We kind of put the logic inside a `private function` and that stuff seems to work like a charm.

**Comment by robrothedev** [comment]
You're doing it correctly.  You're basically using calcSomething() as a private function since it's not part of your service object that you're returning.

**Comment by tobbbe** [comment]
I thought it could fuck with the scope (lexical?) in loops etc. But I might have get that wrong then :)
I thought I'd might need a `var that = this;` to be safe. But I dont then?

**Comment by Markionium** [comment]
As long as you don't use `this` within calcSomething you're good to go. Since you most likely won't this shouldn't be a problem.

**Comment by johnpapa** [comment]
nope. no issues there.

**Comment by breadcrumble** [comment]
Thanks for posting this question and for the people who answered it! It helped me in my project :)
