### ISSUE TITLE
What is the best way to store options for select ?

### ISSUE THREAD

**Issue by maisnamraju** [johnpapa/angular-styleguide#475]
I have this long list of options variables  that are to be used as options for the select dropdown and I am wondering if there is a better way to store those variables somewhere else ? What would be a good practice in this case ?

**Comment by zachlysobey** [comment]
you can register them as an `angular.value` perhaps

Zach Lysobey
(203) 984-4048

On Wed, Aug 5, 2015 at 1:19 PM, Maisnam Raju Singh <notifications@github.com

**Comment by dietergeerts** [comment]
It depends, if you use it only once, you can just hard code it in the place you need it, otherwise, you could use the angular.value like @zachlysobey mentions. It also can be that you better get them from your BE, it really depends on the situation.

**Comment by maisnamraju** [comment]
Thanks, that makes sense
