### ISSUE TITLE
Add Suggested Template Format

### ISSUE THREAD

**Issue by JLLeitschuh** [johnpapa/angular-styleguide#481]
I've found that having templates with each tag on its own line can reduce merge conflicts, make diffing a line easier, and make the code more readable.

Is this a style that others think should be promoted in the angular world?

Example:
https://github.com/angular-ui/ui-grid/blob/master/src/templates/ui-grid/ui-grid-filter.html#L21

**Comment by dietergeerts** [comment]
Lol, everything on one line gets really hard indeed. I mostly split up the lines, depending on how long each attribute gets. But in the example, it's much more clear with each attribute on one line.

**Comment by JLLeitschuh** [comment]
Oh, you mean passing all of the different keywords like `track by`, ect...

**Comment by johnpapa** [comment]
there are good thoughts in here, but i dont see this as an angular style. its more of managing your html.
