### ISSUE TITLE
Inconsistent @ngInject comments (`/**` vs `/*`)

### ISSUE THREAD

**Issue by zachlysobey** [johnpapa/angular-styleguide#484]
At the top of the [ng-annotate section](https://github.com/johnpapa/angular-styleguide#ng-annotate), the @ngInject syntax is described as ` /** @ngInject */`, but everwhere else the is only one asterix on the opening comment (`/* @ngInject */`).

Want a PR to standardize on the later?

**Comment by johnpapa** [comment]
that was a typo. so yes, /* @ngInject */ is preferred.

Sure, feel free to PR it or I will get it if you dont want to.

**Comment by johnpapa** [comment]
closed from the merge
