### ISSUE TITLE
AngularJS Components Definition

### ISSUE THREAD

**Issue by tato123** [johnpapa/angular-styleguide#488]
Primarily a suggestion (not a direct issue, but would provide clarity in terms of code style usability)
-------
My team struggles with understanding how components differ from traditional OOP packages. While part of this is explaining it as a lead, I realize there is a gap in the style guide that doesn't highlight the difference of a component from traditional package / grouping structures (I assume style guide is referring to google's best practice for app structure when referring to components https://docs.google.com/document/d/1XXMvReO8-Awi1EZXAXS4PzDzdNvV6pGcuaF4Q9821Es/pub). 

Since components play a key role in AngularJS 2, it would be helpful to include in the styleguide some information on application structure.

**Comment by johnpapa** [comment]
will think about it. but im not sure i agree components belong here at this time
