### ISSUE TITLE
Function in a controller

### ISSUE THREAD

**Issue by EggieCode** [johnpapa/angular-styleguide#489]
Who to style function that implement form a service.
For a example a popover ($inoicpopover). First parameter is to setup props.
That setup a function to for example load data (ajax) to display in the popover.

Is there a nice way to style that?
```javascript
$ionicModal.fromTemplateUrl('templates/selectbox.html', {
        scope: vm,
        animation: 'slide-in-up'
}).then(function(modal) {

        $http.get('http://crossfitagenda.nl/boxes.php')
                .success(function (data) {
                        $scope.boxes = data;
                        if(cbmConfig.loginUrl != null) {
                                for(var i in $scope.boxes) { 
                                        if($scope.boxes[i].loginUrl == cbmConfig.loginUrl) {
                                                $scope.selectedBox = $scope.boxes[i];
                                        }
                                }
                        }

                });

        vm.popover = modal;

});
```

I hope you can help me with it.

**Comment by johnpapa** [comment]
This guide has a lot of tips you can follow for this. 

1. don't use anonymous functions, use named ones. That will avoid the massive indenting and make it easier to read
2. don't use $http in the controller, use $http from a service/factory
3. use .then , not .success

**Comment by dietergeerts** [comment]
Why load the data and then check if you want to do something with it? Just check that loginUrl first and then load the data...
