### ISSUE TITLE
$resource in services

### ISSUE THREAD

**Issue by ggondim** [johnpapa/angular-styleguide#501]
What is the best `$resource` approach inside services, considering `$resource` return a function that can be instantiated?

To make myself clearer...

Considering this:

    var UserResource = $resource('/user/:userId/', {userId:'@id'});
    // list
    var users = UserResource.query();
    // update
    var user = users[0];
    user.name = "G.Gondim";
    user.$save();
    // create
    var newUser = new UserResource();
    newUser.name = "J.Papa";
    newUser.$save();
    // delete
    newUser.$remove();

How to achieve this:

    function UserController(UserService) {
        var vm = this;
        vm.getUsers = getUsers;
        vm.addUser= addUser;
        vm.updateUser= updateUser;
        vm.deleteUser= deleteUser;
        
        function getUsers() {
            return UserService.list();
        }
 
        function addUser() {
            var user = new ? // who is this constructor in the service?
            return UserService.insert(user);
        }
 
        function updateUser(name) {
            var user = anOldUserRetrievedBefore;
            user.name = name;
            return UserService.update(user);
        }
 
        function deleteUser() {
            var user = anOldUserRetrievedBefore;
            return UserService.delete(user);
        }
    }

Using this:

    function UserService() {
        var service = {
            list: listUsers,
            update: updateUser,
            insert: insertUser,
            delete: deleteUser
        };
        return service;
       
        /////////////
        function listUsers() {
            
        }
        function updateUser() {
            
        }
        function insertUser() {
            
        }
        function deleteUser() {
            
        }
    }
    angular.module("MyModule").factory("UserService", UserService)

Thanks in advance.

**Comment by johnpapa** [comment]
I'm not a fan of `$resource` so I'm not the guy to ask. I use `$http`.

also better for StackOverflow
