### ISSUE TITLE
"camelcase" setting of jshint has been deprecated

### ISSUE THREAD

**Issue by ghost** [johnpapa/angular-styleguide#502]
"camelcase" setting of jshint has been deprecated as follows from http://jshint.com/docs/options/#camelcase
+ their explanation is quite interesting: they are moving away from style-related concerns
Thus we may want to adjust Y230 for that.

**Comment by zachlysobey** [comment]
Seems like this rule is redundant with the following JSCS rule already in the styleguide:

```json
"requireCamelCaseOrUpperCaseIdentifiers": true
```

> Requires identifiers to be camelCased or UPPERCASE_WITH_UNDERSCORES

Think we should just remove the jshint rule?

**Comment by oharlem** [comment]
@zachlysobey 
Aha! Good catch on "requireCamelCaseOrUpperCaseIdentifiers". Thank you.

>> Think we should just remove the jshint rule?

Sure, however,
while the Styleguide splits responsibilities between jshint (for JS) and jscs (for styles), looks like jshint.rc requires a good review, as it has other style-related instructions like "quotes" and "indent".

**Comment by zachlysobey** [comment]
> other style-related instructions like "quotmark" and "indent".

Also marked as deprecated in that link you sent.

I agree that this needs a good review, but I don't have super-high motivation todo it, since I personally use Eslint as a replacement for jshint+jscs. Hopefully I'll get a PR for *that* set up at some point.

**Comment by oharlem** [comment]
@zachlysobey 
hm... There's definitely a benefit using Eslint, as it can be configured to check app-specific concerns, like naming conventions, not just JS.
Moreover, https://github.com/Gillespie59/eslint-plugin-angular looks like a big step towards implementing some rules from _this Styleguide_ for Eslint. However, I see any activity about Eslint stopped in this repo about half a year ago :/

**Comment by johnpapa** [comment]
if the rule is in jscs, then it can be removed from jshint.

im sure there are a few lurking there.

**Comment by johnpapa** [comment]
eslint is nice, but the setup is less smooth than jshint/jscs ... which is why i stuck with it for now.

**Comment by belchugov** [comment]
I've just watched this video [Linting JavaScript with ESLint](https://egghead.io/lessons/javascript-linting-javascript-with-eslint) and think that implementing ESLint is more straightforward than I thought.

**Comment by zachlysobey** [comment]
Not sure if/when I'll get a chance, but I've been thinking about putting
together a PR with for ESLint stuff. If someone wanted to collaborate...

Zach Lysobey
(203) 984-4048

On Fri, Aug 28, 2015 at 3:40 AM, Dimitar Belchugov <notifications@github.com

**Comment by belchugov** [comment]
I will be happy to collaborate.

**Comment by johnpapa** [comment]
Does someone want to remove the duplicate rule?

**Comment by belchugov** [comment]
I'm on it.

**Comment by johnpapa** [comment]
closing due to inactivty
