### ISSUE TITLE
Why place services and components in seperate folders? 

### ISSUE THREAD

**Issue by Patrickkk** [johnpapa/angular-styleguide#505]
In the structure of the application why don't you place the services in the same folder as ui, but instead separate them in a different folder? i think it would increase the L if your lift principle if services related to components reside with those components. for example a service to retrieve people should reside in the people folder.

**Comment by johnpapa** [comment]
Services that cross modules can go more towards the root. Often in a shared module.

Services that are for a specific module go in the specific module.

**Comment by Patrickkk** [comment]
Hi, 

Thank you for your quick reply. That's what I though, either its not explicitly mentioned or I missed it. The i will use the same principle for directives and other stuff.
