### ISSUE TITLE
vm instead of this

### ISSUE THREAD

**Issue by gaboAcosta** [johnpapa/angular-styleguide#513]
Hello, I'm very new to your guide and on the first time that I tried to comply with using this instead of $scope I've already come to an issue.

You'll see, sometimes, libraries like this one:

https://github.com/daniel-nagy/md-data-table

Require you to pass them a callback function that will be triggered at some point, for instance, whenever the user activates the pagination or sorting.

So, if using the this keyword, when the library executes the callback the context of the function changes and this no longer means the view model, some developers have fixed this by doing:

````
var self = this;
````
Which, to be honest, looks terribly unreadable to me.

One solution I've found to like a little bit more, is if on the first line of the controller one would declare:

````
var vm = this;
`````

Which might seem like the same thing, but, since we are already naming the controller as vm to represent the view model on the views, It really makes sense to take this approach in the controller to alwasy be sure about what context you are referring while programming.

On the same style than your guide, Why? Because developers should never worry if the context of a function is clear, and using the self variable makes it hard to read, while using vm creates consistency throughout the code

**Comment by gkalpak** [comment]
Hey, @johnpapa, how come you didn't think of aliasing the controller as `vm` ? (lol)

Fun aside, this is already a recommendation: [Style Y032][1]

[1]: https://github.com/johnpapa/angular-styleguide/blob/master/README.md#style-y032

**Comment by gaboAcosta** [comment]
Thanks, you where very helpful.

Fun aside, you where very helpful.
