### ISSUE TITLE
With a data factory do you create a single data factory or do you have multiple data factories each of which handle a separate request to the server

### ISSUE THREAD

**Issue by MichaelGofron** [johnpapa/angular-styleguide#514]
Currently my team is using a single data factory but we're not sure as to whether to separate it into multiple data factories in order to satisfy the single responsibility principle. It seems that the style guide recommends putting all data operations into a data factory.

**Comment by zachlysobey** [comment]
https://github.com/johnpapa/angular-styleguide#style-y050

> Factories should have a single responsibility, that is encapsulated by
its context. Once a factory begins to exceed that singular purpose, a new
factory should be created.

Zach Lysobey
(203) 984-4048

**Comment by zachlysobey** [comment]
I posted that a bit quickly. It is easy to read the following section as
though it recommends a single data service, but my interpretation is that
new factories should be created when it exceeds a single responsibility.
Perhaps it is worth adding a note in this section as well?

https://github.com/johnpapa/angular-styleguide#data-services



Zach Lysobey
(203) 984-4048

**Comment by johnpapa** [comment]
put like service functions in a like service. 

a service/factory should contain functions that all relate to a theme. when they dont, then you split.

1 service/factory per app is likely not realistic for many situations
