### ISSUE TITLE
[Style Y256] A VS Code Angular snippets bug

### ISSUE THREAD

**Issue by doggy8088** [johnpapa/angular-styleguide#518]
In the [VS Code Angular snippets](https://github.com/johnpapa/angular-styleguide/blob/master/assets/vscode-snippets/javascript.json?raw=true) looks like has a bug in **ngdirective** snippet. 

The **.factory('Directive', Directive);** should change to **.directive('Directive', Directive);**.

**Comment by attilacsanyi** [comment]
+1

**Comment by johnpapa** [comment]
thx
