### ISSUE TITLE
Using Prototype methods for Controllers

### ISSUE THREAD

**Issue by jforjava1981** [johnpapa/angular-styleguide#524]
I have joined a team where we are using AngularJS. I have good amount of experience in Javascript however have just started on AnjularJS. We are following this guideline as a general approach. We are using Controller as syntax everywhere. As part of the team discussion one point was raised in the context of keeping Controllers thin. And some of the members are of the view that all the methods should be defined as part of Controller's prototype instead of instance methods(attached to  this).  

I searched a lot but i didn't get any particular advantage/disadvantage of using this approach over instance methods other than 
            1)   of having shared memory for the functions. 
            2)   Inheritance can be used to share/reuse functionality  in a controller hierarchy(I doubt if this is a common scenario in AngularJS controllers and if having hierarchy of controllers is good idea.)
        

What we have decided is 
1) all methods should be added to prototype of controller
2) dependencies injected should be exposed by attaching them  to "this" variable so that they are available to proptotype methods.

Would like to know any clear advantages and disadvantages from AngularJS perspective.

**Comment by johnpapa** [comment]
When adding a function to a prototype of a controller, this is helpful if you create many instances of the controller. This is good if you do this for a directive's controller where that directive is instanced many times. However if it is for a View's controller, you only have 1 of those, so there is no value using the prototype there.

This was talked about here too ... https://github.com/johnpapa/angular-styleguide/issues/454

#dupe

**Comment by jforjava1981** [comment]
Then what is the generic and best alternative to implement thin controllers. We are facing issues where controller constructor functions get too bulky and lengthy as we go on adding functions to this.even for pages where we have not more than 10 fields?
