### ISSUE TITLE
Multiple routes for a module

### ISSUE THREAD

**Issue by JFSolorzano** [johnpapa/angular-styleguide#527]
In your style guide you only declare one [route in a module](https://github.com/johnpapa/angular-styleguide#style-y270), how could i setup multiple routes in a single module?

I ask this because i have a users module, where i want these routes:

```
users/
users/:id
```

**Comment by bampakoa** [comment]
@JFSolorzano I guess you can declare it in the same file your-module.routes.js

**Comment by JFSolorzano** [comment]
Following the [example](https://github.com/johnpapa/ng-demos/blob/master/modular/src/client/app/avengers/config.route.js), this is the function getRoutes:
```javascript
function getRoutes() {
        return [
            {
                url: '/avengers',
                config: {
                    templateUrl: 'app/avengers/avengers.html',
                    controller: 'Avengers',
                    controllerAs: 'vm',
                    title: 'avengers',
                    settings: {
                        nav: 2,
                        content: '<i class="fa fa-lock"></i> Avengers'
                    }
                }
            }
        ];
    }
```

How could i add ```/avengers/:id``` ?

**Comment by bampakoa** [comment]
function getRoutes() {
        return [
            {
                url: '/avengers',
                config: {
                    templateUrl: 'app/avengers/avengers.html',
                    controller: 'Avengers',
                    controllerAs: 'vm',
                    title: 'avengers',
                    settings: {
                        nav: 2,
                        content: '<i class="fa fa-lock"></i> Avengers'
                    }
                }
            },
            {
                url: '/avengers/:id',
                config: {
                    templateUrl: '',
                    controller: '',
                    controllerAs: '',
                    title: '',
                    settings: {
                        nav: ,
                        content: ''
                    }
                }
            }
        ];
    }

**Comment by JFSolorzano** [comment]
@bampakoa Thnks, another question, in that example johnpapa used ngRoute right?, how could i change it to use ui-route?

**Comment by bampakoa** [comment]
@JFSolorzano that is correct. John uses ngRoute. I have not tried to port its example using ui-route but I think it can be done easy. Maybe @johnpapa would like a PR for its guidelines?

**Comment by JFSolorzano** [comment]
Yes please!

**Comment by attilacsanyi** [comment]
I use hottowel as my project skeleton and it definitely use ui-router,  not ngRoute.

**Comment by JFSolorzano** [comment]
Mmm is that a generator?, i'm trying not to use generators, i just take the ideas that seems nice to me, and apply them to my code, and structures, could you please give me the link to know what you're talking about @attilacsanyi ?

**Comment by johnpapa** [comment]
yep, use multiple in a file for that module. And just use ui-router instead. I use ui-router, myself.

closing ... as this is a question.

**Comment by JFSolorzano** [comment]
Oh i see what you mean, [this is hottowel routing with ui-routing](https://github.com/johnpapa/HotTowel-Angular/blob/master/NuGet/HotTowel-NG/app/config.route.js) right?

i see some differences between your way of routing compared with the way ui-router docs says, what i did is this:

```
(function () {

    'use strict';

    angular.module('app.users')

        .config(['$stateProvider', '$urlRouterProvider', routes]);

    /* @ngInject */
    function routes($stateProvider, $urlRouterProvider) {

        $urlRouterProvider.otherwise("/");
        // Set up the states
        $stateProvider
            .state('users', {
                url: '/users',
                templateUrl: 'modules/users/users.view.html',
                controller: 'UsersController',
                controllerAs: 'vm'
            });
        
    }

})();
``` 

But if i use your code but i want to use states instead of routes, i would do the following right @johnpapa?
```javascript

(function () {
    'use strict';

    angular.module('app.users')

        // Collect the routes
        .constant('routes', getRoutes())

        // Configure the routes and route resolvers
        .config(['$stateProvider', 'routes', routeConfigurator]);
    
    function routeConfigurator($stateProvider, routes) {

        routes.forEach(function (r) {
            $stateProvider.state(r.state, r.config);
        });
        $routeProvider.otherwise({redirectTo: '/'});
    }

    // Define the routes 
    function getRoutes() {
        return [
            {
                state: 'listUsers',
                config: {
                    url: '/users',
                    templateUrl: 'modules/users/users.view.html'
                    title: 'users',
                    controller: 'UsersController',
                    controllerAs: 'vm'
                }
            }, 
            {
                state: 'specificUser',
                config: {
                    url: '/users/:id',
                    title: 'specific user',
                    templateUrl: 'modules/users/userDetail.view.html'
                    controller: 'UsersController',
                    controllerAs: 'vm'
                }
            }
        ];
    }
})();
```

**Comment by attilacsanyi** [comment]
Yes I definitely mean this @JFSolorzano
