### ISSUE TITLE
What are all the angular snippets and file templates available for webstorm?

### ISSUE THREAD

**Issue by JFSolorzano** [johnpapa/angular-styleguide#529]
This is a question, but i don't know how to label it. I use Webstorm to develop my webapps, and i would like to know about all the snippets and templates that are available since in the [guide](https://github.com/johnpapa/angular-styleguide#style-y252) the only ones descriobed are:

```
ng-c // creates an Angular controller
ng-f // creates an Angular factory
ng-m // creates an Angular module
```

**Comment by MAustinMMDP** [comment]
That is all I am aware of in regards to the angular-styleguide but I was planning on creating a directive template. What snippets or templates are you looking for?

**Comment by JFSolorzano** [comment]
It would be nice to have a template of services, filters, directives, states(ui-router), config, run, as they're for brackets @MAustinMMDP

**Comment by johnpapa** [comment]
feels free to add via a PR

**Comment by MAustinMMDP** [comment]
I've created live templates to match what is already available for the other editors, i.e., controller, directive, factory, module, service, filter. I am still trying to figure out how to archive the templates to add via a PR but until then you can reference the [webstorm-live-templates repo] (https://github.com/MAustinMMDP/webstorm-live-templates). 

I am using ui-router for my [Web Brownie App] (https://github.com/MAustinMMDP/web-brownie) but it does not currently match best practice based on the angular-styleguide; I am still working on defining each route in the module where they exist.

Anywho, hope this helps. It's a start. Feel free to contribute to the [repo] (https://github.com/MAustinMMDP/webstorm-live-templates). It may not make it into the angular-styleguide, as this will ultimately need to be approved by @johnpapa, but I can include it as a general resource.

**Comment by MAustinMMDP** [comment]
I am not a Java fan so I decided to go with the native .xml file type, which can be found [here] (https://github.com/MAustinMMDP/webstorm-live-templates/blob/master/angular/webstorm-angular-live-templates.xml). The [README] (https://github.com/MAustinMMDP/webstorm-live-templates/blob/master/README.md) has been edited to include installation instructions with a link to WebStorm help in regards to locating the project and IDE settings. @johnpapa let me know if you would like me to PR the new format otherwise feel free to link to the repo unless you can find someone who can save it to an .jar executable file.

**Comment by MAustinMMDP** [comment]
I have submitted the PR for approval and have updated my personal [webstorm live templates repo](https://github.com/MAustinMMDP/webstorm-live-templates) with the .xml files and installation info in the README. Feel free to communicate with me there if you have code samples you would like translated into a live template.

**Comment by EskoCruz** [comment]
This is great! I was wondering why there wasn't a simple directives snippit for WebStorm like there is for Sublime... I didn't know it was cause no one has done it yet. Great work @MAustinMMDP!

**Comment by MAustinMMDP** [comment]
Thanks @EskoCruz. Feel free to contribute to the repo. My plan is to add a JavaScript, LESS, SASS and HTML folder to the repo.
