### ISSUE TITLE
Prevent double curly brace notation from displaying momentarily before angular.js compiles/interpolates document

### ISSUE THREAD

**Issue by lucianosousa** [johnpapa/angular-styleguide#535]
I'm not a angular specialist. I was looking to something to prevent show these curly brace notation before the template was load and I really suggest you guys put this here as a styleguide.

I found cool responses here: http://stackoverflow.com/questions/12866447/prevent-double-curly-brace-notation-from-displaying-momentarily-before-angular-j

Which one should be the proper way to solve this?
- ng-cloack (also set .ng-cloak { display:none; } )
- use ng-bind

**Comment by MarcLoupias** [comment]
[ng-cloak] (https://docs.angularjs.org/api/ng/directive/ngCloak)
