### ISSUE TITLE
Broadcasts in controllers (Y031)

### ISSUE THREAD

**Issue by sebastianhaas** [johnpapa/angular-styleguide#541]
Hey! I'm having some trouble understanding the following sentence from [Y031](https://github.com/johnpapa/angular-styleguide#style-y031):
> Consider using `$scope` in a controller only when needed. For example when publishing and subscribing events using `$emit`, `$broadcast`, or `$on` consider moving these uses to a factory and invoke from the controller. 

While the _Why?_ is perfectly clear to me, I'm somehow missing the answer to this very specific issue. How do I move a possible event registration, e.g. `$scope.$on()` to a factory? Can somebody provide some code for demonstration?

However I do understand that it is possible to avoid broadcasts _at all_ with the use of factories. Is that the proposition of the above sentence?

**Comment by sebastianhaas** [comment]
I just realized that there is already an Issue opened on that topic #398 that I must have overlooked at first. I will move my question there.

**Comment by sebastianhaas** [comment]
Since there was no response in the other ticket I'll reopen this.

**Comment by johnpapa** [comment]
just closed this in #398

**Comment by sebastianhaas** [comment]
Thank you. I find that section much clearer now.
