### ISSUE TITLE
Run blocks with http requests and testing

### ISSUE THREAD

**Issue by lunks** [johnpapa/angular-styleguide#542]
Hi, I'm working on a legacy angular app that had the following in an `ApplicationController` that is used to tie-in a few things the app needs. An specific part was fetching the logged in user with a factory called `SessionManager` function `fetchUser()` which queries the backend-server for the current logged-in user, and stores it for later use.

My understanding is that this kind of thing should belong to a `run` block in the `core` module instead, following the guide (feel free to correct me in this one if I'm wrong). But this led me into having all tests break because it's trying to hit the backend server for every test. I'm not sure how to follow and this is an example on where the examples fall short.

What do to in these cases? Is my assumption that this should go into a `run` block wrong? Should I setup this stub on `$http` for all specs?

**Comment by johnpapa** [comment]
i try to avoid run blocks as they are hard to test.

Auth should already be done by the time the angular app kicks up. Take a look at Troy Hunts Angular Security course at PLuralsight for details

**Comment by lunks** [comment]
Thanks, @johnpapa, I'll take a look at it.

Just for reference, the mentioned course is this one: http://www.pluralsight.com/courses/angularjs-security-fundamentals
