### ISSUE TITLE
[Style Y033]

### ISSUE THREAD

**Issue by INGCRENGIFO** [johnpapa/angular-styleguide#547]
Hi, I'm using the style guide but gives me a warning to follow this style.

function SolicitudController(accesoService, notificaService, solicitudService,$routeParams, $q){
      /* jshint validthis: true */
      var vm = this;

      vm.addTrayecto = addTrayecto;
      vm.Registrar = Registrar;
      vm.ConsultaPermanencia = ConsultaPermanencia;
      vm.liquidaViaje = LiquidaViaje;
      vm.borrarDesp = BorrarDesp;

in doing so, the editor displays an alert indicating me

![solicitud](https://cloud.githubusercontent.com/assets/12200313/10165159/5656cd5a-6683-11e5-9fc7-b6dbbf5e892c.png)

**Comment by bampakoa** [comment]
I think it has something to do with the JSHint rules. Did you use the proposed one from the guidelines?

**Comment by johnpapa** [comment]
you want `latedef` for functions

**Comment by INGCRENGIFO** [comment]
@bampakoa I'm using the editor "atom" and a plugin called linter which use jshint, I must change something ??

**Comment by bampakoa** [comment]
Sorry @INGCRENGIFO . I am not aware of this plugin. Nevertheless, I guess you should search for a file that defines jshint rules and change **latedef** property to **nofunc** as stated from @johnpapa in [this](https://github.com/johnpapa/angular-styleguide#js-hint) section of the guideline.

**Comment by INGCRENGIFO** [comment]
@johnpapa that can be changed in the editor ?, I want to work according to your guide

**Comment by INGCRENGIFO** [comment]
@bampakoa you mean to create something with the code [Style Y230]?

**Comment by bampakoa** [comment]
Yes something like that.

**Comment by INGCRENGIFO** [comment]
Perfect, add this file mensionan and the "latedef" property "nofunc".

Fixed all, Thank you @bampakoa @johnpapa

**Comment by INGCRENGIFO** [comment]
@bampakoa and @johnpapa I totalSum new function (vm.conceptos);

but now he tells me quite "new", now when off "new" tells me to add. which of the two warnings should I accept it?

**Comment by bampakoa** [comment]
@INGCRENGIFO Can you give some more details?

**Comment by INGCRENGIFO** [comment]
Hello @bampakoa , this is the image
![atom](https://cloud.githubusercontent.com/assets/12200313/10193383/5391a020-6748-11e5-8cf0-14c2439b5c0a.png)

I'm already using jshint of the guide, but if I remove "new" gives me a warning and if I leave gives me another warning, in the image are 2 warnings.

**Comment by bampakoa** [comment]
I think your new statement should be something like:

     var SumaTotal = new SumaTotal(vm.conceptos);

**Comment by zachlysobey** [comment]
naming conventions suggest constructor functions should be named with a
Capital letter, but instances, and regular variables, etc... start with
lower case. This would make Aristeidis's suggested code look more like this:

var sumaTotal = new SumaTotal(vm.conceptos);
If the purpose of `SumaTotal` is not to be a constructor (not built to
be used with `new`, then that function should be named with a
lowercase 'S'.

If SumaTotal is a constructor, but you don't need to save a reference
to the instance you create with `new`, then this is a code smell:
(you're essentially using it for its side effects.)

**Comment by johnpapa** [comment]
closing due to not part of the style guide.

**Comment by INGCRENGIFO** [comment]
thank you @zachlysobey indeed it is what you indicate, the rationale of "totalSum is score a catidad value and return it, try var sum = new totalSum (xxx) but not worked for me, then switch to var sum = totalSum (xxx) and I return the expected result did not give me jshint additional errors. Thank you for your help.
