### ISSUE TITLE
index.html conflicts when on multi person projects.

### ISSUE THREAD

**Issue by dotsonjb14** [johnpapa/angular-styleguide#548]
When on teams with multiple people, the automatic generation of the index.html always leeds to conflicts.

This can be solved by moving the base index.html into another file, and using gulp to make a copy of that file to index.html prior to doing the transformations.

When doing that, if you add index.html to the .gitignore file there will be longer be merge conflicts.

**Comment by zachlysobey** [comment]
I don't believe that this style-guide (nor anywhere else that I've seen) recommends automatic generation of `index.html`. Is this a common practice? Or a relevant discussion here?

**Comment by zachlysobey** [comment]
As a general rule, generated code should *not* be put in version control.

**Comment by johnpapa** [comment]
not really applicable to ng style guide
