### ISSUE TITLE
JavaScript Closures aka IIFE?

### ISSUE THREAD

**Issue by MAustinMMDP** [johnpapa/angular-styleguide#550]
I noticed Style [Y010](https://github.com/johnpapa/angular-styleguide#style-y010) advocates an IIFE format of ```(function() { / code */ })();```, however, Crockford suggests the format ```(function () { /* code / }());``` in the following video. Is there a reason why we have not adopted his version? If so, can someone explain?

[![ScreenShot](http://i1.ytimg.com/vi/eGArABpLy0k/0.jpg)](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=7&cad=rja&uact=8&ved=0CEgQtwIwBmoVChMI9ey99PSfyAIVDpaICh3CKQHq&url=http%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DeGArABpLy0k&usg=AFQjCNFoZsKF1SY8tcZPHiXv3AzAZoVmog&sig2=rgYkAqk98yxDJMGWPTiBgQ)

**Comment by johnpapa** [comment]
was just my preference. note that what i show is not what Douglas shows in his screen cap, tho

**Comment by MAustinMMDP** [comment]
Got it. The screen shot is not showing the end result of the format he suggests; I just grabbed it from the beginning of the video. You can click the image to play the video. It is short and kinda fun in a nerdy way ;)

**Comment by dietergeerts** [comment]
imo `(function () {})();` is clearer than `(function () {}());` because you 'take' the function `(...)` and execute it `(.....)()`

**Comment by Jandalf** [comment]
I would stick with `(function () {}());` because JSLint, JSHint and ESLint suggest this as default for their rules regarding parenthesis in IIFE

https://jslinterrors.com/move-the-invocation-into-the-parens-that-contain-the-function
https://github.com/eslint/eslint/blob/master/docs/rules/wrap-iife.md

**Comment by johnpapa** [comment]
This has been beaten to death a few times. Appreciate the chat, but it's staying as is
