### ISSUE TITLE
Best way to implement thin controllers

### ISSUE THREAD

**Issue by jforjava1981** [johnpapa/angular-styleguide#551]
In reference with and continuation of question/issue #524 ,   
what is the generic and best alternative to implement thin controllers. We are facing issues where controller constructor functions get too bulky and lengthy as we go on adding functions to this.even for pages where we have not more than 10 fields?

**Comment by johnpapa** [comment]
maybe an example will help

i try to keep ctor's dead simple

**Comment by jforjava1981** [comment]
An Example is where we have form with 6/7 fields and add and edit functionalities are handled in same controller and we handle specific add/edit cases using a flag called addMode. Now whatever logic is there except bringing data from back end we add to controller. and all this logic is encapsulated in multiple functions in controller. Once we bring the data from back end all the data manipulation happens in controller. Also we have just single controller for whole page. could that be an issue? (where we should break views/templates with multiple controllers)?                                                                                                                   If you want some code will try to post this here on Monday as we have long weekend starting today and code is on my office repo.

**Comment by zachlysobey** [comment]
> "we have just single controller for whole page"

Hard to offer much advice without seeing the code, but it sounds like you might want to create "component" ("element") directives to break your page down into chunks, with their own scopes and controllers. Logic should be separated out into Services, and the directives' controllers act mostly as the 'glue' to attach things to that directives scope.

On the (large) projects I've worked on, the vast majority of controller logic is in individual directives' controllers, each of which is generally <20 lines of code. @johnpapa's example projects should be a good template for creating similarly modularized projects.

**Comment by MarcLoupias** [comment]
Follow theses rules :
1. controller role should be only to publish model to the view.
2. delegate model to dedicated services.
3. delegate logic (even UI logic) to dedicated services.
4. avoid as much as possible usage of $rootScope and $scope in controllers.
5. split your template in directives.
6. use services to share data between components (with model dedicated services or specific services for special cases)
7. use controllerAs syntax

Finally, your controllers code shoud be something like that : 

```javascript
/**
 * @ngInject
 */
function ExampleController(modelService) {
  var vm = this;
  vm.data = modelService.data;
  // or : vm.modelServiceInstance = modelService; then in your view do ctrl.modelServiceInstance.data 

  init();

  function init() {
    modelService.getData();
  }
}
```

This pattern allow data sharing between views.

You can also resolve the getData() promise in the controller and publish in the view : 

```javascript
/**
 * @ngInject
 */
function ExampleController(modelService) {
  var vm = this;
  
  init();

  function init() {
    modelService.getData().then(function (data) {
      vm.data = data;
    });
  }
}
```

**Comment by dietergeerts** [comment]
@MarcLoupias 

> 1. controller role should be only to publish model to the view.

A controller may also hold some additional stuff that you can't put in your view, for example, I had to translate a parameter which is used in a filter. In Angular, you can't use a filter in a filter, so I had to put a function on the controller that will translate the value before it can be used in the filter.

A controller is a VIEWMODEL, so it's role is more than just publishing the model to the view imo. A viewmodel can contain logic for the view.

> 2. delegate model to dedicated services.

Models should always come from services, but you can always change your models in your view/controllers.

> 3. delegate logic (even UI logic) to dedicated services.

UI logic should never be in services, UI logic belongs to the UI, either in the html, the controller or in directives. Or you mean something different here than what I see in UI logic.

> 4. avoid as much as possible usage of $rootScope and $scope in controllers.

Correct. Just never use them in your controllers, and if you do, have a damn good reason and put it into a comment, so others also know why.

> 5. split your template in directives.

Split? I think you mean to use directives in your template. Don't make directives just to split your template imo.

**Comment by MarcLoupias** [comment]
> A controller may also hold some additional stuff that you can't put in your view, for example, I had to translate a parameter which is used in a filter. In Angular, you can't use a filter in a filter, so I had to put a function on the controller that will translate the value before it can be used in the filter.

If you have a piece of logic, put it in a service and inject it where it is needed.
If you need de work on the filter args work in the filter through a service instead of outside in the controller.

> A controller is a VIEWMODEL, so it's role is more than just publishing the model to the view imo. A viewmodel can contain logic for the view.

By model i mean **business model**. The model in a controller is the view model, not the business model. It is not the same. The model usage in the controller is limited to his own scope (not reusable outside by itself).

Every piece of logic should go in a service, no matter the logic purpose. Easier de test, easier to share, easier to maintain.

> UI logic should never be in services, UI logic belongs to the UI, either in the html, the controller or in directives. Or you mean something different here than what I see in UI logic.

I strongly disagree on this cf upper. Logic should go to service, no matter the logic purpose.

> Split? I think you mean to use directives in your template. Don't make directives just to split your template imo.

Yes, i mean *think component*. It is impossible to write a html for a single page with everything in it withtout the possibility to cut & paste some pieces into some directives.

**Comment by jforjava1981** [comment]
I am still reading all the resources possible including this issue. We are also brainstorming within ourselves. Right now we are trying approach suggested  by @MarcLoupias. But would like to more comments on this issue to get alternatives and best patterns possible.

**Comment by jforjava1981** [comment]
And coming from Java background I want to know how I will distinguish between ViewModel (maybe DTOs in java) and Models (Business or Value Objects in java) and where I can put logic which handles both these models. I am sure business models must be handled in services and controllers should not know anything about them. So services will convert(compose,aggregate) the model object into respective viewModel objects.  But if I start writing methods which manipulate the viewModel objects returned from services (for example ngClick invokes a method on controller and that method manipulates multiple viewModel objects)  in controllers , the controllers  themselves start bulging up. and thats where I face a question for which this issues is created. Now what we have done is we have created separate factories to hold such logic but still not sure if there is a better and correct way. As the factories will also get bigger.

**Comment by MarcLoupias** [comment]
[This article] (http://toddmotto.com/rethinking-angular-js-controllers/) should help you. IMO it is a must read for Angular Controllers.

**Comment by johnpapa** [comment]
good ideas. i am closing for now, but if someone has a PR suggestion , please fire away
