### ISSUE TITLE
JSHint warns with W026 when returning directive object before declaring linkFn

### ISSUE THREAD

**Issue by yesobo** [johnpapa/angular-styleguide#552]
The examples for Style Y074, returns the directive object before linkFn function declaration. ¿Would'nt it be better returning the directive object at the end of the directive declaration?

**Comment by zachlysobey** [comment]
I personally like it as is, and don't see much benefit to burying the
return below the link function.
In any case, its clear that this is Jon's preference, and unlikely to
change at this point in the style-guide's maturity

Zach Lysobey
(203) 984-4048

**Comment by zachlysobey** [comment]
Also, I can't confirm as I use ESLint, but I'm confident that if you use the JSHint settings recommended in this guide you will not get any warning with this style.

**Comment by stramel** [comment]
I believe that is a Crockford style preference that all functions must be declared before they are used to avoid the possibility of the function not being defined at the time of use. (http://stackoverflow.com/questions/7609276/javascript-function-order-why-does-it-matter#answer-7610883)

**Comment by yesobo** [comment]
I'm using JSHint settings provided in the JSHint section of this guide and they would need to add the ignore warning property;

"-W026": true

in the .jshintrc file to pass the linting. In return we wouln't be warned.

Do you prefer not to be warned and follow the style guide as is? I personally do, so I would fix the provided JSHint.

**Comment by MAustinMMDP** [comment]
I agree with @stramel and prefer to declare functions before they are used to be consistent with [Crockford](http://javascript.crockford.com/code.html).

**Comment by johnpapa** [comment]
Good discussion. If someone has a PR to make, please fire away
