### ISSUE TITLE
Data service with catch and reject example

### ISSUE THREAD

**Issue by styxiak** [johnpapa/angular-styleguide#555]
Hi,
I would like to see best practices for data service with `catch()` (update example in https://github.com/johnpapa/angular-styleguide#style-y061). 
For example when data.service get http status code other than 200 I would like to show message for user. But if it is 200 service usually do some validation etc, and return status code for operation like `{status: 'OK', data: ...}` or `{status: 'DUPLICATE_SOMETHING', data: null}`. In this case I would like also show message for user. Where is best place to put `catch()`, `$q.reject()` etc.

**Comment by bampakoa** [comment]
@styxiak the best place to do it is in a service file that will be in the same folder as your controller. In that file you will create your factory that will resolve the promise and return an object like `{status: 'DUPLICATE_SOMETHING', data: null}` or reject it and show the message to the user.

Personally, for logging, I use **logger** block factory as stated in the [modular](https://github.com/johnpapa/ng-demos/blob/master/modular/src/client/app/blocks/logger/logger.js) demo of @johnpapa that logs and notifies the user.

**Comment by styxiak** [comment]
And the same with http errors like 404? Convert them in this service to similiar object like `{status: HTTP_404, data: null}`? I do this this way already.

**Comment by bampakoa** [comment]
Yes, that's right.
