### ISSUE TITLE
Add note for function declaration/ordering when using CoffeeScript

### ISSUE THREAD

**Issue by SimplGy** [johnpapa/angular-styleguide#557]
Lots of these tips are usefully generic and would apply equally in JS, CoffeeScript, TypeScript. One in particular I can't do it in CoffeeScript, but want to.

It's not my intent to start a precompile-or-no dogma discussion, hopefully we can avoid that.

Coffeescript [doesn't have function declarations](https://github.com/jashkenas/coffeescript/issues/1640). This is not likely to change. Intended to avoid hoisting and unify function definition, It makes [Bindable Members Up Top](https://github.com/johnpapa/angular-styleguide#bindable-members-up-top) difficult to implement.

There are a few options. Sometimes we expose all public methods at the bottom in a single hash:

```coffee
    return api =
      setThis: setThis
      getThat: getThat
```

This is ok, but it's at the bottom of the file, so it doesn't have the immediate discoverability of your style :(

We also sometimes put everything inside methods and call an `init` at the bottom, again just to handle declaration order.

```coffee
    vm = this
    init = ->
      vm.getThis = getThis
      vm.setThat = setThat
    getThis = ->
    setThat = ->
    #...
    init()
    return vm # avoid implicit return issues
```

So, no particular problem, but I like the style guide and wonder if a note for CS is warranted, and if anyone has some nice ideas on an alternative to hoisted function declarations.

Thanks for reading.

**Comment by MAustinMMDP** [comment]
imo this would be a great topic for stackoverflow

**Comment by SimplGy** [comment]
My experience with Stacko is they are getting to be less and less interested in subjectiveish questions. If you guys aren't interested in CS though, I totally understand. Feel free to close.

I also have to rephrase the problem statement to be more specific and accurate--the variable definition is actually available in the scope because `var` declaration gets hoisted in CS, it's just the function definition that isn't available so you can't call it until that LOC is reached. I'm playing around with it now, maybe I'll come up with something interesting.

**Comment by johnpapa** [comment]
thanks, but not ideal for the guide
