### ISSUE TITLE
Specifying Dependencies without array notation would create global variables

### ISSUE THREAD

**Issue by mickeypuri** [johnpapa/angular-styleguide#558]
Y091: The suggested approach of Manually Identifying Dependencies is great, however the recommended implementation method would end up creating functions in the Global Scope. You could avoid this by using immediately invoked functions, but then this runs the risk that the dependencies to be injected are  themselves not yet instantiated.

The minsafe array syntax avoids creating a new function within the global context, hence personally would recommend it.

**Comment by zachlysobey** [comment]
Check out [Y010](https://github.com/johnpapa/angular-styleguide#style-y010):

> Wrap Angular components in an Immediately Invoked Function Expression (IIFE)

> Note: For brevity only, the rest of the examples in this guide may omit the IIFE syntax.

**Comment by mickeypuri** [comment]
@zachlysobey  I had mentioned about the IIFE, however I had assumed that all dependencies had to be themselves defined before we could mention them in an IIFE. However have just tested and found that assumption is not right, and angular will instantiate them in the correct sequence. 

So will close this issue.
