### ISSUE TITLE
Please provide an example using UI-Router in separate modules as recommended in Styles Y270 and Y271

### ISSUE THREAD

**Issue by dkromp** [johnpapa/angular-styleguide#565]
Can you provide an example of how to use UI-Router's $stateProvider to set up my states in multiple modules?

Per Style Y270 and Style Y271, you recommend using UI-Router and defining routes for views in the module where they exist, however UI-Router's FAQ doesn't do a very good job of explaining how this can be accomplished and the majority of examples provided show $stateProvider defining states in the main app's module's config as shown in the following example.

(function () {
	'use strict';
angular.module('app').config(stateConfig)

function stateConfig($stateProvider, $urlRouterProvider){
   $urlRouterProvider.otherwise('/home');

  $stateProvider.state('primary' {
      url: '/primary', 
      template: '/primary.html'
  })

  $stateProvider.state('secondary' {
      url: '/secondary', 
      template: '/secondary.html'
  })
}
})();

**Comment by bampakoa** [comment]
**primary.routes.js**

    (function() {
       'use strict';

       angular
        .module('app.primary')
        .config(stateConfig);

       function stateConfig($stateProvider){
          $stateProvider.state('primary' {
            url: '/primary', 
            template: '/primary.html'
         })
    })();
**secondary.routes.js**

     (function() {
        'use strict';
           
        angular
          .module('app.secondary')
          .config(stateConfig);

       function stateConfig($stateProvider){
          $stateProvider.state('secondary' {
            url: '/secondary', 
            template: '/secondary.html'
         })
    })();
**core.routes.js**

     (function() {
       'use strict';

       angular
         .module('app')
         .config(stateConfig);

       function stateConfig($urlRouterProvider){
          $urlRouterProvider.otherwise('/home');
    })();

**Comment by dkromp** [comment]
What version of UI router does this work with? I am using "version": "0.2.15" and the provided solution isn't working. Can you please provide a working plunkr?

**Comment by bampakoa** [comment]
What do you mean "isn't working"? Do you get an error in the console or does the change of state not responding at all?

**Comment by dkromp** [comment]
No error in the console, the change of state is not responding.

**Comment by dkromp** [comment]
Maybe i need to have an updated version of UI-router? With #492 merged (v0.2.8)... https://github.com/angular-ui/ui-router/wiki/Frequently-Asked-Questions#how-to-configure-ui-router-from-multiple-modules

**Comment by dkromp** [comment]
My mistake! My closures weren't structured properly. Thanks for the soluiton.

**Comment by cariquitanmac** [comment]
If anyone still having a hard time finding this implementation like me.
There is a separate repo for this created by @johnpapa 
[johnpapa/gulp-patterns](https://github.com/johnpapa/gulp-patterns/blob/master/src/client/app/blocks/router/router-helper.provider.js)
