### ISSUE TITLE
Y038 - Assigning Controllers

### ISSUE THREAD

**Issue by bampakoa** [johnpapa/angular-styleguide#567]
Hi,

The guide mentions in [Y038](https://github.com/johnpapa/angular-styleguide#style-y038)

    Note: If a View is loaded via another means besides a route, then use the
    ng-controller="Avengers as vm"  syntax.

Is this valid also for showing dialogs/modals (e.g. [$mdDialog](https://material.angularjs.org/0.11.4/api/service/$mdDialog) from Angular Material) ?

Thanks

**Comment by brantphoto** [comment]
@bampakoa As far a I know you would just list your controller as in the config object of the show method. Angular material takes care of it for you, similar to a route. 

```
$mdDialog.show({
      controller: 'sampleController as vm'
   });
```

**Comment by bampakoa** [comment]
@brantphoto thank you for your answer. 

My question concerns specifically if the above style should apply for modals. That is, which method is better: Use **controllerAs** in the config object of the dialog or declare it in the partial html as `ng-controller="Avengers as vm"`?

**Comment by dietergeerts** [comment]
@bampakoa , having it in the config object makes your template and controller more loosly coupled and interchangeable, like you can then have two controllers for the same template, or the other way around. For modals, that's something that can happen a lot, the same template, but with different controllers....

**Comment by bampakoa** [comment]
Thank you for your suggestions!
