### ISSUE TITLE
Question: Passing in 'angular'

### ISSUE THREAD

**Issue by spongessuck** [johnpapa/angular-styleguide#572]
Do you recommend always setting 'angular' as a global in your linter? None of your examples pass angular in as a parameter:
```javascript
(function() {
    angular.module(..., [])    // Linter complains if 'angular' not configured as global
})();
```

I guess the problem would be that you'd need to reference 'window' when you passed it in or you'd just be moving the warning:
```javascript
(function(angular) {
    ....
})(window.angular);
```

**Comment by zachlysobey** [comment]
At the risk of speaking for John... •yes*.  None of his examples pass angular into the IIFE's, and the linter config has it as global.

I personally don't see much benefit to passing it in, and this would create quite a bit of boilerplate.

**Comment by spongessuck** [comment]
> ...this would create quite a bit of boilerplate...

Seems reason enough to avoid it considering it's only a validation problem. It's easy enough to have it in one place (linter config) than in every module/controller/etc. you write.
