### ISSUE TITLE
Why is $inject not working

### ISSUE THREAD

**Issue by MalleusMalefic** [johnpapa/angular-styleguide#575]
This is my first time trying to build an app in accordance to this style guide but I'm having a problem with my dependencies.

Here is my app:
```javascript
(function() {
    'use strict';
    angular
        .module('app', ['dndLists']);
})();
```
And my controller:
```javascript
(function() {
    'use strict';

    angular
        .module('app')
        .controller('TheThing', TheThing);

    TheThing.$inject = ['dndLists'];

    function TheThing(dndLists) {
        var vm = this;
        vm.title = 'Here\'s A Thing';
    }
})();
```
This doesn't give me any grief with the app itself (telling me have all the JS in there the right way) but the controller always barfs out an [$injector:unpr] error. Also, I have tried this with other plugins besides this angular-drag-and-drop-lists that I show here but to no avail.

Any help would be much appreciated.

**Comment by dennismohan** [comment]
It looks like you are trying to inject a module into the controller. I'm not sure if that is actually supposed to work, however given that you are getting an $injector error that means the inject is actually firing. Try passing in something like service.

**Comment by MalleusMalefic** [comment]
OF COURSE!!! Yeah, totally brain farted on that one. Thanks for setting me straight :-)
