### ISSUE TITLE
Recommendations for including all .js files for an app

### ISSUE THREAD

**Issue by bernfarr** [johnpapa/angular-styleguide#578]
Thanks for a most useful style guide. When I first read it I learned a good deal about Angular, I'm still learning.

The recommendation that each definition (controller, service, factory, etc.) be in it's own file makes a lot of sense. This also means that a _lot_ of .js files need to be included in ````index.html```` as the app grows.

Can you suggest or recommend a way to solve this problem -- that is maintaining ````index.html```` easily? I know we can use tools like grunt and RequireJS, but is there another way to get around this issue?

**Comment by kylecordes** [comment]
In the style guide, John recommends using gulp or grunt for a build process; there are plug-ins available for either of those that can automate finding all of your JavaScript files and including them in your HTML, typically by concatenating them together. But as of late 2015, that approach is feeling rather long in the tooth, and I think something like webpack is a more suitable current solution. Non-module-based JavaScript development feels nearly obsolete, at least for a fresh new project.

**Comment by HamburgerTS** [comment]
I'm too still learning and stumbled over this very question today as well. 

As far as I understand, you bundle all the js files into a single one (at least for production)(?).

See here (line 61):
https://github.com/johnpapa/ng-demos/blob/master/modular/gulpfile.js

The author also injects all the js files into the index.html (I guess this is what kylecordes mentioned). 

See here (line 163):
https://github.com/johnpapa/ng-demos/blob/master/modular/gulpfile.js

Don't undertand why not just use the "all.min.js" generated by task 'js' but I'm also just a beginner.

**Comment by bensinther** [comment]
@HamburgerTS just FYI - you can click into the Line or append '#L<line-number>' to directly link to a specific line.
Example: 
https://github.com/johnpapa/ng-demos/blob/master/modular/gulpfile.js#L163

**Comment by HamburgerTS** [comment]
@bensinther nice! Thanks for letting me know!

**Comment by richfergus** [comment]
enumerating the js functionality but dividing the file structure for "readability" is a core design pattern. But @bernfarr, it can be a pain.... IMHO

**Comment by johnpapa** [comment]
Gulp is fantastic for this. Check out `yo hottowel` for a sample gulp file.

webpack can help, but i prefer the customization of gulp over the config of webpack.
