### ISSUE TITLE
How to use controllerAs from a directive

### ISSUE THREAD

**Issue by johnpapa** [johnpapa/angular-styleguide#58]
http://stackoverflow.com/questions/25266555/using-this-instead-of-scope-with-angularjs-controllers-and-directives

**Comment by brutalcrozt** [comment]
sir i want to follow your suggention as well, but can you give me some advice?
i write a directive and i create inside it, i want use that controller as well on the directive template but, i got error when use ng-swicth. so i write the additional code controllerAs as well, but it not solve mine
