### ISSUE TITLE
Step-by-Step App Setup

### ISSUE THREAD

**Issue by dkromp** [johnpapa/angular-styleguide#583]
Hi, as an enhancement to your existing style guide, I recommend putting together a complimentary step-by-step guide that can instill some of these best practices in a newbie. This tutorial would be particularly useful for taking care of the behind-the-scenes tasks that are required to write clean, well commented code (i.e. configuring gulp to assist minification, getting jsdoc set up, etc.)

**Comment by johnpapa** [comment]
yo hottowel

**Comment by dkromp** [comment]
Well said - just now stumbling upon this. Thx John.
