### ISSUE TITLE
Controller per view or as entity?

### ISSUE THREAD

**Issue by feniixx** [johnpapa/angular-styleguide#585]
This is a question:

I've been thinking about the concept of controller in the MV* pattern, but there's something i would like to discuss, should we create a controller per view when using angular (since angular follows the singleton concept) or is it right to have a controller for all the views related to "products" for example?

I'll give a situation:

Let's say we have a module called ```purchases``` and under that module we've got three submodules: ```products```, ```suppliers```, & ```stock-moves```, each submodule has views for the CRUD operations, let's say that under products we have: ```list-products.view.html```, ```create-product.view.html```, ```edit-product.view.html```; what would be the best approach for the controllers? a single controller per view, or a controller for all views?

**Comment by HamburgerTS** [comment]
The way I understand it, you define one controller for each of your views:

- Define a controller for a view, and try not to reuse the controller for other views. 
https://github.com/johnpapa/angular-styleguide#style-y037

- The exampel application structure looks like this:

```
attendees.html <- View 1 
attendees.controller.js <- Dedicated controller for view 1
people.routes.js
speakers.html <- View 2
speakers.controller.js <- Dedicated controller for view 2
speaker-detail.html <- View 3
speaker-detail.controller.js <- Dedicated controller for view 3 
```
https://github.com/johnpapa/angular-styleguide#style-y152

**Comment by feniixx** [comment]
Retaking the example i posted, what you mean @HamburgerTS  is that i should  create three controllers: ```list-products.controller.js```,```create-product.controller.js``` & ```edit-product.controller.js```?

I read somewhere that controllers are things, nouns, not verbs... so having controllers like: CreateProductController, EditProductController... is not good practice, is that true?

**Comment by dietergeerts** [comment]
@feniixx, Why would you need to have a controller for each action? The controller (I rather called it ViewModel) just holds the data for the view, and will redirect all actions to model services. So for create and edit, you could use a productcontroller, where the products get loaded in, of course in case of the create case, you'll load a new model with default values.

**Comment by dietergeerts** [comment]
@HamburgerTS , imo, controllers can be reused, so do views, but you just have to make them focused on one thing, that doesn't mean on view. One thing can just be that a controller is for doing actions on one product. You can then reuse this controller for edit, create, even showing it in a list....

**Comment by dietergeerts** [comment]
@feniixx , just look at a controller as a ViewModel, which holds ViewModel related logic, and nothing else.

**Comment by feniixx** [comment]
@danmindru That's what i was thinking, but i don't want too complex controllers either, but services might be the solution. Just want to hear some other opinions to close this...

**Comment by HamburgerTS** [comment]
@dietergeerts 
> imo, controllers can be reused, so do views

According to [Y037](https://github.com/johnpapa/angular-styleguide#style-y037), you should not. If you reuse a combination of visible html and a controller, wouldn't that rather be a directive which you then use in multiple (not reused) dedicated views?

**Comment by HamburgerTS** [comment]
@feniixx, 
> what you mean @HamburgerTS is that i should create three controllers

yes, this is how I understand (and implement) it.

IF you want to have these three views. The thing is: One controller per view. You could of course decide to have e.g. two views: "list" and "details" where "details" controller cover the complete CRUDE functionality (view related).

Then you would have two controllers. 

As @feniixx already noted, you put every shared functionality (CRUDE for your product) into e.g. a product.service.js which is then injected into each of your controllers.

Your controllers could then only concern "How do I make a product accessible (read and write) for my user?" (E.g. request single / multiple product(s) from service, react on input from user, provide save / details / delete button (and delegate persisting of the new / updated product to your product.service.js) etc.)

**Comment by MarcLoupias** [comment]
@HamburgerTS 
Furthermore, the controller is the view/scope constructor. The controller core responsability is to initialize the view and publish the data.

So i agree with you. If uou have to reuse a template you should create at least one directive. But a view should remain unique, and the associated controller too.

**Comment by feniixx** [comment]
I'm confused, if i a controller must be unique per view, then what should i name the CRUD Operations Views like ```create-product.view.html```... @MarcLoupias & @HamburgerTS ?

**Comment by HamburgerTS** [comment]
@feniixx 

> Controllers are things, nouns, not verbs or actions,
> naming the a controller CreateProductController isn't good practice.

But the suggested naming convention is conform with this:

```
{noun}-{noun|verb}.html
{noun}-{noun|verb}.controller.js
{noun}.service.js
```
Like here (from [Y152](https://github.com/johnpapa/angular-styleguide#style-y152)):
```
speakers.html <- View 2
speakers.controller.js <- Dedicated controller for view 2
speaker-detail.html <- View 3
speaker-detail.controller.js <- Dedicated controller for view 3 
```

I don't see why 
```
product-create.controller.js
product-edit.controller.js
product-list.controller.js
```
or
```
products.controller.js <- list of products (-R--)
product-detail.controller.js <- single product (C-UD)
```
should not be ok...

**Comment by feniixx** [comment]
Well, you're right @HamburgerTS, thanks

**Comment by dietergeerts** [comment]
Maybe one more comment on this as food for thought: So you would make two controllers that do exactly the same for your edit and create view? Those can really have the same controller imo, they will just have another service or save delegate inserted to where the save call will go...
