### ISSUE TITLE
Laravel 5 + Front-end Johnpapa Angular Standards (styleguide)

### ISSUE THREAD

**Issue by aaesis** [johnpapa/angular-styleguide#596]
Hi I've been studying your angular-style, and I find it very interesting. Well on the documentation of your angular-styleguide has no enough demo or tutorials. I find it so hard to integrate it to my Laravel application. Do you have a sample and demo enough for me to start with? 

Im really want to learn your angular-styleguide. Very neat, clean and organize.

**Comment by zachlysobey** [comment]
Check the [yeoman generator](https://github.com/johnpapa/angular-styleguide#yeoman-generator) for a good template to start with.

[John's "Modular" example app](https://github.com/johnpapa/ng-demos/tree/master/modular) serves as a good example app for this styleguide in practice.

[John Papa's Pluralsight courses](http://app.pluralsight.com/author/john-papa) are excellent video tutorials covering these topics.

**Comment by johnpapa** [comment]
yep

**Comment by aaesis** [comment]
Thank you so much zachy and johnpapa.. Appreciate it so much..
