### ISSUE TITLE
Should we use `context` in our tests?

### ISSUE THREAD

**Issue by dezoxel** [johnpapa/angular-styleguide#603]
Hi,

Mocha testing framework has such great thing like `context`. From the docs:

> context() is just an alias for describe(), and behaves the same way; it just provides a way to keep tests easier to read and organized.

It was inherited from the Ruby world. Here is best practice link: http://betterspecs.org/#contexts

Unfortunately Jasmine framework doesn't have such method, but I believe it will be implemented soon.

What do you think about adding new rule "Use contexts" to the styleguide?

**Comment by johnpapa** [comment]
not sure it applies to angular styles. its a tip for sure, but this is not a perf, tips, or usage guide.

**Comment by dezoxel** [comment]
Yes, agree, it is not related to angular itself. But anyway you have a great tip about writing tests as a stories (https://github.com/johnpapa/angular-styleguide#write-tests-with-stories). This is not related to angular too. Nevertheless it would be nice to have much more tips about test topic. I wouldn't suggest to remove "test as stories" tip. Conversely, lets think about adding new tips.
