### ISSUE TITLE
Example application to use for code examples?

### ISSUE THREAD

**Issue by chanoch** [johnpapa/angular-styleguide#604]
Hi,

Is it worth adding an example application to use for examples? I see too many people using app (angular) or "starter" (ionic) and "myapp", which seems to go against the advice to come up with names. If you had an example application then you would have pretend scenarios to use in code examples. e.g. the prefix for directives, the names of the main and child modules. YO20.

Also, should there be advice against calling your module app, starter, or myapp?

I'm happy to create a pull request for this if desired. 

Chanoch

**Comment by johnpapa** [comment]
There is a link to the HotTowel generator to get started in this doc

**Comment by chanoch** [comment]
is recommended to always call the app module 'app' then or should it be called after the app ideally?

**Comment by FrancescoRizzi** [comment]
you know, I've been bugged by the use of the generic 'app' lately (in many projects and templates I've been looking at)... but:

* if all apps and modules use the same 'name' for their root package ('app') then they are easier to transfer/reuse
* apps don't seem to interact directly with other apps, so really you have only one 'app' in context at any given time

Just my $0.175

**Comment by dietergeerts** [comment]
Another advantage is that you can reuse your gulp build etc....
And you can make toolkits a la fabricator that contain modules for your app, which will be in the app module etc....
