### ISSUE TITLE
ES6 warning?

### ISSUE THREAD

**Issue by chanoch** [johnpapa/angular-styleguide#605]
Is it worth putting an EcmaScript paragraph at the top to say that this doesn't deal with Ecmascript? Except for a few warnings that the recommendations here will break in ES6, there's no real discussion of what a migration to ES6 might be, whether to be worried about the need to migrate in the future, etc. Also, is it worth pointing at a repo that deals with ES6?

**Comment by johnpapa** [comment]
Feel free to add something ... Not sure what "won't work" in ES6. Can you elaborate?

The only thing I can readily think of, is the same issue in TypeScript, and that is the functions won't be hoisted. So the registration of the controllers/directives/etc should be done at the bottom of the file for ES6 and TypeScript

**Comment by chanoch** [comment]
That's what I was referring to but wasn't sure how to explain.

Is there a way to write in a version agnostic way? I like the declarations at the top. Perhaps by nesting the controller with another function and calling it? Fairly new to JS/Angular - I've experimented but not sure what I'm doing e.g.

    (function() {
      var profileControllerFactory = profileControllerFactory();
     angular.module('app').controller('ProfileController', ['dependencies',controllerFactory.profileController]);

      function profileControllerFactory {
         this.profileController = function($scope, etc ...
    }
})();

but perhaps having the declarations at the top is not that important.

**Comment by zachlysobey** [comment]
I'm a bit confused by this.

Are you saying the following does not work in ES6?

```js
if (x) {
  f();
  function f() { doSomething() }
}
```

because I was pretty sure that it did...

**Comment by gkalpak** [comment]
What they meant to say is that class definitions won't be hoisted, so can't define them after registering them (e.g. as controllers, services etc).

Using functions will still work as expected.

**Comment by johnpapa** [comment]
It specifically is an issue when you use ES6/TS classes.
