### ISSUE TITLE
In Y121 and Y122 - added to explanation for spec naming convention?

### ISSUE THREAD

**Issue by chanoch** [johnpapa/angular-styleguide#606]
To make the angular style guide more accessible to relative beginners (like me), is it worth explainign the type of scenarios where it is necessary to quickly identify components - such as for identifying tests to run or to exclude test files from the production build task?

**Comment by MAustinMMDP** [comment]
I believe the whole purpose of Style Y121 & Y122 is to encourage you to "Use consistent names for all components following a pattern that describes the component's feature then (optionally) its type" in every scenario.

**Comment by johnpapa** [comment]
i think we're fine here. adding too much more gets pretty specific and may exclude cases too. its just a general guideline for being consistent as @MAustinMMDP states
