### ISSUE TITLE
Add note about multiple directives with isolated scope?

### ISSUE THREAD

**Issue by karlhorky** [johnpapa/angular-styleguide#608]
As noted in [my comment in #536](https://github.com/johnpapa/angular-styleguide/issues/536#issuecomment-161230305), multiple directives with isolated scopes cause `Multiple Directive Resource Contention` errors in Angular 1.2+ when applied to the same element. For instance:

```html
<input my-directive my-second-directive ng-model="title">
```

```js
angular.module('app', []).directive('myDirective', function () {
  return {
    restrict: 'A',
    scope: {}
  };
}).directive('mySecondDirective', function () {
  return {
    restrict: 'A',
    scope: {}
  };
});
```

[Demo on Plunker](http://plnkr.co/edit/b0zllng8micc0lTg8YmT?p=preview)

**Resulting error:**
https://docs.angularjs.org/error/$compile/multidir?p0=myDirective&p1=mySecondDirective&p2=new%2Fisolatedundefinedcope&p3=undefined

Should we add a note about this in the **Directives and ControllerAs** section? Or it's own section, with recommendations what to do?

**Comment by johnpapa** [comment]
This doesnt feel like a style guide thing to me ... it is important, but so is perf, security, tips and tricks, etc.

**Comment by karlhorky** [comment]
I would argue it is - the style guide is proposing a certain way of writing directives, which can lead to problems if used on the same element.

Even a small note would suffice:

**Heads up!** If you apply multiple directives with isolated scope to the same element, you will run into [Multiple Directive Resource Contention](https://docs.angularjs.org/error/$compile/multidir?p0=directiveOne&p1=&p2=directiveTwo&p3=&p4=new%2Fisolated%20scope&p5=) errors.
