### ISSUE TITLE
Why does hot towel use bower and node modules?

### ISSUE THREAD

**Issue by dkromp** [johnpapa/angular-styleguide#609]
Why not just use npm?

**Comment by zachlysobey** [comment]
The generator was built > 2 years ago, when bower was much more in vogue than it is now.

I'd personally prefer if it was *just* NPM as well

**Comment by dkromp** [comment]
So, the future is NPM... it would make sense then to modify the hot towel to move the dependencies over as node dependencies then and remove the bower references from the gulp and app config, yeah?

**Comment by johnpapa** [comment]
make a PR :)

as long as it works the same, wiredep functionality is replaced, etc. we can review it and see where it leads.

**Comment by dkromp** [comment]
cool -- some weekend homework ;)
