### ISSUE TITLE
Function Declarations to Hide Implementation Details on form ng-submit 

### ISSUE THREAD

**Issue by vazh** [johnpapa/angular-styleguide#610]
so i kind of new to angular, testing things out to work better.
and im following this guide,
but when i implement the section in the title, the ng-submit on a form doesnt work quite like i expected.

so my question is,

if i have something like this in a controller
````javascript
function Controller(){
    var vm = this;
    vm.login = login;

    function login(){
        /* block of code */
    }
}
````
and then inside a html
````html
<form ng-submit="vm.login">
    <!-- block of code -->
</form>
````
that kind of code inside ng-submit doest work, i have to change it into 
````html
<form ng-submit="vm.login()">
    <!-- block of code -->
</form>
````
to make it work.
does it actually work like that ? or did i missing something important ?

**Comment by bampakoa** [comment]
@vazh The correct use of controller methods in a template is using parentheses.

**Comment by zachlysobey** [comment]
yup. See the example in the documentation:

https://docs.angularjs.org/api/ng/directive/ngSubmit

**Comment by dietergeerts** [comment]
Login is a function. To call a function, you have to use parentheses. That's plain JavaScript.

**Comment by vazh** [comment]
my bad, i thought by following the styling i dont have to use the parentheses.

thanks a lot guys.

**Comment by zachlysobey** [comment]
@dietergeerts in his defense perhaps, this is not exactly plain JavaScript function invocation here. `ng-submit` (and other `&` bound properties) take an [angular 'expression'](https://docs.angularjs.org/guide/expression) which is a "JavaScript-like code snippet". Its a bit confusing for beginners and I've been caught up on this myself once or twice.
