### ISSUE TITLE
How to pass parameters to a router resolve function?

### ISSUE THREAD

**Issue by disnoa** [johnpapa/angular-styleguide#620]
I'm trying to apply the style **Manually Identify Route Resolver Dependencies** 
```javascript
/* recommended */
function config($routeProvider) {
    $routeProvider
        .when('/avengers', {
            templateUrl: 'avengers.html',
            controller: 'AvengersController',
            controllerAs: 'vm',
            resolve: {
                moviesPrepService: moviesPrepService
            }
        });
}

moviesPrepService.$inject = ['movieService'];
function moviesPrepService(movieService) {
    return movieService.getMovies();
}
```
but i need to pass parameter for moviesPrepService

```javascript
resolve: {
   moviesPrepService: moviesPrepService("parameter")
}
```
this gave me an ng:areq Bad Argument. So how can i do that?

**Comment by viniciuskneves** [comment]
> Use $inject to manually identify your route resolver dependencies for Angular components.

Your "parameter", also known as movieService is injected through moviesPrepService.$inject. So you don't need to call moviesPrerService("parameter")

Hope it helps :)

**Comment by disnoa** [comment]
Hmm I think I understand, but do not know how to apply it in my code

I have a function called LoadPlugin this requires an array with all jquery plugin that an specific route need

```javascript
.state('Example', {
    templateUrl: "path/example.html",
    resolve: {
        loadPlugin: function ($ocLazyLoad) {
            return $ocLazyLoad.load([
                {
                    files: ['path/chosen-spinner.css','path/chosen.min.css','path/chosen.jquery.min.js','path/chosen.js']
                }
            ]);
        }
    }
});
```
how can i apply *Manually Identify Route Resolver Dependencies* with this code?

```javascript
.state('routeExample', {
    templateUrl: "path/example.html",
    resolve: {
        loadPlugin: loadPlugin(
            [{files: ['path/chosen-spinner.css','path/chosen.min.css','path/chosen.jquery.min.js','path/chosen.js']}]
        );
    }
});
```

**Comment by viniciuskneves** [comment]
I don't know what your loadPlugin looks like but when it says **Dependencies** it meant services, factories or whatever Angular dependencies you might inject. As far as I understood it can't be applied to you example because your array of files won't be inject, it must be 'passed' as a param. In the other hand $ocLazyLoad can be inject in your function.

You would have something like:

```javascript
loadPlugin.$inject = ['$ocLazyLoad']
function loadPlugin($ocLazyLoad) {
var files = [file1.css, file2.css];
//do stuff with files
}


resolve: {
loadPlugin: loadPlugin
}
```

**Comment by disnoa** [comment]
I get it, the problem was that i didn't understand what **Dependency** means. Thanks you!
