### ISSUE TITLE
Injecting components loaded with require.js

### ISSUE THREAD

**Issue by marco-faustinelli** [johnpapa/angular-styleguide#624]
I like very much the idea of having many smaller files, each one for its own component.
However, I don't want to have tens and maybe hundreds of lines:

    <script src="my.small.controller.file.js"></script>

inside my `index.html` file. Therefore I am planning to use require.js to declare file dependencies and load them all in orderly fashion.

However I can't see exactly how to handle angular injections of require-loaded components. Let's take for example [this case](https://github.com/johnpapa/angular-styleguide#user-content-configuration-1)

    angular
        .module('app')
        .config(configure);

    configure.$inject =
        ['routerHelperProvider', 'exceptionHandlerProvider', 'toastr'];

    function configure (routerHelperProvider, exceptionHandlerProvider, toastr) { ... }

If the module I am configuring is the the very first module of the app, where will I prepare the Angular components that I want to give the injector? I understand that in your architecture `app` depends on `app.core`; this question is about the very first module.

**Another question**: if a module has ten controllers in 10 separated files:

    angular.module('myModule')
        .controller('Speakers', speakers)
    ....

how would you suggest to handle the dependencies in presence of requireJs? [This page](https://www.youtube.com/watch?v=ysXcfpjxm7U) proposes to have requireJs provide an array of file references and import+read all the 10 files one after the other. No Angular whatsoever involved in the import/inject process and no guarantee on the sequence of file import.

Thinking about it, I can't recall any point of this repository where you specified how to physically load the files into the browser. Did I miss something?

**Comment by dietergeerts** [comment]
Or you can just use gulp to build your files into one?

**Comment by johnpapa** [comment]
I use gulp in a build process. You can use that with require if you want.
