### ISSUE TITLE
How to avoid referring a module which is not defined yet. 

### ISSUE THREAD

**Issue by raghuvenmarathoor** [johnpapa/angular-styleguide#627]
I want to modularize my app and I've created a folder structure for each modules like the following

    /module-name/
       module-name.js -- for module initialisation
       module-name.service.js -- service
       module-name.controller.js -- controller 

problem is that as module-name.controller is alphabetically higher in order than module-name.js , my uglify is generating its code first which is triggering an error saying "Module 'module-name' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument."

How do I avoid such an error?

For the time being, I've chosen to define the modules in a file which will be the first file in root folder. 
So, app.js  will have 
    
    angular
        .module('module-name', []);
    angular
        .module('module-name1', []);
    angular
        .module('main-module', ['module-name','module-name1']);

Is this a good practice?

**Comment by bampakoa** [comment]
Hi there,

You could change the name of **module-name.js** to **module-name.module.js**, as stated in the guide, and uglify all **module.js** files first.

**Comment by raghuvenmarathoor** [comment]
Hi,

I have a lot of files to uglify and it seems difficult to add each and every js files manually. Is there any tools which can uglify in a specific order? 

I'm using grunt uglify in my app

**Comment by bampakoa** [comment]
You could check [hottowel generator project](https://github.com/johnpapa/generator-hottowel) from @johnpapa that automates uglify/minification using **gulp**.

**Comment by raghuvenmarathoor** [comment]
Thanks...
