### ISSUE TITLE
Modifications for Angular 2.0?

### ISSUE THREAD

**Issue by mbcooper** [johnpapa/angular-styleguide#628]
Is anyone considering how/where this fantastic guide changes with NG 2?  Esp as we have the choice of TypeScript as a first class language?

**Comment by zachlysobey** [comment]
This is a guide specifically for angular 1 and there will (presumably) be another project (projects) for angular 2.

**Comment by zachlysobey** [comment]
See the discussion here: https://github.com/johnpapa/angular-styleguide/issues/355

**Comment by johnpapa** [comment]
yep. this guide was crafted after many apps were written. im working on a new one for A2, but i am waiting til the experience is behind it before releasing too much of it.

**Comment by johnpapa** [comment]
the concepts in this guide here translate pretty well tho. syntax, obviously, differs
