### ISSUE TITLE
PascalCase file naming

### ISSUE THREAD

**Issue by ghahramani** [johnpapa/angular-styleguide#635]
Hi,
I want to know why you recommend this type of naming. What do you think if we use PascalCase for example for avenger we can say AvengersController.js or AvengersConfig.js or AvengersRoute.js

I think it's much better. I want to hear all thoughts.
Thanks

**Comment by bradchesney79** [comment]
PascalCase
camelCase

kebab-case (train-case) (lisp-case)
snake_case SNAKE_CASE Snake_Case Snake_case

ALLCAPS
lowercaseonly

Learn 'em, live 'em, love 'em.

**Comment by ghahramani** [comment]
@bradchesney79 Thanks to mentioned I edit my question. But I want to know why we don't use PascalCase for javascript files? ( I mean in John Papa style guide )

**Comment by dietergeerts** [comment]
Just use the appropriate casing for the language you are in, so it's the same others are already using etc.... less fuss, less problems, less confusion, ....

**Comment by gkalpak** [comment]
Some OS are case-insensitive while others aren't. 

Using lowercase filenames everywhere avoids surprizes (where your app will break when moving to case-sensitive OS). Thus it's considered a good practice (when it comes to JS files at least).

It's OK to choose another casing for consistency with the rest of your stack imo (although I always use lowercase).

**Comment by ghahramani** [comment]
@gkalpak Yeah I work with Mac OSx and it's case sensitive but because I work with automation ( gulp ) to inject the file in index.html so I think It won't break anything because the automation cares about the all these stuffs

**Comment by gkalpak** [comment]
@ghahramani, true, until someone checks out your project on a case-insensitive OS and then tries to serve it of a case-sensitive server. Other combinations are also possible :)

The point it, by using lowercase filenames, you will potentially avoid some hard-to-find "bugs" and lots of disappointment. "Potentially" is the key word here - there are always trade-offs. All in all, I consider lowercase filenames a good practice for JS front-end assets (and as such, pretty suitable for the styleguide).

**Comment by johnpapa** [comment]
1 addition point for the dasherized style and using dots is to make it easier for build systems like gulp to find the files of a particular type. *.spec.js *.module.js etc

**Comment by ghahramani** [comment]
@gkalpak @johnpapa  Ok thank you. I got the points
