### ISSUE TITLE
Question about "controller activate" technique

### ISSUE THREAD

**Issue by comara** [johnpapa/angular-styleguide#638]
I'm using the "controller activate" technique referenced here: https://github.com/johnpapa/angularjs-styleguide#style-y080. 

Question: Is there a way to move the call to getAvengers() to a function inside the dataservice? For example, I would like to create listAvengers() and getAvenger(avengerId) functions inside the dataservice, and both would be responsible for calling getAvengers.

I tried a few different things, but I'm not able to get the results to show in my view. My logging shows that the data is being retrieved, but the view never updates. Does Angular make a copy of my data when scope variables were set instead of observing the underlying data for changes?

**Comment by zachlysobey** [comment]
This sounds like a good candidate for a plnkr and/or a StackOverflow question.

**Comment by jeserkin** [comment]
The better question under this topic would probably be, why activate? Why not init or initialize?

**Comment by johnpapa** [comment]
activate is just word. Durandal used it (now Angular 2 and Aurelia use it too).
