### ISSUE TITLE
Question about "gulpfile"

### ISSUE THREAD

**Issue by INGCRENGIFO** [johnpapa/angular-styleguide#640]
Hello, I'm kissing the pope john guide but have a question about your gulpfile.js.

As I read on various topics, such gulpfile runs asynchronously and may complete a first tasks than others, then it is not good to use something like "run-secuence"? I see using something.

I appreciate your comments and advice.

I'm not using gulpfile pope john as it is very advanced and profit not understand but if I'm using some of the things to be mine.

**Comment by johnpapa** [comment]
you can use run sequence.

or gulp 4 will have a feature for parallel tasks.

or watch my gulp course on Pluralsight and you can learn how it all works in detail.

**Comment by INGCRENGIFO** [comment]
Hello "john papa", which you use ?? I am new to this and reading your gulpfile use secuentas not see, but if it works excellently. Now I did my gulpfile copying me yours does not work the same.

I appreciate your recommendation. (not yet implemented the test)
