### ISSUE TITLE
What are the basic differences between Angular Factory and services ?

### ISSUE THREAD

**Issue by ami0011** [johnpapa/angular-styleguide#641]
I am an angularJs developer and following johnpapa angular style-guide since beginning. But I am not able to understand the basic difference between factories and services apart from syntax. Can anyone explain it for me? 
Thanks in advance.

**Comment by bampakoa** [comment]
Hi,

You can find a similar issue [here](https://github.com/johnpapa/angular-styleguide/issues/39)

**Comment by zachlysobey** [comment]
I don't really think the purpose of this guide is to explain the differences.
Moreover, you don't *really* need to understand. They're pretty much interchangable. Just pick one and roll with it.

`service`s return a *constructor* that angular instantiates with `new` under the hood. `factory`s return an object literal. Angular just gives you that object when the factory is injected.

In any case, the thread linked and any number of articles on the internet will provide a better explanation than you are likely to get here.

This one looks good.
http://tylermcginnis.com/angularjs-factory-vs-service-vs-provider/

**Comment by MarcLoupias** [comment]
> But I am not able to understand the basic difference between factories and services apart from syntax. 

Simple, factory allow you to execute some code before instanciation.
Services (i mean in the large term, provider + factory + services) are singleton, they instanciated only once in the webapp life time. So this initialization code will be executed once for the webapp life time.

Another bonus for factory over service is the ability to define what is public what is private.

Ex : 

```javascript
(function (angular) {
  'use strict';

  angular
    .factory('foo', function () {
      var thisIsPrivate = "Private";

      return {
        variable: "This is public",
        getPrivate: getPrivate
      };

      function getPrivate() {
        return thisIsPrivate;
      }

    });

})(angular);
```
This code is from this [excellent article] (http://angular-tips.com/blog/2013/08/understanding-service-types/) on services.

**Comment by gkalpak** [comment]
> Another bonus for factory over service is the ability to define what is public what is private

You can have private things in services too.

--
Trying to explain the differences between providers/factories/services etc is totally out of place for this repo imo. There are plenty of excellent (detailed and quite lengthy) resources out there (official docs, blog-posts, SO answers), let's not try to squeeze all that wisdom in a couple of lines, because we'll end up with inevitably inaccurate and probably misleading answers.

Fortunately, this is one of the favorite Angular topics (especially in the early days).

**Comment by johnpapa** [comment]
SO is more appropriate
