### ISSUE TITLE
Route cancellation when a form is dirty

### ISSUE THREAD

**Issue by bampakoa** [johnpapa/angular-styleguide#644]
Hi,

In the context of this guide, how do you suggest one should approach the problem of cancelling a route change when a form is dirty (has changes)? 
My first thought would be to create a service, that could be called in the **$stateChangeStart** event of the rootScope, and will check if a form is dirty. The current working form could be set in the service.

**Comment by brutalcrozt** [comment]
@bampakoa Does that create `routeChangeError` ? Currently i work on route and form also

**Comment by bampakoa** [comment]
@brutalcrozt I finally chose not to implement this behavior in the current case but I would be interested if you have any ideas.

**Comment by brutalcrozt** [comment]
@bampakoa is form dirty can cause `routeChangeError` ? i am not yet can touch my code

**Comment by bampakoa** [comment]
@brutalcrozt Yes, I think that should be the correct behavior.

**Comment by brutalcrozt** [comment]
that's odd , sometimes it not cause routeChangeError in my app. Then what option you choose to handle this man?

**Comment by bampakoa** [comment]
I decided not to handle it in my application because I was running in too many problems.
