### ISSUE TITLE
Assigning values to the $rootScope

### ISSUE THREAD

**Issue by remcohaszing** [johnpapa/angular-styleguide#648]
I generally think it's a bad practice to assign properties to the `$rootScope`. Mainly because I consider scope inheritance to be a bad practice.

It can be convenient though. I had in mind to use the following piece of code:
```js
angular.module('myApp')

.decorator('$rootScope', function($delegate) {
  $delegate.url = function(url) {
    return 'url("' + url + '")';
  };
  return $delegate;
});
```

This would allow it to be used in `ng-style`:
```html
<div ng-style="{'background-image': url(vm.someUrl)}"></div>
```

Instead of:
```html
<div ng-style="{'background-image': 'url("' + vm.someUrl + '")'}"></div>
```

Similarly it would often be convenient to add for example a boolean `authenticated` to the `$rootScope`.

Do you have any thoughts on using `$rootScope` or scope inheritance in general?

**Comment by MarcLoupias** [comment]
> Do you have any thoughts on using `$rootScope` or scope inheritance in general?

Yes, don't use `$rootScope`, and don't use scope inheritance.

If you want to save a state or a property and share it to all your webapp, use a service and attach the data to the service instance.

> I generally think it's a bad practice to assign properties to the $rootScope. Mainly because I consider scope inheritance to be a bad practice.

And because it makes unit tests harder to write properly.

**Comment by dietergeerts** [comment]
True, but there are exceptions, like the name you want in the title in the header of your page, but these aren't functionalities of your program though.

**Comment by remcohaszing** [comment]
@MarcLoupias:
> If you want to save a state or a property and share it to all your webapp, use a service and attach the data to the service instance.

I totally agree. However, in my example the value is used in a template, so a service is not an option. I guess one should always use a filter for this purpose? E.g.:
```html
<div ng-style="{'background-image': vm.someUrl|url}"></div>
```

@dietergeerts:
> True, but there are exceptions, like the name you want in the title in the header of your page, but these aren't functionalities of your program though.

This can be accomplished using a directive or named views.

**Comment by johnpapa** [comment]
good conversation. the nothign is absolute ... and you bring up some good points. Im not convinced it should go in the guide (i like it here in the comments tho as it is searchable) because most of the time it is not something we want to recommend.
