### ISSUE TITLE
Reason for "Directives and ControllerAs" is not helpful

### ISSUE THREAD

**Issue by LordMidi** [johnpapa/angular-styleguide#650]
In section "Directives and ControllerAs" the reason for using them is not very helpful:

> Why?: It makes sense and it's not difficult.

A little more technically explanation would be good (if there is any at all).
I mean "It makes sense" is just a statement, nothing more...

**Comment by brutalcrozt** [comment]
For me it's help because i already use ```controllerAs vm``` syntax, consider when i use controllerAs syntax i will use it everywhere because we have to consistent with using controller as with view.

**Comment by zachlysobey** [comment]
For easy reference: [Style Y075](https://github.com/johnpapa/angular-styleguide#style-y075)
