### ISSUE TITLE
Is possible inject a module automatically? 

### ISSUE THREAD

**Issue by rlopes-fixeads** [johnpapa/angular-styleguide#656]
Is it possible add a module after the APP has been initialized?
exemple I have the main module **`app`** the file name is `app.module.js`

```
(function() {
        'use strict';
        angular
            .module('app', ['app.core']);
})();
```

And I have the module named **`app.layout`** in another file separate with name `layout.module.js` as in example:

```
(function() {
    'use strict';
    angular
            .module('app.layout', [])
            .controller('Layout', layout);

    function layout() {}
})();
```

But I would like to inject the **`app.layout`** module in **`app`** module, but the injector needs to be
in file `layout.module.js`, for when the IFF is executed the module needs To be automatically injected
The end it is the result:

```
(function() {
    'use strict';

    var app = angular.module('app');
        
    app.$inject = ['app.layout'];
})();

(function() {
    'use strict';
    angular
            .module('app', ['app.core', 'app.layout']);
})();
```

Can anyone help me, I have no idea where I can start.
maybe creating a `provider`, `run` maybe there is anything like it that is already done.
Below there is an example:

[Fiddle Example](https://fiddle.jshell.net/Grumelo/tqz29b3e/1/)

**Comment by MarcLoupias** [comment]
You could use [ocLazyLoad] (https://oclazyload.readme.io/docs/getting-started).

**Comment by rlopes-fixeads** [comment]
Maybe I am doing something wrong. 
But it isn't working, I think is because the controller on html
is loading before `ocLazyLoad` inject the module.

> I got this error "Error: [ng:areq] Argument 'Content' is not a function, got undefined"

How can I do it? Any idea?
Look at example 
[Fiddle Example](https://fiddle.jshell.net/Grumelo/uyLoLn4x/3/)

**Comment by zachlysobey** [comment]
I don't think this is the right venue for such a question (perhaps better suited for StackOverflow or ocLazyLoad's issues). In any case, you probably ought to create a minimal test case that shows your issue. 1400 lines of code in a jsFiddle is a bit overwhelming

**Comment by rlopes-fixeads** [comment]
Ok, But I would like to know if exist any way to inject the module in app that has  been started?

**Comment by zachlysobey** [comment]
i dont think so, no.

**Comment by dietergeerts** [comment]
You can't inject a module, but you can let your app load it through ocLazyLoad when it's needed. It's what I also do in big apps where we don't want to load everything at first.

**Comment by dequn** [comment]
Auto injection is possible, but you can only use the defined name, can't change. The big problem is than it's not compressed safely.

**Comment by johnpapa** [comment]
more of a SO question
