### ISSUE TITLE
Publishing data to the view with functions is bad practice ?

### ISSUE THREAD

**Issue by MarcLoupias** [johnpapa/angular-styleguide#661]
There is no good practices in this style-guide about publishing data in the views.

I have some dev who likes to do this kind of things : 

```javascript
<xx-list-item ng-repeat="item in myCtrl.getItems()">
    <h1>{{ item.prop1 }}</h1>
    <p>{{ item.prop2 }}</p>
</xx-list-item>

// or worse 
<xx-list-item ng-repeat="item in myCtrl.getItems()">
    <h1>{{ item.getProp1() }}</h1>
    <p>{{ item.getProp2() }}</p>
</xx-list-item>

// in the controller :

(function (angular) {
    "use strict";

    angular
        .module('app')
        .controller('MyController', MyController);

    MyController.$inject = ['dataHolderService'];

    function MyController(dataHolderService){
        var vm = this;
        vm.getItems = getItems;

        function getItems(){
            return dataHolderService.data;
        }
    }

}(angular));

```
The `dataHolderService` hold data. Theses data are set in the service elsewhere in the webapp.

I don't like this, i prefer regular data binding but do you see any reason to avoid this ?
By regular data binding i mean `vm.data = dataHolderService.data`.

I see some cons : 
- a console.log in `getItems()` show that the function is executed multiples times at each digest.
- there is a risk to see another dev writing code inside getItems, leading to bad perf issues because of first of the cons.
- one time binding only work for expressions, [see this answer] (https://github.com/angular/angular.js/issues/11416#issuecomment-94837181) from an angular dev.
`<xx-list-item ng-repeat="item in ::myCtrl.getItems()">` will not work.

I see no pros.

**Comment by gkalpak** [comment]
It depends on the implementation of `dataHolderService`. If `dataHolderService.data` is already assigned when you try to access it during your controllers instantiation and is never re-assigned, then the direct version is OK. But it will break if `dataHolderService.data` is not available yet, or if it gets re-assigned. (That's when you need the function form.)

<sub>Basically, the asynchronous initialization should be solved using promises, but if the `dataHolderService.data` gets re-assigned, then you either need a function or you need to expose the whole service and access it's `data` property from the template (which might not be ideal).</sub>

**Comment by johnpapa** [comment]
also ... you could assign the value of the function just once only.

```
(function () {
    "use strict";

    angular
        .module('app')
        .controller('MyController', MyController);

    MyController.$inject = ['dataHolderService'];

    function MyController(dataHolderService){
        var vm = this;
        vm.items = [];
        activate();

        function activate(){
            return dataHolderService.data;
        }
    }

}());
```

**Comment by MarcLoupias** [comment]
@gkalpak 
> But it will break if dataHolderService.data is not available yet, or if it gets re-assigned. (That's when you need the function form.)

It works well with direct assign, you just need to wrap primitives and array in an object like that : 
```javascript
vm.data = {
    items: []
}
```
With this pattern you can re-assign vm.data.items and the view will render correctly the data.

My concern is about performances essentially, a function is constantly executed at each digest, and about good practices, if you use a function de publish data, some dev can have the temptation to write more code in there.


So my question is more : "Do you think direct binding is a better practice then function assign ?"

@johnpapa 
I don't understand your code, `activate()` is not exposed to the view and it return data to ?

**Comment by johnpapa** [comment]
typo is now fixed ... the point is you dont want to call a function in a binding. that makes it call that over and over again. instead, call the func in your controller when you need it (active in the above code) and then set your array.

**Comment by gkalpak** [comment]
@MarcLoupias 

> It works well with direct assign, you just need to wrap primitives and array in an object

That's why I said, it depends on the implementation of `dataHolderService`. You can make it work both ways, but note that you are not always the implementor of `dataHolderService`.

> Do you think direct binding is a better practice then function assign ?

I generally do, with the exception when `dataHolderService` is implemented in a way that doesn't lend itself for property binding and you don't have access to change `dataHolderService`. In any other case, binding to properties (possibly through a promise if necessary) is both cleaner and more performant* (and avoids the pitfall of putting extra logic into the function, where it doesn't belong).

(*): It's not the kind of performance gain that you are likely to notice, but a gain is a gain :wink:
