### ISSUE TITLE
jsDoc or ngDoc?

### ISSUE THREAD

**Issue by guillermo-varela** [johnpapa/angular-styleguide#663]
Hi,

I see that for documentation the recomendation is "jsDoc": https://github.com/johnpapa/angular-styleguide/#comments

But the AngularJS code is using a variant called "ngDoc": https://github.com/angular/angular.js/wiki/Writing-AngularJS-Documentation

Is there a reason why using "jsDoc" instead of "ngDoc"?
Maybe "ngDoc" should be used only on the official AngularJS source code?

Thanks.

**Comment by johnpapa** [comment]
any doc tool is fine to use.

**Comment by guillermo-varela** [comment]
Got it!

PS: Great work @johnpapa :+1:

**Comment by DeveloperChallenge** [comment]
Any one you can use as you like 👍
