### ISSUE TITLE
Service used by layout module

### ISSUE THREAD

**Issue by bampakoa** [johnpapa/angular-styleguide#672]
In case you have to create a service that is used from the controller of the layout module (e.g. Shell) where would you add it? In the core service or in a dedicated one inside the layout module?

Thanks

**Comment by NevillePerkins** [comment]
Good question. I'm struggling with the same concept.

**Comment by andreshg112** [comment]
I'm waiting for the answer too.

**Comment by bampakoa** [comment]
While I am thinking it again and again, I conclude to the following:
Since the layout ***is*** a module, everything that applies to the other modules should be valid for the layout also. Thus, the service should go to the layout module in that case. What do you think?
