### ISSUE TITLE
Wouldn't i18n files be more accessible?

### ISSUE THREAD

**Issue by zirho** [johnpapa/angular-styleguide#679]
Hi,

Wouldn't i18n files be more accessible if you change angular 1 style guide link on the README.md to 
`https://github.com/johnpapa/angular-styleguide/tree/master/a1/`
not
`https://github.com/johnpapa/angular-styleguide/tree/master/a1/README.md`
?

so people landing on the first page from other countries might find it easier that there are translated docs.

thanks

**Comment by johnpapa** [comment]
help me understand how this helps?
