### ISSUE TITLE
Confusing services standards

### ISSUE THREAD

**Issue by NevillePerkins** [johnpapa/angular-styleguide#682]
I'm still battling to figure out where to put my data services factories. In which file will the "dataservice" factory under the Y060 Seperate Data Services example be saved? 
I'm guessing it will be in the services/data.service.js file as per the "file per feature" structure? 

If you go with the "one file per module" idea, then this should be in an avengersService.js file, or not? 

And then what about all the other other services e.g. hypothetically speaking, where would the GetVilans, GetWeapons, GetNavigationServices etc factories go? All into one "..services.js" file? Or into a [feature].service.js file within each feature folder? There are no .service.js files in the "structure by feature" example. 

I'm so confused my head is spinning with all these different, contradicting standards.

**Comment by bampakoa** [comment]
@NevillePerkins to make it clear: if a service is for a specific module only, then add the file in that module, otherwise add it to the core. That is, the **avengers.service.js** should be in the **Avengers** module. If for any reason, a method of this service is needed from another module, add it to a **data.service.js** file in the **core** module.
I hope it helped you.

**Comment by NevillePerkins** [comment]
@bampakoa and the "core" module would be the roor /app folder, yes?

**Comment by bampakoa** [comment]
That's right!

**Comment by NevillePerkins** [comment]
Sorry, I just notice that he puts the data.service.js file under the services/ drawer as per Y152. I'll do that for now. 

Is there a sample project for the exact folder structure as per the Y152 layout? I'd be interested to see the content of some of those files and modules to help me understand better of where to place what. 

For example what goes in app.config.js?
And why is there no config.routes.js?

**Comment by bampakoa** [comment]
You can see how [generator-hottowel](https://github.com/johnpapa/generator-hottowel) is implemented.

**Comment by NevillePerkins** [comment]
Thank you kindly, I'll have a look at that. 

I digress though as you did answer my services questions, thanks!
