### ISSUE TITLE
directive naming convention

### ISSUE THREAD

**Issue by Elux91** [johnpapa/angular-styleguide#683]
the guide says that a directive schould be named using lowerCamelCase.
The problem is if you create an attribute using this convention it won't show, because html doesn't like attributes names like this.

example directive:

    angular.module('shiftPlanner')
    .directive("roleCheckbox", function() {
      return {
        restrict: "A",
        link: function(){
          alert("test!");
        }
      }
    });

example view: 

    <div roleCheckbox class="col-xs-2">role filter</div>

this won't work.

The problem is neither does using a hyphen or an underscore..

So I guess there is no other choice but write rolecheckbox?

I guess not using an attribute, but a class would be the best way to avoid this.

**Comment by mattgrande** [comment]
If the directive is named `roleCheckbox`, as in your example, angular will look for a directive in the HTML like this:

    <div role-checkbox class="col-xs-2">role filter</div>

**Comment by Elux91** [comment]
my bad. if the directive is named roleCheckbox you have to access it as role-checkbox in html
