### ISSUE TITLE
Missing guidelines on providers and decorators.

### ISSUE THREAD

**Issue by lobo-tuerto** [johnpapa/angular-styleguide#686]
I think it would be good to have guidelines for how to name and structure providers and decorators.

They aren't usually needed, but I came across this when implementing a `$log` enhancer (using a provider and a decorator).

**Comment by johnpapa** [comment]
i avoid providers when i can. :)

decorators ... i use them sparingly, but they are helpful for things like logging and error handling.

its less of a style tho. might be better for SO on when to use them
