### ISSUE TITLE
Modularity: Angular and Browserify

### ISSUE THREAD

**Issue by brion-fuller** [johnpapa/angular-styleguide#691]
https://github.com/johnpapa/angular-styleguide/blob/master/a1/README.md#modularity

Under this section, this talks about create a bunch of small modules that you would re-purpose over the whole angular application.  I was wondering how this would work with browserify.  

1. My original thought shown below is to use browserify to create the modules, I like this idea because this doesn't populate the global namespace.

     - app.js

     ```
     angular
          .module('MyApp', [
               require('./core/module1'),
               require('./feature/module2')
          ])
          .provider(require('./blocks/routehelper'));
     ```

    - routehelper.js

     ```
     /* @ngInject */
     module.exports = function routerHelperProvider($locationProvider, $stateProvider, $urlRouterProvider) {
          (code here)
     }
     ```

1. The other way would be using angular modules with browserify to import them to other modules.

     - app.js

     ```
     require('./blocks/routehelper');

     angular
          .module('MyApp', [
               'blocks.router'
           ]);
     ```

     - ./blocks/router.module.js
     ```
     module.exports = (function(){
          angular.module('blocks.router', ['ui.router'])
               .provider(require('./routehelper'));
     })();
     ```

**Comment by johnpapa** [comment]
might be better on StackOverflow
