### ISSUE TITLE
Where to put services that share data and functionality

### ISSUE THREAD

**Issue by roblouie** [johnpapa/angular-styleguide#695]
I'm curious about the recommended location for a service that is used in multiple unrelated components.  The style guide recommends a folder-by-feature layout, which I think is great, but what if a service is used in multiple features?  I've seen another best practices guide recommend making a "shared" folder for directives and services used in multiple places.  Thoughts?

**Comment by bampakoa** [comment]
@roblouie My approach is to have a shared core module and put services in there.

**Comment by dietergeerts** [comment]
Really depends on the project. Having a shared core module like @bampakoa says is great. If your application is bigger and you have shared stuff for certain 'submodules' you can have multiple shared modules, but most of the time, one core module is enough.

**Comment by johnpapa** [comment]
at the most shared level that makes sense.
