### ISSUE TITLE
Structure with server/client

### ISSUE THREAD

**Issue by Cyber1000** [johnpapa/angular-styleguide#697]
Hi,

Thanks for this comprehensive styleguide! In particular I like the idea of structuring by "Folders-by-Feature". I want to restructure a small private project of some colleages and me and scratching my head of how to structure it efficiently. 

I would use the "Folders-by-Feature" structure for the angular-app. But we also have an express-server included in our project (structure of express itself found on http://expressjs.com/en/starter/generator.html). How would you build this together, do you have an advice or even better: a blog entry or similar?

Thanks!

**Comment by johnpapa** [comment]
i do this ...

```
src/
  client/
    app/
  server/
```

**Comment by johnpapa** [comment]
Thanks for the question!
