### ISSUE TITLE
Do you think you could add some details for the "creation" and "use" of module?

### ISSUE THREAD

**Issue by jianlin** [johnpapa/angular-styleguide#699]
https://github.com/johnpapa/angular-styleguide/blob/master/a1/README.md#style-y001

So it looks like, we must arrange for the module creation file to be loaded first. 

So, is it true that... say, we divide global directives into separate files, and global services into separate files, then if they all use the same module, we would add dependencies that myDirective1 need to the module creation file.   And then, say 2 weeks later, if myDirective2 needs some other dependencies, then now add it to the module creation file?

Does it matter what order to load the files (in terms of performance due to locality)?  Because we can load all module creation files first, or another way is to load 1 module creation file and all the directives and services for that module.  (and repeat for the next module)

**Comment by johnpapa** [comment]
the module files just have to come before the others.
