### ISSUE TITLE
Inheritance

### ISSUE THREAD

**Issue by patrick-fls** [johnpapa/angular-styleguide#70]
How would you handle inheritance for services in the spirit of the guide?

I realized my services and controllers each reuse a lot of boilerplate code and/or function names. 
Looks pretty WET.

Todd's suggestion https://github.com/toddmotto/angularjs-styleguide#controllers of prototypal inheritance wouldn't work well in this case because of IIFE.

**Comment by ddanailov-nmdp** [comment]
@johnpapa - What do you think for this article: [Object-oriented AngularJS Services](http://blog.revolunet.com/blog/2014/02/14/angularjs-services-inheritance/) ?

This article follow the guide suggestions ?
