### ISSUE TITLE
Imports, spaces or not around keys

### ISSUE THREAD

**Issue by Foxandxss** [johnpapa/angular-styleguide#701]
So the idea is:

```
import { Component } from 'angular2/core';
```

vs

```
import {Component} from 'angular2/core';
```

I see you prefer the first one, but could be good to say a few words about it.

**Comment by johnpapa** [comment]
spaces :)

mostly for clarity

thanks for the issue

**Comment by johnpapa** [comment]
Angular 2 issues will now go to the A2 style guide in the angular.io repo
