### ISSUE TITLE
conventions around typings

### ISSUE THREAD

**Issue by Foxandxss** [johnpapa/angular-styleguide#705]
It is good to cover stuff like typing. For example:

```
heroName = "Mr Elastic";
```

vs

```
heroName: string = "Mr Elastic";
```

Implicit vs explicit typing. Implicit when the attribute is initialized, explicit when it is not initialized.

----

Return types:

```
isSelected(hero: Hero) : boolean {
 return this.hero === hero;
}
```

vs

```
isSelected(hero: Hero) {
  return this.hero === hero;
}
```

I vote for the first one.

----

Perhaps I am digging too much into typescript instead of angular 2 concrete things, so this is up to you.

**Comment by johnpapa** [comment]
another great example! thanks!

My guideline is that if the type can be determined, don't be explicit.

```
// avoid
heroName: string = "Mr Elastic";
```

```
// recommended
heroName = "Mr Elastic";
heroWeapons: number; // be explicit when no initial value that can be derived
```

Return types:
```
// avoid
isSelected(hero: Hero) : boolean {
 return this.hero === hero;
}
```

```
// recommended
isSelected(hero: Hero) {
  return this.hero === hero;
}
```

**Comment by Foxandxss** [comment]
That works for me.

What about arrays?

```
heroes: Hero[] = [];
```

We need to do both in here or we will lose the typing.

Also, what about `hero[]` vs `Array<Hero>`. People vote for the first one because the second one is too much Java-ish (or C#-ish). I think they are right.

**Comment by johnpapa** [comment]
I prefer `[]` ... shorter, easier.

```
heroes: Hero[];
```

**Comment by rmdias** [comment]
@Foxandxss I can be wrong, but I think that It also touch questions about performance.

You can see it on:
- [Performance with JavaScript strings](https://hacks.mozilla.org/2012/12/performance-with-javascript-string-objects/)
- [Performance Tips for JavaScript in V8](http://www.html5rocks.com/en/tutorials/speed/v8/)

**Comment by johnpapa** [comment]
Angular 2 issues will now go to the A2 style guide in the angular.io repo
