### ISSUE TITLE
Angular2 services and DTOs in one file

### ISSUE THREAD

**Issue by damienbod** [johnpapa/angular-styleguide#706]
Thanks for this style guide. It's great.

I was looking at this service:
https://github.com/johnpapa/angular2-tour-of-heroes/blob/master/app/hero.service.ts

Do you not think it would be better to split the DTOs and the service? I know this saves a line in a component when using the service. Maybe the recommended approach could be defined here.
 
Greetings and thanks for the style guide Damien

**Comment by johnpapa** [comment]
this is an interesting question and one i can see pros and cons for on both sides.

1 file per thing? ... very clear, but lots of imports (but we use barrels)
1 file for all models? ... easier ... but yuk
1 file for the model for a service? ... not so great as most services will use many models

so i lean to 1 file per thing

thoughts?

**Comment by bampakoa** [comment]
I would definitely vote for 1 file per thing, one for the interface and another one the services that provide to that interface.

**Comment by johnpapa** [comment]
there is also a consideration for file that only contain interfaces, as they generate emptiness.

**Comment by damienbod** [comment]
I would also prefer 1 file per thing, maybe then the model DTOs inside a models folder.

<component folder>
   a.component
   b.component
   cService
   dService
  <models folder>
     DTOa
     DTOa1
     DTOb
     DTOc
     ...

What do you think?

Greetings Damien

**Comment by johnpapa** [comment]
Angular 2 issues will now go to the A2 style guide in the angular.io repo
