### ISSUE TITLE
ES6 for Angular

### ISSUE THREAD

**Issue by ospar0829** [johnpapa/angular-styleguide#707]
Hi Jhon, thanks for the huge contribution!

I suggest update  angular1's styleguide including ES6 syntax and preparation guide for migrate to Angular 2 [https://angular.io/docs/ts/latest/guide/upgrade.html#!#preparation](https://angular.io/docs/ts/latest/guide/upgrade.html#!#preparation)

**Comment by johnpapa** [comment]
would be nice, yes. but i'm not going to create an ES5, ES6, ES7, and TS version of this guide for A1. Right now I'm leaving it as ES5 for A1 and TS for A2. Feel free to create one tho
