### ISSUE TITLE
Angular 2 - TSLint support

### ISSUE THREAD

**Issue by leocaseiro** [johnpapa/angular-styleguide#715]
As there's a JSCS and a JSHINT for Angular 1.x, I believe that a tslint that follows the Angular Style Guide would be very helpful for who chooses Typescript.

What do you think?

**Comment by johnpapa** [comment]
would be nice ... and will come. stay tuned.

**Comment by crorodriguezro** [comment]
what happened with this?

**Comment by leocaseiro** [comment]
Hi @crorodriguezro the https://github.com/mgechev/codelyzer is what you're looking for.
