### ISSUE TITLE
component structure

### ISSUE THREAD

**Issue by kazemihabib** [johnpapa/angular-styleguide#719]
Hi,I have a question about components.consider the below screenshot as an example(media controller of a potplayer).
now if you want to create this in angular2 do you implement all buttons of that in one component or you make a mediaController as a root of it  and put each button and it's action in a component.
can you please draw your structure.
![media-controller](https://cloud.githubusercontent.com/assets/10830552/14629150/7cd58ddc-0619-11e6-9fec-c5821a91b628.png)

what do you think about this:
app|...
+++|...
+++|...
+++|--> media-controller.component+|-->play.component(for handling play and pause) +++++++++++++++++++++++++++++|-->stop.component
+++++++++++++++++++++++++++++|-->seek.component(for both backward and forward)
+++++++++++++++++++++++++++++|-->open-file.component
+++++++++++++++++++++++++++++|-->aduio.component|-->mute.component
 +++++++++++++++++++++++++++++++++++++++++++++ |-->audio-slider.component

![image](https://cloud.githubusercontent.com/assets/10830552/14630260/9dcf16c2-0621-11e6-9e66-4dcad6fea786.png)

**Comment by bampakoa** [comment]
I would go with the following:

- Controls component (contains buttons that control the player such as play, pause etc).
- Progress component (will show duration, elapsed time and the progress bar).
- Settings/Playlist component (the two buttons on the far right).
- Sound component (contains sound control)

**Comment by johnpapa** [comment]
more will come. stay tuned. closing as we'll have answers within 2 weeks :)

**Comment by kylecordes** [comment]
Even as more stuff comes out from the Angular team and more stuff lands in this growing style guide, I still think the question from this issue is fundamentally application-specific, but there is not an industrywide style guide answer. It all depends on what kind of flexibility you want in terms of moving the individual pieces around.
