### ISSUE TITLE
Separation of imports on top of files

### ISSUE THREAD

**Issue by bampakoa** [johnpapa/angular-styleguide#720]
I can see that in some cases, imports from angular2 modules are separated from custom ones by one empty line, such as in **Style A2-001**

```
// app.component.ts
import { Component, OnInit } from 'angular2/core';

import { Hero } from './hero';
import { HeroService } from './hero.service';
```
Is this a guideline or is it a random fact? If the former, it would be nice to state the importance of the separation between these two type of imports.

**Comment by johnpapa** [comment]
yes ... it is n purpose ... separate stuff we wrote vs stuff we didnt write
