### ISSUE TITLE
Alphabetized order of component members

### ISSUE THREAD

**Issue by bampakoa** [johnpapa/angular-styleguide#721]
I was reading through [Style A2-033](https://github.com/johnpapa/angular-styleguide/blob/master/a2/README.md#style-a2-033) and I found the following sentence really confusing:

> Place properties up top, then public functions, then private functions, alphabetized, and not spread through the component code.

Particularly the part that mentions the **alphabetized** order of members. 

Should we alphabetize each distinct section of our members (e.g. first alphabetize public functions, then private functions) or members as a whole?
Also, should we consider underscores or the alphabetization omits them?

**Comment by johnpapa** [comment]
no underscores. i'm removing those

yes, alpha by group
