### ISSUE TITLE
Self references in object declarations 

### ISSUE THREAD

**Issue by stefaneidelloth** [johnpapa/angular-styleguide#725]
If the property of an object needs to be used while the object is declared, would you recommend to 
a) define the property in the parent scope of the object or to 
b) define the object step by step. 

Does option b) has any disadvantages? It allows to define a singleton and keep the syntax similar to the syntax when using transient view models/modules.

Example for strategy a)
  var someValue = '';
  return {
      someValue: someValue,
      validate: validate
  };

  function validate() {
      if(someValue){
           /* */
      }
  }

Examble for strategy b)

var self =  {};
self.someValue = '';
self.validate = validate;
return self;

function validate() {
      if(self.someValue){
           /* */
      }
}

**Comment by johnpapa** [comment]
more of a SO question, i think
