### ISSUE TITLE
[Style A2-035] Defer Logic to Services

### ISSUE THREAD

**Issue by brechtbilliet** [johnpapa/angular-styleguide#727]
> [Style A2-035]
> Defer logic in a component by delegating to services.
> Why?: Logic may be reused by multiple components when placed within a service and exposed via a function.
> Why?: Logic in a service can more easily be isolated in a unit test, while the calling logic in the component can be easily mocked.
> Why?: Removes dependencies and hides implementation details from the component.
> Why?: Keeps the component slim, trim, and focused.

Not sure if I agree with this.
I'm a huge fan of using smart/dumb components.
Dumb components will not have any dependencies(mostly) and will know nothing about the application. Therefore they are easy to reason about and they are reusable.
Smart components do know about the application. However, I think smart components should have some kind of api that abstracts the application logic which they can use to communicate with the rest of the application.

If you try to defer all the component logic to services, you will have hard dependencies on every component and a lot of bloat code. Also, your components will become simple facades. I think every component has a responsability and should execute that himself. 

However, if the logic is unrelated to that specific component and can be used by different components, I totaly agree. In that case you inject a service.

What do you think?

**Comment by dietergeerts** [comment]
Keep in mind that there are different kinds of logic (I just give them a name here) and that each of them has a purpose and a place!:

- View logic: Logic that belongs to displaying things, like how something is shown, sorting stuff in a list, ... This belongs to a certain view.
- ViewModel logic: Logic that belongs to the behaviour of the view, like you have a list, and you can add, delete and edit items. It's the real logic that doesn't dictate any view. You should be able to use multiple templates with this kind of controller/directive/.... 
- Model logic: This includes mostly business logic and application logic, and its this kind that you want to have in services/model objects.

**Comment by johnpapa** [comment]
the intent is the logic is shared or not the responsibility of the component. if it is the component's job and nobody else will ever need it maybe you can go there. 

in the end, it's your app, your decision, your direction ... the guide is just a starting place ;)
