### ISSUE TITLE
Snippets for Atom Editor

### ISSUE THREAD

**Issue by mmcbride1007** [johnpapa/angular-styleguide#730]
I ported your VS Code snippets and made a package for Atom ([here](/mmcbride1007/ng2-snippets)). Is this the right place to cut a PR to contribute to the style guide? I wasn't able to find the repo for the Angular.io docs. Thanks!

**Comment by johnpapa** [comment]
the angular.io docs contain the A2 style guide please go there

**Comment by mmcbride1007** [comment]
Thanks
