### ISSUE TITLE
Angular2 Snippets

### ISSUE THREAD

**Issue by evanplaice** [johnpapa/angular-styleguide#731]
Carrying over from https://github.com/mgechev/angular2-style-guide/issues/15.

The Angular2 snippets package for Sublime Text are ready.

The PR for publication to Package Control is pending. https://github.com/wbond/package_control_channel/pull/5482.

I noticed mention of snippets in the Style Guide, not sure if this is worth mentioning. Feedback, contributions, and constructive criticism is welcome.

**Comment by johnpapa** [comment]
A2 snippets are listed in the official A2 guide which I have migrated to the A2 repo
