### ISSUE TITLE
Avoid prefixing private properties and methods with an underscore: Example show private field and not property

### ISSUE THREAD

**Issue by bittmeier** [johnpapa/angular-styleguide#733]
The example Shows an example with a private field.
/* avoid */

import { Injectable } from '@angular/core';

@Injectable()
export class ToastService {
  message: string;

  private _toastCount: number;

  hide() {
    this._toastCount--;
    this._log();
  }

  show() {
    this._toastCount++;
    this._log();
  }

  private _log() {
    console.log(this.message);
  }
}

The previous example should be valid. I see no other way to differ private field and property.. But you should avoid:

/
import { Injectable } from '@angular/core';

@Injectable()
export class ToastService {
  message: string;

  private _toastCountInner: number;
   
   private get  _toastCount () {
     return this._toastCountInner;
 }

  hide() {
    this._toastCountInner--;
    this._log();
  }

  show() {
    this._toastCountInner++;
    this._log();
  }

  private _log() {
    console.log(this.message);
  }
}

Good:
import { Injectable } from '@angular/core';

@Injectable()
export class ToastService {
  message: string;

  private _toastCount: number;
   
   public get  toastCount () {
     return this._toastCount;
   }
  hide() {
    this._toastCount--;
    this._log();
  }

  show() {
    this._toastCount++;
    this._log();
  }

  private _log() {
    console.log(this.message);
  }
}

**Comment by johnpapa** [comment]
I think you meant to put this in the angular.io repo, as the style guide for Angular 2 is there.

The style is meant to suggest that underscores are not necessary. The tooling in editors understands TypeScript and can tell you when we use private members inappropriately.

In years past JavaScript had no way of telling the editor these things.

Of course, as always, modify styles as you see fit.
