### ISSUE TITLE
Naming convention for constants

### ISSUE THREAD

**Issue by mmefriantine** [johnpapa/angular-styleguide#736]
Hi,

It's not an issue. It's a question.

I would like to know if there's a naming convention for constants to make them more obvious when we inject them inside controllers.

```
angular
    .module('abp001App', ['ngRoute'])
    .constant("myConfig", {
        "url": "http://localhost",
        "port": "80"
    })
```

**Comment by gkalpak** [comment]
There doesn't seem to be any guidelines for naming constants in the ng1 styleguide.
The ng2 styleguide suggests [uppercase and underscores][1] for constants, but they are not necessarily the exact equivalent of ng1 constants.

FWIW, I've always use `UPPERCASE_WITH_UNDERSCORES` for ng1 constants.

[1]: https://angular.io/docs/ts/latest/guide/style-guide.html#!#constants

**Comment by mmefriantine** [comment]
Thank you!

I use `UPPERCASE_WITH_UNDERSCORES`  for the constants variable names, my problem is more about the "myConfig" in my example. Should we specify constant in the name?

```
angular
    .module('abp001App', ['ngRoute'])
    .constant("myConfig", {
        "URL": "http://localhost",
        "PORT": "80"
    })
```

**Comment by gkalpak** [comment]
I usually do:

```js
.constant('MY_CONFIG', {
  url: '...',
  port: '...'
})
```

<sub>(But that's not necessarily what others do :smiley:)</sub>

**Comment by mmefriantine** [comment]
I like it!
Thank you very much for your time

**Comment by wardbell** [comment]
UPPER_SNAKE_CASE is the convention. We should add it to styles and lint  for it.

**Comment by johnpapa** [comment]
yes.

added here https://github.com/angular/angular.io/issues/1451
