### ISSUE TITLE
HostBinding and Pipes in Angular 2

### ISSUE THREAD

**Issue by bczengel** [johnpapa/angular-styleguide#737]
I'm trying to use ChangeDectionStrategy.OnPush and Rx.Subjects to increase the performance of my application.  I'm having trouble following the style guide as it pertains to the `@HostBinding` decorator.  If I use the the host property in the Component definition, I can use the Async pipe.

    host: {
        'class.foo': 'bar | async'
    }

I haven't been able to figure out a good way to do this using the `@HostBinding` decorator.

**Comment by johnpapa** [comment]
a question better for SO
