### ISSUE TITLE
Style 02-05 - bootstrapping - consider renaming main.ts to app.ts or root.ts

### ISSUE THREAD

**Issue by jhades** [johnpapa/angular-styleguide#738]
In section Style 02-05, its mentioned that the entry point of the app should be main.ts. 

This would lead to the creation of a component with selector 'main' for consistency between the file name and the selector.

The problem is that 'main' is a standard existing HTML 5 selector. If the developer would create a page with a typical layout using HTML 5 tags like head, aside, footer, main, etc. and then inside main
it puts somewhere the entry point of the application:

    <header></header>
    
    <main> 

        ... some more layout

        ... the entry point of the app
        <main></main>

    </main>

The program would not work as expected. The application would be applied to the outer main. This would be especially confusing for someone just getting started. 

I would suggest to rename the root component to something other than main, to avoid this minor confusion.

**Comment by bampakoa** [comment]
@jhades **main.ts** is used only for bootstrapping and platform logic. You do not need to create a component for this. Nevertheless, in any component that you create, according to **02-07** style guide, use a custom prefix for your selector to mitigate these problems.

**Comment by johnpapa** [comment]
all A2 styles are now in the A2 repo.
