### ISSUE TITLE
IIFE  - recommend tools

### ISSUE THREAD

**Issue by mrt123** [johnpapa/angular-styleguide#739]
We recommend IFFE, and for brevity we remove it from rest of the style-guide. 

Shouldn't we mention tools which can wrap files automatically, so followers of this guide can achieve said brevity for their own source code?

We seem to be doing tool recommendations on other topics, like here: https://github.com/johnpapa/angular-styleguide/blob/master/a1/README.md#minification-and-annotation
where we recommend a specific gulp tool.

Lets mention gulp-wrap or similar. It supports any template, so things like "use strict" can also be automated: 
Example: http://stackoverflow.com/questions/25508427/use-gulp-to-wrap-javascript-files-with-a-iife

Alternatively lets just mention tooling as viable/recommended option.

**Comment by johnpapa** [comment]
feel free to use a tool ... but its not needed to mention in the guide, IMO. And if folks want it ... Google will now find it here in this issue :) Which is good

Thanks!
