### ISSUE TITLE
Question about my "model" service

### ISSUE THREAD

**Issue by gandaldf** [johnpapa/angular-styleguide#742]
Hi all, I'm trying to develop a "model" service to keep my shared data synchronized between my controllers.
I ended up with this solution:

```
myApp.factory('UserService', function() {
  return {
    data: {
      user: {
        vm: {
          firstName: '',
          lastName: ''
        },
        save: function() {
        	console.log("save user");
        }
      },
      settings: {
        vm: {
          theme: '',
          language: '',
          currency: ''
        },
        save: function() {
        	console.log("save user settings");
        }
      },
      save: function() {
      	console.log("save all");
      }
    }
  };
});
```

(fiddle here to better understand how it works: http://jsfiddle.net/n36kpuf6/).
I don't think it's a bad solution, it keeps my HTML tidy and I can see at the glance what functions I can use in my controllers, keeping them slim; I prefer it among other solutions of data-sharing based on events or $scope...
At the same time I'm thinking that, maybe, it's a bit confused; so I was searching trough the styleguide how I can keep it better organized, but I can't find anything about this kind of "model" services, just "standard" services (based on methods)... so I ended up thinking that I miss something.
Can someone please give me advices on how I can keep my service better organized?

**Comment by JuanHB** [comment]
For small projects your structure is ok, but when things start to grow you will be in a code-hell very quickly.
This style guide is meant to bring peace to your mind when doing any kind of AngularJS, so stick to the rules and you will be fine.

I've made a plnkr with an example following your idea and the style guide rules: [http://plnkr.co/edit/XNQ0H9z89PkUV5dBHhJQ](http://plnkr.co/edit/XNQ0H9z89PkUV5dBHhJQ?p=preview)

**Comment by gandaldf** [comment]
@JuanHB thank you, I ended up splitting my project in different files like you done in your plunker.
I just posted the service for reference; I would closing the issue.

**Comment by johnpapa** [comment]
probably best for SO.
