### ISSUE TITLE
Internationalization / Translation

### ISSUE THREAD

**Issue by phackwer** [johnpapa/angular-styleguide#748]
Are there any translation efforts currently being made for portuguese and spanish? Can we start one?

**Comment by johnpapa** [comment]
there are some for angular 1 already in here. check them out.

and *yes* ... please contribute :)

**Comment by AFelipeTrujillo** [comment]
@phackwer check !

https://github.com/johnpapa/angular-styleguide/tree/master/a1/i18n

Cheers !!
