### ISSUE TITLE
Problems with plus char in URL when using IIS

### ISSUE THREAD

**Issue by mbeckenbach** [johnpapa/angular-styleguide#749]
Hi, 

the ng2 style guide tells us to create folders that start with a + sign for lazy loaded routes. 
This causes problems with IIS default security policy and should be considered to be replaced by a char that is trusted. Underscore works fine for example.

Best regards 

Max

**Comment by wardbell** [comment]
One problem with `_` is that some servers refuse to serve content from a folder whose name begins with that character.

It's looking like a *no win* situation.  

We are looking into two possible changes to our recommendations:

1) "Pick a distinguishing prefix character (such as `+` or `_`) that works for your intended production server technology".

2) Abandoning the need for a prefix altogether as more trouble than it's worth.

Stay tuned.

**Comment by Brocco** [comment]
FYI, the CLI currently supports the customization of the `lazyRoutePrefix` via `angular-cli.json` You can view he [source code here](https://github.com/angular/angular-cli/blob/03fd4c49148022cee34ef70471252cbc6af85a64/addon/ng2/blueprints/ng2/files/angular-cli.json#L30)

**Comment by mbeckenbach** [comment]
I know. I've seen that. But having a style guide that tells you something that will immediately fail after deploying to your server is not a good developer experience. Also not everyone uses cli.

IIS allows you to overwrite that security setting. But first it is not recommended and second changing these settings is not allowed by a lot of hosting providers.

In my opinion especially for new ng2 developers the experience should be like "wow, it just works out of the box!" instead of "oh no, why does my code work on the dev machine but not in production?". If this can be achieved by simply changing the style guide to use another letter in urls, perfect. :)

**Comment by wardbell** [comment]
@mbeckenbach As I said above, there is no one prefix character that both serves the intended purpose of highlighting potentially async routes AND works for all servers. We can no more cater to IIS than we can to Harp or something else.

I think the only safe resolution is to abandon the default prefix altogether. That would mean

1) updating the style guide to offer an "option" to establish a prefix ... but admitting that no prefix is ok too.

2) Resetting the default value of the prefix to the empty string.

If agreed, we'll need PRs for both. Any volunteers?
