### ISSUE TITLE
JSDocs -> NGDocs

### ISSUE THREAD

**Issue by coryellenberger** [johnpapa/angular-styleguide#765]
Hello there; 

I would like to suggest updating this style: https://github.com/johnpapa/angular-styleguide/blob/master/a1/README.md#style-y220
to specify the Angular Standard for JS Documentation: https://github.com/angular/angular.js/wiki/Writing-AngularJS-Documentation

Using NGDocs; which is built on top of JSDocs so supports all the typical directives. But in addition includes Angular specific directives.

**Comment by johnpapa** [comment]
interesting thought. but I'm not sure the docs should ever have been in the guide in the first place. going to let this one sit.
