### ISSUE TITLE
Translation to Spanish

### ISSUE THREAD

**Issue by hartlink** [johnpapa/angular-styleguide#779]
Is posible to create a translation of this Angular style guide on Spanish, I'm working on Angular 1 and move on to Angular 2, so I can collaborate creating a translate of this guide.

Thank you in advance. 

Regards.

**Comment by primerproyecto** [comment]
Good idea ...i can colaborate with the spanish translations too.

**Comment by hartlink** [comment]
Translations are here: https://github.com/johnpapa/angular-styleguide/tree/master/a1/i18n

So forget it, thank you!
