### ISSUE TITLE
No IIFE needed if using a JS module system

### ISSUE THREAD

**Issue by mheiber** [johnpapa/angular-styleguide#795]
Suggestion: Remove the recommendation to wrap code in IIFEs, instead say to use ES2015 modules. Using JS modules has been a best practice in development for several years, and simply concatenating source files together in 2016 and beyond is a no-no, in my opinion. 

CommonJS modules are also a good option, but ES2015 modules will be more future-proof.

**Comment by jrmlstfMt** [comment]
These styleguides are written for ECMAScript 5/Strict.

Have a look at the ES2015/ES6 fork : https://github.com/rwwagner90/angular-styleguide-es6

**Comment by mheiber** [comment]
@jrmlstfMt thanks for that link. If this is an ES5/Strict style guide, then using CommonJS modules and a tool like Browserify or Webpack would be better practice than concatenating files and using IIFE's, right?

**Comment by mattbrunetti** [comment]
@mheiber Yes, I think that's right

@jrmlstfMt Isn't writing in ES2015 the best practice yet? The latest versions of all the major browsers (which are all ever-green now) support it, and we have transpilers like babel and traceur for backwards compatibility until the old versions die out. What do you think? Let's discuss.

**Comment by dietergeerts** [comment]
There is no harm in using them....

**Comment by mheiber** [comment]
@dietergeerts have to say I think modules are pretty valuable, some of the reasons are in here: http://eloquentjavascript.net/10_modules.html .

**Comment by johnpapa** [comment]
modules are indeed awesome. However using ES6/2015+ or TypeScript with Angular 1 is very very different than ES5. Thus, this style guide would need considerable overhaul to go there. It is much more pervasive than just using modules. For example ...  with modules changing, we also need to consider revising the entire build process.

I'm closing this issue as while I agree modules are awesome and I love them ... for this to work i would want a ES+ branch with all styles updated for it.

**Comment by jrmlstfMt** [comment]
@johnpapa I agree too, modules are awesome and should be used if possible.

@dietergeerts yep, not bad, only less futur-proof.

@mheiber As @johnpapa said, if you want to use modules, you'll need a module bundler even if it's ES5/CommonJs modules. Then you'll need to adapt these styleguide architecture for require/export. I'm currently working on a project with Webpack/Angular1/ES5/CommonJS. But I don't have enough time to propose a branch. It's something like :

```js
// avengers.module.js
'use strict';

var AvengersController = require('./avengers.controller.js');
var avengersRoutes = require('./avengers.routes.js');

angular
  .module('app.avengers', [])
  .config(avengersRoutes)
  .controller('AvengersController', AvengersController);
```

```js
// avengers.controller.js
'use strict';

require('./nginclude.html');

var AvengersController = function ($log) {
  var vm = this;
  vm.title = '';

  activate();

      // //////////////

  function activate () {
    $log.info('AvengersController activated');
  };
};

AvengersController.$inject = ['$log'];

module.exports = AvengersController;
```
