### ISSUE TITLE
upgrade to 1.6.2 issue

### ISSUE THREAD

**Issue by cht8687** [johnpapa/angular-styleguide#815]
My component is working in 1.5, it is declared like below:

```javascript

(function() {
'use strict';

angular
    .module('myModule')
    .component('myComponent', myComponent());

function myComponent() {
    var component = {
        bindings: {
            dateOptions: '='
        },
        templateUrl: 'myComponent.component.html',
        controller: MyController
    };
    return component;
}


function MyController() {
    var vm = this;

    vm.getData = getData;

    vm.$onInit = function() {

    };

    function getDate() {
        var options = {
            config: vm.dateOptions.config
        };
    }

}
})();
```

html:

```html
<div  class="datearea" ng-click="$ctrl.getDate()">

</div>
```
when I fire the ng-click, it says:

Cannot read property 'config' of undefined

which is the line : config: vm.dateOptions.config

Really interest to know what caused this issue? And I would not use the temp fix: $compileProvider.preAssignBindingsEnabled(true);

Just thinking if it is the problem with this style as controller is hoisted functions.

**Comment by cht8687** [comment]
it turns out that dateOptions was not properly sent by it's parent, nothing wrong with this style.

**Comment by zongming** [comment]
getDate and getData, did you misspell something?
