### ISSUE TITLE
Can you give simple Hello World Program?

### ISSUE THREAD

**Issue by muralitharanvellaisamy** [johnpapa/angular-styleguide#834]
I have Follow Your Style Guide, But i cannot get clear view and folder structure  can give any simple example?

**Comment by FrancescoRizzi** [comment]
For a1 I usually refer to the [modular demo](https://github.com/johnpapa/ng-demos/tree/master/modular) app, and its [source/client](https://github.com/johnpapa/ng-demos/tree/master/modular/src/client).

In general terms, it's a "modular" folder structure.. so if you have modules corresponding to your app's pages/states, you'll have a directory (within /app ) for each module (with a <module>.app.js, <module>.html and <module>.js within), plus a directory for each service or directive. Although for extremely simple services used only by that app (and by most or all of the pages/modules in the app), I might put them all in a single /services directory/module.

HTH (and of course, I'm just a simple "reader/user" of JP's style guide, so don't take my voice as authoritative)

**Comment by johnpapa** [comment]
thanks
