### ISSUE TITLE
JSHint support

### ISSUE THREAD

**Issue by adben** [johnpapa/angular-styleguide#89]
It is possible to integrate most of the rules in this styleguide to a [JSHint](http://www.jshint.com/) valid format?

**Comment by grifjef** [comment]
Are you saying the JShint section of the readme covers enforcement of the style guide, or are there custom JShint rules you've created?

**Comment by johnpapa** [comment]
oh, i just realized i think you were asking if these guidelines could become rules in jshint. is that what you meant? if so, no. they could become custom eslint or jscs rules ... in fact id love to get community help on doing that.

**Comment by nickroberts** [comment]
A .jscsrc file would be great. If anyone can get to that, awesome! If I can get the time to, I'll start to work on it.

Awesome style guide, btw!

**Comment by joeskeen** [comment]
@johnpapa Do you know if anyone has started a project for custom eslint or jscs rules to help keep your code in line with the style guide?  I would love to be involved in such a project if there is one, or help start one up.

**Comment by zachlysobey** [comment]
see https://github.com/johnpapa/angular-styleguide/pull/530 and https://www.npmjs.com/package/eslint-plugin-angular

**Comment by gustavomick** [comment]
@johnpapa hi, any news or thoughts about this?

**Comment by brutalcrozt** [comment]
@gustavomick see #530 , IMO better use eslint and use eslint-plugin-angular
